/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@interface _ABAddressBookCopyArrayOfAllGroups (XMPPBinaryCoder)
- (BOOL)wa_isHex8Encodable;
- (BOOL)wa_isNibble8Encodable;
@end

