/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@interface _ABAddressBookCopyArrayOfAllGroups (X_WA_Metadata)
- (id)wa_fileHash;
- (id)wa_fileType;
- (id)wa_metadataHeaderValueForKey:(id)fp8;
- (id)wa_headerValueForKey:(id)fp8;
- (id)wa_metadata;
@end

