/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WAActionSheetPresenter.h"
#import "UIActionSheetDelegate.h"

@class NSMutableDictionary, NSString, UIActionSheet;

__attribute__((visibility("hidden")))
@interface _WAActionSheetPresenterOS7 : WAActionSheetPresenter <UIActionSheetDelegate> {
	UIActionSheet* _actionSheet;
	UIActionSheet* _retainedActionSheetBeforePresentation;
	NSMutableDictionary* _actionMap;
	id _destructiveActionHandler;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(void)didPresentActionSheet:(id)sheet;
-(void)actionSheet:(id)sheet didDismissWithButtonIndex:(int)buttonIndex;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)addCancelButton;
-(void)addDestructiveButtonWithTitle:(id)title handler:(id)handler;
-(void)addButtonWithTitle:(id)title handler:(id)handler;
-(void)dismissByCancellingWithAnimation:(BOOL)animation;
-(void)presentFromViewController:(id)viewController;
-(id)initWithTitle:(id)title;
@end

