/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import "WAContactPopup.h"

@class UIImage;

__attribute__((visibility("hidden")))
@interface _WAContactPopupOS6 : WAContactPopup {
	UIImage* _topImage;
	UIImage* _bottomLeft;
	UIImage* _bottomArrow;
	UIImage* _bottomRight;
	UIImage* _pinImage;
}
-(void).cxx_destruct;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)drawRect:(CGRect)rect;
-(void)setAnnotation:(id)annotation;
-(void)setImageTag:(int)tag;
-(id)initWithAnnotation:(id)annotation reuseIdentifier:(id)identifier;
@end

