/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class NSLayoutConstraint, UILabel;

__attribute__((visibility("hidden")))
@interface _WACountryTableViewCell : UITableViewCell {
	NSLayoutConstraint* _countryCodeTrailingToSuperview;
	UILabel* _countryNameLabel;
	UILabel* _countryCodeLabel;
}
@property(readonly, assign, nonatomic) UILabel* countryCodeLabel;
@property(readonly, assign, nonatomic) UILabel* countryNameLabel;
-(void).cxx_destruct;
-(void)setAccessoryType:(int)type;
-(void)addAutoLayoutConstraints;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

