/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_WAConversationHeaderViewLegacy.h"

@interface _WAConversationHeaderViewMap : _WAConversationHeaderViewLegacy
{
}

- (void)configureTitleAndCaption;
- (id)captionFontForCompactHeight:(BOOL)fp8 groupLayout:(BOOL)fp12;
- (id)titleFontForCompactHeight:(BOOL)fp8 groupLayout:(BOOL)fp12;
- (void)setCaption:(id)fp8;
- (void)setTitle:(id)fp8;

@end

