/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


__attribute__((visibility("hidden")))
@interface _WACameraPreviewAnimation : NSObject {
	BOOL _completed;
	id _callback;
	id _completionHandler;
	double _duration;
	double _startTime;
}
@property(assign, nonatomic, getter=isCompleted) BOOL completed;
@property(assign, nonatomic) double startTime;
@property(assign, nonatomic) double duration;
@property(copy, nonatomic) id completionHandler;
@property(copy, nonatomic) id callback;
-(void).cxx_destruct;
@end

