/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class NSLayoutConstraint, UILabel;

@interface _WACountryTableViewCell : _ABAddressBookCopyArrayOfAllGroups
{
    NSLayoutConstraint *_countryCodeTrailingToSuperview;
    UILabel *_countryNameLabel;
    UILabel *_countryCodeLabel;
}

- (id)countryCodeLabel;
- (id)countryNameLabel;
- (void).cxx_destruct;
- (void)setAccessoryType:(int)fp8;
- (void)addAutoLayoutConstraints;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;

@end

