/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol _WAContainerScrollViewDelegate <NSObject>
-(void)containerScrollViewDidEndDecelerating:(id)containerScrollView;
-(void)containerScrollViewDidEndDragging:(id)containerScrollView willDecelerate:(BOOL)decelerate;
-(void)containerScrollViewDidScroll:(id)containerScrollView;
@end

