/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class UIColor;

@interface _WACustomSeparatorView : _ABAddressBookCopyArrayOfAllGroups
{
    UIColor *_separatorColor;
}

- (id)separatorColor;
- (void).cxx_destruct;
- (void)setSeparatorColor:(id)fp8;
- (void)drawRect:(struct CGRect)fp8;

@end

