/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAContactPopup.h"

@class UIImage, UIView;

@interface _WAContactPopupOS7 : WAContactPopup
{
    UIImage *_bottomArrow;
    UIView *_viewBody;
    UIImage *_pinImage;
}

- (void).cxx_destruct;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)drawRect:(struct CGRect)fp8;
- (void)setAnnotation:(id)fp8;
- (void)setImageTag:(int)fp8;
- (id)initWithAnnotation:(id)fp8 reuseIdentifier:(id)fp12;

@end

