/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import <UIKit/UIView.h>

@class UILabel, UIImageView;

__attribute__((visibility("hidden")))
@interface _WADirectionsButtonContentView : UIView {
	UIImageView* _imageViewCarIcon;
	UILabel* _labelETA;
}
-(void).cxx_destruct;
-(void)setETADurationString:(id)string;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
@end

