/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import <UIKit/UIButton.h>

@class UIActivityIndicatorView;

__attribute__((visibility("hidden")))
@interface _WADoneWithSpinnerButton : UIButton {
	BOOL _rightAligned;
	UIActivityIndicatorView* _spinner;
}
@property(readonly, assign, nonatomic) UIActivityIndicatorView* spinner;
@property(assign, nonatomic) BOOL rightAligned;
-(void).cxx_destruct;
-(void)layoutSubviews;
-(UIEdgeInsets)alignmentRectInsets;
-(id)initWithFrame:(CGRect)frame;
@end

