/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class WAURLSessionTask;

@interface _WADeferredTaskOperation : _ABAddressBookCopyArrayOfAllGroups
{
    BOOL _isAddOperation;
    WAURLSessionTask *_task;
}

- (void)setTask:(id)fp8;
- (id)task;
- (void)setIsAddOperation:(BOOL)fp8;
- (BOOL)isAddOperation;
- (void).cxx_destruct;

@end

