/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import <UIKit/UIView.h>

@class UIImageView;

__attribute__((visibility("hidden")))
@interface _WADividerCellBackground : UIView {
	UIImageView* _imageViewTop;
	UIImageView* _imageViewMiddle;
	UIImageView* _imageViewBottom;
}
-(void).cxx_destruct;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
@end

