/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class UILabel;

@interface _WAFAQBrowserTableViewCell : _ABAddressBookCopyArrayOfAllGroups
{
    UILabel *_bodyLabel;
}

+ (float)maximumContentWidthExcludingInsets;
+ (float)preferredRowHeightForText:(id)fp8 width:(float)fp12;
+ (id)preferredBodyFont;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)configureWithContents:(id)fp8;
- (id)initWithReuseIdentifier:(id)fp8;

@end

