/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class UIImageView, UILabel;

@interface _WAForwardPickerEmptyListView : _ABAddressBookCopyArrayOfAllGroups
{
    UIImageView *_imageView;
    UILabel *_label;
}

- (void).cxx_destruct;
- (void)setText:(id)fp8;
- (id)text;
- (void)setImage:(id)fp8;
- (id)image;
- (id)initWithFrame:(struct CGRect)fp8;

@end

