/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import <UIKit/UIView.h>

@class UILabel, UIImageView;

__attribute__((visibility("hidden")))
@interface _WAGroupMessageDetailsTableHeaderView : UIView {
	UIView* _topBorder;
	UIView* _bottomBorder;
	BOOL _showTopBorder;
	BOOL _showBottomBorder;
	UILabel* _titleLabel;
	UIImageView* _imageView;
}
@property(assign, nonatomic) BOOL showBottomBorder;
@property(assign, nonatomic) BOOL showTopBorder;
@property(readonly, assign, nonatomic) UIImageView* imageView;
@property(readonly, assign, nonatomic) UILabel* titleLabel;
-(void).cxx_destruct;
-(void)setBorderColor:(id)color;
-(void)setBottomBorderHidden:(BOOL)hidden;
-(void)setTopBorderHidden:(BOOL)hidden;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
@end

