/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@interface _WAGrabHandleLayer : _ABAddressBookCopyArrayOfAllGroups
{
    float _radius;
}

+ (BOOL)needsDisplayForKey:(id)fp8;
- (void)setRadius:(float)fp8;
- (float)radius;
- (id)initWithLayer:(id)fp8;

@end

