/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UISearchBar.h>

@class UIView;

__attribute__((visibility("hidden")))
@interface _WAImageSearchBar : UISearchBar {
	UIView* _backgroundView;
	UIView* _bottomBorderView;
}
-(void).cxx_destruct;
-(void)layoutSubviews;
-(void)awakeFromNib;
@end

