/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import <UIKit/UIView.h>

@class UIColor;

__attribute__((visibility("hidden")))
@interface _WAPieView : UIView {
	UIColor* _fillColor;
}
@property(retain, nonatomic) UIColor* fillColor;
@property(assign, nonatomic) float progress;
+(Class)layerClass;
-(void).cxx_destruct;
-(void)drawRect:(CGRect)rect;
-(void)setProgress:(float)progress animated:(BOOL)animated;
-(id)initWithFrame:(CGRect)frame;
@end

