/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class CAAnimation, UIImageView;

@interface _WASpinner : _ABAddressBookCopyArrayOfAllGroups
{
    UIImageView *_imageView;
    BOOL _animating;
    CAAnimation *_animation;
}

- (void).cxx_destruct;
- (void)stopAnimating;
- (void)animationDidStop:(id)fp8 finished:(BOOL)fp12;
- (void)performAnimation;
- (void)startAnimating;
- (id)init;

@end

