/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_WAMapButton.h"

@interface _WAStaticPinButton : _WAMapButton
{
    BOOL _staticPinHidden;
}

- (BOOL)staticPinHidden;
- (id)accessibilityLabel;
- (void)setStaticPinHidden:(BOOL)fp8;
- (void)reloadButtonImage;
- (void)commonInit;

@end

