/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>

@class CAAnimation, UIImageView;

__attribute__((visibility("hidden")))
@interface _WASpinner : UIView {
	UIImageView* _imageView;
	BOOL _animating;
	CAAnimation* _animation;
}
-(void).cxx_destruct;
-(void)stopAnimating;
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
-(void)performAnimation;
-(void)startAnimating;
-(id)init;
@end

