/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WATimelockViewController.h"

@interface _WATimelockViewControllerModern : WATimelockViewController
{
}

+ (id)controller;
- (void)learnMoreAction:(id)fp8;
- (void)reloadHelperText;
- (int)preferredStatusBarStyle;
- (void)viewDidLoad;

@end

