/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSSecureCoding.h"
#import </libobjc.A.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface _WAURLSessionDownloadTaskResumeDataOS6 : NSObject <NSSecureCoding> {
	NSString* _filePath;
	NSString* _etag;
}
@property(copy, nonatomic) NSString* etag;
@property(copy, nonatomic) NSString* filePath;
+(BOOL)supportsSecureCoding;
-(void).cxx_destruct;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
@end

