/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import <UIKit/UIView.h>

@class UIColor;

__attribute__((visibility("hidden")))
@interface _WAVideoScrubberStripedBar : UIView {
	CGPatternRef _pattern;
	float _spacing;
	UIColor* _stripeColor;
}
@property(retain, nonatomic) UIColor* stripeColor;
@property(assign, nonatomic) float spacing;
-(void).cxx_destruct;
-(void)drawRect:(CGRect)rect;
-(void)rebuildPattern;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

