/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import <UIKit/UIView.h>

@class UILabel, NSString;

__attribute__((visibility("hidden")))
@interface _WAVerificationCodeView : UIView {
	UILabel* _codeLabel;
	UILabel* _helperTextLabel;
	CGSize _boundsSize;
	BOOL _needsReloadText;
	NSString* _formattedCode;
}
@property(copy, nonatomic) NSString* formattedCode;
+(id)helperTextFontOfSize:(float)size;
+(id)verificationCodeFontOfSize:(float)size;
-(void).cxx_destruct;
-(void)reloadTextIfNeeded;
-(void)setNeedsReloadText;
-(void)setFrame:(CGRect)frame;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
@end

