/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class XMPPStanzaElement, NSString, XMPPNotificationStanza;

__attribute__((visibility("hidden")))
@interface _WAWebClientDeferredTaskInfo : NSObject {
	XMPPStanzaElement* _task;
	XMPPNotificationStanza* _parentNotification;
	NSString* _webRef;
}
@property(copy, nonatomic) NSString* webRef;
@property(retain, nonatomic) XMPPNotificationStanza* parentNotification;
@property(retain, nonatomic) XMPPStanzaElement* task;
-(void).cxx_destruct;
@end

