/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAViewController.h"

@class UIButton, UIImageView, UILabel;

@interface ABDisabledViewController : WAViewController
{
    UIImageView *_imageViewLock;
    UILabel *_labelHelperTop;
    UILabel *_labelHelperBottom;
    UIButton *_buttonSettings;
    id <ABDisabledControllerDelegate> _delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)wa_fontSizeDidChange;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)viewDidLayoutSubviews;
- (void)loadView;
- (id)bottomHelperText;
- (void)cancelAction:(id)fp8;
- (void)openSettingsAction:(id)fp8;
- (void)layoutHelperLabels;
- (void)reloadFonts;
- (id)initWithDelegate:(id)fp8;

@end

