/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol ABNewPersonViewControllerDelegate <NSObject>
-(void)newPersonViewController:(id)controller didCompleteWithNewPerson:(const void*)newPerson;
@end

