/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WAViewController.h"
#import "ABDisabledControllerDelegate.h"

@class UITableView, UILabel, NSString, UIView, WASupportEmailComposer, UIImageView, UITableViewCell;

__attribute__((visibility("hidden")))
@interface AboutViewController : WAViewController <ABDisabledControllerDelegate> {
	WASupportEmailComposer* _emailComposer;
	UITableViewCell* _cellHelpFAQ;
	UITableViewCell* _cellContactUs;
	UITableView* _tableViewButtons;
	UIView* _viewDivider;
	UIView* _viewLogoContainer;
	UIImageView* _imageLogo;
	UIImageView* _imageWP;
	UILabel* _labelTitlePortrait;
	UILabel* _labelVersionPortrait;
	UIView* _viewTableHeader;
	UILabel* _labelTitleLandscape;
	UILabel* _labelVersionLandscape;
	UIView* _footerView;
	UILabel* _labelCopyright;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) UILabel* labelCopyright;
@property(retain, nonatomic) UIView* footerView;
@property(retain, nonatomic) UILabel* labelVersionLandscape;
@property(retain, nonatomic) UILabel* labelTitleLandscape;
@property(retain, nonatomic) UIView* viewTableHeader;
@property(retain, nonatomic) UILabel* labelVersionPortrait;
@property(retain, nonatomic) UILabel* labelTitlePortrait;
@property(retain, nonatomic) UIImageView* imageWP;
@property(retain, nonatomic) UIImageView* imageLogo;
@property(retain, nonatomic) UIView* viewLogoContainer;
@property(retain, nonatomic) UIView* viewDivider;
@property(retain, nonatomic) UITableView* tableViewButtons;
-(void).cxx_destruct;
-(id)helperTextForABDisabledViewController:(id)abdisabledViewController;
-(id)helperTitleForABDisabledViewController:(id)abdisabledViewController;
-(void)abDisabledViewControllerDidCancel:(id)abDisabledViewController;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view willSelectRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForFooterInSection:(int)section;
-(id)tableView:(id)view viewForFooterInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)wa_fontSizeDidChange;
-(void)wa_tintColorDidChange;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)viewDidLayoutSubviews;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidLoad;
-(void)openFAQAction;
-(void)contactUsAction;
-(void)setContactUsCellEnabled:(BOOL)enabled;
-(void)updateLayoutToOrientation:(int)orientation;
-(void)dealloc;
-(id)init;
@end

