/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAViewController.h"

#import "ABDisabledControllerDelegate-Protocol.h"

@class UIImageView, UILabel, UITableView, UITableViewCell, UIView, WASupportEmailComposer;

@interface AboutViewController : WAViewController <ABDisabledControllerDelegate>
{
    WASupportEmailComposer *_emailComposer;
    UITableViewCell *_cellHelpFAQ;
    UITableViewCell *_cellContactUs;
    UITableView *_tableViewButtons;
    UIView *_viewDivider;
    UIView *_viewLogoContainer;
    UIImageView *_imageLogo;
    UIImageView *_imageWP;
    UILabel *_labelTitlePortrait;
    UILabel *_labelVersionPortrait;
    UIView *_viewTableHeader;
    UILabel *_labelTitleLandscape;
    UILabel *_labelVersionLandscape;
    UIView *_footerView;
    UILabel *_labelCopyright;
}

- (void)setLabelCopyright:(id)fp8;
- (id)labelCopyright;
- (void)setFooterView:(id)fp8;
- (id)footerView;
- (void)setLabelVersionLandscape:(id)fp8;
- (id)labelVersionLandscape;
- (void)setLabelTitleLandscape:(id)fp8;
- (id)labelTitleLandscape;
- (void)setViewTableHeader:(id)fp8;
- (id)viewTableHeader;
- (void)setLabelVersionPortrait:(id)fp8;
- (id)labelVersionPortrait;
- (void)setLabelTitlePortrait:(id)fp8;
- (id)labelTitlePortrait;
- (void)setImageWP:(id)fp8;
- (id)imageWP;
- (void)setImageLogo:(id)fp8;
- (id)imageLogo;
- (void)setViewLogoContainer:(id)fp8;
- (id)viewLogoContainer;
- (void)setViewDivider:(id)fp8;
- (id)viewDivider;
- (void)setTableViewButtons:(id)fp8;
- (id)tableViewButtons;
- (void).cxx_destruct;
- (id)helperTextForABDisabledViewController:(id)fp8;
- (id)helperTitleForABDisabledViewController:(id)fp8;
- (void)abDisabledViewControllerDidCancel:(id)fp8;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 willSelectRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForFooterInSection:(int)fp12;
- (id)tableView:(id)fp8 viewForFooterInSection:(int)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)wa_fontSizeDidChange;
- (void)wa_tintColorDidChange;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewDidLoad;
- (void)openFAQAction;
- (void)contactUsAction;
- (void)setContactUsCellEnabled:(BOOL)fp8;
- (void)updateLayoutToOrientation:(int)fp8;
- (void)dealloc;
- (id)init;

@end

