/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WALinkLabelDelegate.h"
#import "WAStaticTableViewController.h"

@class WALinkLabel, UISwitch, NSString, WATableRow, WATableSection;

__attribute__((visibility("hidden")))
@interface AccountViewController : WAStaticTableViewController <WALinkLabelDelegate> {
	BOOL _showShareAccountInfoSwitch;
	BOOL _shareAccountOptOutInProgress;
	UISwitch* _switchShareAccountInfo;
	WATableRow* _rowShareAccountInfo;
	WATableSection* _sectionShareAccountInfo;
	WALinkLabel* _shareAccountInfoSectionFooter;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(void)wa_applicationDidEnterBackground;
-(id)tableView:(id)view viewForFooterInSection:(int)section;
-(float)tableView:(id)view heightForFooterInSection:(int)section;
-(void)setupTableView;
-(void)wa_fontSizeDidChange;
-(void)viewDidLayoutSubviews;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)handleOpenURL:(id)url fromLinkLabel:(id)linkLabel;
-(void)optOutOfSharingAccountInfo;
-(void)switchAccountInfoSharingChanged:(id)changed;
-(void)adjustFooterViewInsetsForInterfaceOrientation:(int)interfaceOrientation reloadTableIfChange:(BOOL)change;
-(void)addShareAccountInfoSwitchRow;
-(void)setShouldShowShareInfoOptOutSwich:(BOOL)showShareInfoOptOutSwich;
-(void)deleteAccountAction;
-(void)changeNumberAction;
-(void)showStorageUsage;
-(void)showAccountSecuritySettings;
-(void)setPrivacyAction;
-(id)initWithStyle:(int)style;
-(id)init;
@end

