/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAWarningViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WAVerificationCloudReminderViewControllerDelegate-Protocol.h"

@class NSNumber, NSString, NSTimer, UIActivityIndicatorView, UILabel, UISwitch, UIView, WABackupInfoTableCell, WACloudStatus, WAProgressHUD, WAUploadedBackup;

@interface BackupViewController : WAWarningViewController <UITableViewDataSource, UITableViewDelegate, WAVerificationCloudReminderViewControllerDelegate>
{
    WAProgressHUD *_progressHUD;
    double _hudDisplayedTime;
    NSTimer *_timer;
    BOOL _registered;
    BOOL _inProgress;
    float _sectionHeight;
    BOOL _showProgressText;
    BOOL _timerEnabled;
    BOOL _backupInProgress;
    BOOL _loadingVideoEstimate;
    WABackupInfoTableCell *_cellBackupInfo;
    UISwitch *_switchIncludeVideos;
    UIView *_viewTableFooter;
    UILabel *_labelProgressInfo;
    UIActivityIndicatorView *_activityIndicator;
    WACloudStatus *_cloudStatus;
    id _cloudStatusListener;
    WAUploadedBackup *_uploadedInformation;
    NSString *_backupStatusMessage;
    NSNumber *_videoEstimate;
}

- (void)setVideoEstimate:(id)fp8;
- (id)videoEstimate;
- (void)setLoadingVideoEstimate:(BOOL)fp8;
- (BOOL)loadingVideoEstimate;
- (id)backupStatusMessage;
- (BOOL)backupInProgress;
- (BOOL)timerEnabled;
- (void)setUploadedInformation:(id)fp8;
- (id)uploadedInformation;
- (void)setCloudStatusListener:(id)fp8;
- (id)cloudStatusListener;
- (void)setCloudStatus:(id)fp8;
- (id)cloudStatus;
- (void)setActivityIndicator:(id)fp8;
- (id)activityIndicator;
- (void)setLabelProgressInfo:(id)fp8;
- (id)labelProgressInfo;
- (void)setViewTableFooter:(id)fp8;
- (id)viewTableFooter;
- (BOOL)showProgressText;
- (void)setSwitchIncludeVideos:(id)fp8;
- (void)setCellBackupInfo:(id)fp8;
- (id)cellBackupInfo;
- (void).cxx_destruct;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 willSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForFooterInSection:(int)fp12;
- (id)tableView:(id)fp8 titleForFooterInSection:(int)fp12;
- (id)tableView:(id)fp8 viewForFooterInSection:(int)fp12;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)calculateVideoEstimate;
- (BOOL)tryToUpdateVideoEstimate;
- (BOOL)needsVideoEstimate;
- (void)changedIncludeVideos:(id)fp8;
- (id)switchIncludeVideos;
- (void)wa_fontSizeDidChange;
- (void)wa_tintColorDidChange;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (void)dismissModal:(id)fp8;
- (void)unregisterForBackupNotifications;
- (void)registerForBackupNotifications;
- (void)startBackupAction;
- (void)backupInformationUpdated:(id)fp8;
- (void)backupPhaseCompleted:(id)fp8;
- (void)updateBackupDetails;
- (void)setBackupInProgress:(BOOL)fp8;
- (void)checkForInProgressBackup;
- (void)layoutFooterViewAnimated:(BOOL)fp8;
- (void)setShowProgressText:(BOOL)fp8;
- (id)footerTextForUploadProgress:(float)fp8 size:(long long)fp12;
- (id)footerTextForCompressionProgress:(float)fp8;
- (void)setTimerEnabled:(BOOL)fp8;
- (void)updateProgressTimer;
- (void)invalidateProgressTimer;
- (void)scheduleProgressTimer;
- (void)updateProgressFromTimer:(id)fp8;
- (void)setBackupStatusMessage:(id)fp8;
- (void)updateBackupStatusMessage;
- (BOOL)hasCloudStatusNetworkError;
- (void)updateProgress;
- (void)cloudStatusUpdated;
- (void)stopAnimatingGears;
- (void)startAnimatingGears;
- (void)updateGearsAnimating;
- (void)removeHUD:(BOOL)fp8;
- (void)removeHUD;
- (void)showHUD:(id)fp8;
- (void)verificationCloudReminderControllerDidFinish:(id)fp8;
- (BOOL)verificationCloudReminderControllerShouldShowDoneButton:(id)fp8;
- (BOOL)verificationCloudReminderControllerShouldShowNextButton:(id)fp8;
- (void)showCloudInstructions;
- (void)showViewControllerFromErrorBanner:(id)fp8;
- (void)showAutobackupSettings;
- (void)dealloc;
- (void)updateErrorDisplay:(id)fp8;
- (void)backupErrorUpdated:(id)fp8;
- (id)init;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

