/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WANavigationController.h"

#import "GroupViewControllerDelegate-Protocol.h"

@class GroupViewController, NSMutableDictionary;

@interface ContactsNavigationController : WANavigationController <GroupViewControllerDelegate>
{
    GroupViewController *_groupController;
    NSMutableDictionary *_contactViewControllers;
}

- (void).cxx_destruct;
- (void)groupViewController:(id)fp8 didSelectGroupWithID:(id)fp12;
- (id)init;
- (void)popToMainViewControllerAnimated:(BOOL)fp8;
- (void)reloadViewControllers;
- (void)loadContactsViewController:(int)fp8;
- (void)loadGroupViewController;

@end

