/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


__attribute__((visibility("hidden")))
@interface CrashLogger : NSObject {
}
+(void)internalUploadDataUsingActiveLog:(BOOL)log footnote:(id)footnote discretionary:(BOOL)discretionary;
+(void)uploadDataUsingActiveLog:(BOOL)log footnote:(id)footnote discretionary:(BOOL)discretionary;
+(void)uploadDataOnLogRequest;
+(BOOL)crashOccurred;
+(void)setCrashOccurred:(BOOL)occurred;
+(BOOL)shouldUploadLogs;
+(BOOL)canUploadLogs;
+(void)uploadLogs:(id)logs discretionary:(BOOL)discretionary;
+(void)uploadLogData:(id)data filename:(id)filename discretionary:(BOOL)discretionary;
+(void)initialize;
@end

