/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol CSSearchableIndexDelegate <NSObject>
-(void)searchableIndex:(id)index reindexSearchableItemsWithIdentifiers:(id)identifiers acknowledgementHandler:(id)handler;
-(void)searchableIndex:(id)index reindexAllSearchableItemsWithAcknowledgementHandler:(id)acknowledgementHandler;
@optional
-(void)searchableIndexDidFinishThrottle:(id)searchableIndex;
-(void)searchableIndexDidThrottle:(id)searchableIndex;
@end

