/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITextViewDelegate.h"
#import "WhatsApp-Structs.h"
#import "WAViewController.h"

@class UITableViewCell, UITextView, NSString, UITableView, UILabel;
@protocol FeedbackInputControllerDelegate;

__attribute__((visibility("hidden")))
@interface FeedbackInputViewController : WAViewController <UITextViewDelegate> {
	float _keyboardHeight;
	id<FeedbackInputControllerDelegate> _delegate;
	UITableView* _tableViewFeedback;
	UITableViewCell* _cellFeedbackInput;
	UITextView* _textViewFeedback;
	UILabel* _labelPlaceholder;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) UILabel* labelPlaceholder;
@property(retain, nonatomic) UITextView* textViewFeedback;
@property(retain, nonatomic) UITableViewCell* cellFeedbackInput;
@property(retain, nonatomic) UITableView* tableViewFeedback;
@property(assign, nonatomic) __weak id<FeedbackInputControllerDelegate> delegate;
-(void).cxx_destruct;
-(void)keyboardWillShow:(id)keyboard;
-(int)tableView:(id)view editingStyleForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view willDisplayCell:(id)cell forRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(id)tableView:(id)view titleForFooterInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(BOOL)textView:(id)view shouldChangeTextInRange:(NSRange)range replacementText:(id)text;
-(void)textViewDidChange:(id)textView;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)nextAction:(id)action;
-(void)cancelAction:(id)action;
-(void)dealloc;
-(id)initWithDelegate:(id)delegate;
@end

