/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAViewController.h"

#import "UITextViewDelegate-Protocol.h"

@class UILabel, UITableView, UITableViewCell, UITextView;

@interface FeedbackInputViewController : WAViewController <UITextViewDelegate>
{
    float _keyboardHeight;
    id <FeedbackInputControllerDelegate> _delegate;
    UITableView *_tableViewFeedback;
    UITableViewCell *_cellFeedbackInput;
    UITextView *_textViewFeedback;
    UILabel *_labelPlaceholder;
}

- (void)setLabelPlaceholder:(id)fp8;
- (id)labelPlaceholder;
- (void)setTextViewFeedback:(id)fp8;
- (id)textViewFeedback;
- (void)setCellFeedbackInput:(id)fp8;
- (id)cellFeedbackInput;
- (void)setTableViewFeedback:(id)fp8;
- (id)tableViewFeedback;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)keyboardWillShow:(id)fp8;
- (int)tableView:(id)fp8 editingStyleForRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 willDisplayCell:(id)fp12 forRowAtIndexPath:(id)fp16;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (float)tableView:(id)fp8 heightForHeaderInSection:(int)fp12;
- (id)tableView:(id)fp8 titleForFooterInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (BOOL)textView:(id)fp8 shouldChangeTextInRange:(struct _NSRange)fp12 replacementText:(id)fp20;
- (void)textViewDidChange:(id)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (void)nextAction:(id)fp8;
- (void)cancelAction:(id)fp8;
- (void)dealloc;
- (id)initWithDelegate:(id)fp8;

@end

