/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import "NSCopying.h"
#import </libobjc.A.h>

@class GPBEnumDescriptor, NSString;

@interface GPBExtensionDescriptor : NSObject <NSCopying> {
	GPBExtensionDescription* description_;
	XXUnion_Or81$A defaultValue_;
	Class containingMessageClass_;
}
@property(readonly, assign, nonatomic) int alternateWireType;
@property(readonly, assign, nonatomic) int wireType;
@property(readonly, assign, nonatomic) id defaultValue;
@property(readonly, assign, nonatomic) GPBEnumDescriptor* enumDescriptor;
@property(readonly, assign, nonatomic) NSString* singletonName;
@property(readonly, assign, nonatomic) Class msgClass;
@property(readonly, assign, nonatomic, getter=isPackable) BOOL packable;
@property(readonly, assign, nonatomic, getter=isRepeated) BOOL repeated;
@property(readonly, assign, nonatomic) int dataType;
@property(readonly, assign, nonatomic) Class containingMessageClass;
@property(readonly, assign, nonatomic) unsigned fieldNumber;
-(int)compareByFieldNumber:(id)number;
-(BOOL)isMap;
-(const char*)singletonNameC;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(id)initWithExtensionDescription:(GPBExtensionDescription*)extensionDescription;
@end

