/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "GPBMessage.h"

@class GPBFieldOptions, NSString;

@interface GPBFieldDescriptorProto : GPBMessage {
}
@property(retain, nonatomic) GPBFieldOptions* options;
@property(assign, nonatomic) BOOL hasOptions;
@property(copy, nonatomic) NSString* jsonName;
@property(assign, nonatomic) BOOL hasJsonName;
@property(assign, nonatomic) int oneofIndex;
@property(assign, nonatomic) BOOL hasOneofIndex;
@property(copy, nonatomic) NSString* defaultValue;
@property(assign, nonatomic) BOOL hasDefaultValue;
@property(copy, nonatomic) NSString* extendee;
@property(assign, nonatomic) BOOL hasExtendee;
@property(copy, nonatomic) NSString* typeName;
@property(assign, nonatomic) BOOL hasTypeName;
@property(assign, nonatomic) int type;
@property(assign, nonatomic) BOOL hasType;
@property(assign, nonatomic) int label;
@property(assign, nonatomic) BOOL hasLabel;
@property(assign, nonatomic) int number;
@property(assign, nonatomic) BOOL hasNumber;
@property(copy, nonatomic) NSString* name;
@property(assign, nonatomic) BOOL hasName;
+(id)descriptor;
@end

