/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "GPBMessage.h"

@class NSMutableArray, NSString, GPBServiceOptions;

@interface GPBServiceDescriptorProto : GPBMessage {
}
@property(retain, nonatomic) GPBServiceOptions* options;
@property(assign, nonatomic) BOOL hasOptions;
@property(readonly, assign, nonatomic) unsigned methodArray_Count;
@property(retain, nonatomic) NSMutableArray* methodArray;
@property(copy, nonatomic) NSString* name;
@property(assign, nonatomic) BOOL hasName;
+(id)descriptor;
@end

