/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import "NSCopying.h"
#import </libobjc.A.h>
#import "GPBDictionaryInternalsProtocol.h"

@class NSMutableDictionary, GPBMessage;

@interface GPBUInt32EnumDictionary : NSObject <GPBDictionaryInternalsProtocol, NSCopying> {
	GPBMessage* _autocreator;
	NSMutableDictionary* _dictionary;
	/*function-pointer*/ void* _validationFunc;
}
@property(readonly, assign, nonatomic) /*function-pointer*/ void* validationFunc;
@property(readonly, assign, nonatomic) unsigned count;
+(id)dictionaryWithValidationFunction:(/*function-pointer*/ void*)validationFunction capacity:(unsigned)capacity;
+(id)dictionaryWithDictionary:(id)dictionary;
+(id)dictionaryWithValidationFunction:(/*function-pointer*/ void*)validationFunction rawValues:(const int*)values forKeys:(const unsigned*)keys count:(unsigned)count;
+(id)dictionaryWithValidationFunction:(/*function-pointer*/ void*)validationFunction rawValue:(int)value forKey:(unsigned)key;
+(id)dictionaryWithValidationFunction:(/*function-pointer*/ void*)validationFunction;
+(id)dictionary;
-(void)setValue:(int)value forKey:(unsigned)key;
-(void)removeAll;
-(void)removeValueForKey:(unsigned)key;
-(void)setRawValue:(int)value forKey:(unsigned)key;
-(void)addRawEntriesFromDictionary:(id)dictionary;
-(void)enumerateKeysAndValuesUsingBlock:(id)block;
-(BOOL)valueForKey:(unsigned)key rawValue:(int*)value;
-(BOOL)valueForKey:(unsigned)key value:(int*)value;
-(void)enumerateForTextFormat:(id)textFormat;
-(void)setGPBGenericValue:(XXUnion_vOMGVC*)value forGPBGenericValueKey:(XXUnion_vOMGVC*)gpbgenericValueKey;
-(id)serializedDataForUnknownValue:(int)unknownValue forKey:(XXUnion_vOMGVC*)key keyDataType:(int)type;
-(void)writeToCodedOutputStream:(id)codedOutputStream asField:(id)field;
-(unsigned long)computeSerializedSizeAsField:(id)field;
-(void)enumerateKeysAndRawValuesUsingBlock:(id)block;
-(id)description;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(id)initWithValidationFunction:(/*function-pointer*/ void*)validationFunction capacity:(unsigned)capacity;
-(id)initWithDictionary:(id)dictionary;
-(id)initWithValidationFunction:(/*function-pointer*/ void*)validationFunction rawValues:(const int*)values forKeys:(const unsigned*)keys count:(unsigned)count;
-(id)initWithValidationFunction:(/*function-pointer*/ void*)validationFunction;
-(id)init;
@end

