/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


__attribute__((visibility("hidden")))
@interface GZipFile : NSObject {
}
+(id)deflateData:(id)data originalFile:(id)file;
+(id)deflateFile:(id)file removeOriginalFile:(BOOL)file2;
@end

