/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol HostSelectorDelegate <NSObject>
- (void)hostSelectorDidCancel:(id)fp8;
- (void)hostSelector:(id)fp8 didEnterHostname:(id)fp12;
@end

