/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UISearchBarDelegate.h"
#import "WAViewController.h"
#import "WhatsApp-Structs.h"

@class UIView, UIButton, UISearchBar, NSMutableArray, NSString, UIImageView, UILabel, ImageListScrollView, UIActivityIndicatorView;
@protocol ImageSearchControllerDelegate;

__attribute__((visibility("hidden")))
@interface ImageSearchController : WAViewController <UISearchBarDelegate> {
	UIActivityIndicatorView* _activityIndicator;
	UILabel* _labelNoResults;
	UIButton* _buttonLoadMore;
	UIView* _overlayView;
	UIImageView* _bingAttribution;
	NSMutableArray* _imageURLs;
	NSMutableArray* _thumbnailViews;
	UIImageView* _highlightedImageView;
	int _searchOffset;
	int _resultsCount;
	UISearchBar* _searchBar;
	ImageListScrollView* _scrollView;
	NSString* _preloadedSearchText;
	id<ImageSearchControllerDelegate> _delegate;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) __weak id<ImageSearchControllerDelegate> delegate;
@property(retain, nonatomic) NSString* preloadedSearchText;
@property(retain, nonatomic) ImageListScrollView* scrollView;
@property(retain, nonatomic) UISearchBar* searchBar;
-(void).cxx_destruct;
-(void)processImageSearchResponseData:(id)data error:(id)error;
-(void)doSearch:(id)search;
-(void)searchBarTextDidEndEditing:(id)searchBarText;
-(void)searchBarTextDidBeginEditing:(id)searchBarText;
-(void)searchBar:(id)bar textDidChange:(id)text;
-(void)searchBarCancelButtonClicked:(id)clicked;
-(void)searchBarSearchButtonClicked:(id)clicked;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)viewDidLayoutSubviews;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)cancelAction:(id)action;
-(void)clearAction:(id)action;
-(void)loadMoreAction:(id)action;
-(void)updateLayoutForCurrentOrientation;
-(int)positionForBar:(id)bar;
-(void)addSearchResults:(id)results;
-(void)selectMediaAtIndex:(id)index;
-(void)resetSearchResults;
-(void)showActivity:(BOOL)activity;
-(void)hideOverlay;
-(void)showOverlay;
-(id)initWithDelegate:(id)delegate;
@end

