/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface ModuleInfo : NSObject {
	NSString* _name;
	NSString* _arch;
	unsigned _base;
}
@property(assign, nonatomic) unsigned base;
@property(retain, nonatomic) NSString* arch;
@property(retain, nonatomic) NSString* name;
+(id)loadedModules;
-(void).cxx_destruct;
@end

