/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WALinkLabelDelegate.h"
#import "WAStaticTableViewController.h"

@class WALinkLabel, UISwitch, UILabel, NSString, UIView, WATableRow, WATableSection;

__attribute__((visibility("hidden")))
@interface NotificationsViewController : WAStaticTableViewController <WALinkLabelDelegate> {
	UIView* _headerView;
	UILabel* _headerLabel;
	WATableSection* _sectionPersonal;
	WATableRow* _rowMessageSound;
	UISwitch* _switchMessageAlerts;
	WATableSection* _sectionGroup;
	WATableRow* _rowGroupSound;
	UISwitch* _switchGroupAlerts;
	WATableSection* _sectionCall;
	WATableRow* _rowCallSound;
	UISwitch* _switchCallAlerts;
	UISwitch* _switchPreview;
	WALinkLabel* _noPreviewLinkLabel;
	int _noPreviewSectionIndex;
	WATableRow* _rowInAppAlerts;
	WATableRow* _rowResetSettings;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)controller;
-(void).cxx_destruct;
-(void)handleOpenURL:(id)url fromLinkLabel:(id)linkLabel;
-(float)tableView:(id)view heightForFooterInSection:(int)section;
-(id)tableView:(id)view viewForFooterInSection:(int)section;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(void)wa_fontSizeDidChange;
-(void)wa_applicationWillEnterForeground;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)viewWillAppear:(BOOL)view;
-(void)setupTableView;
-(void)viewDidLoad;
-(void)showInAppNotificationSettings;
-(void)showPreviewAction:(id)action;
-(void)callAlertsAction:(id)action;
-(void)groupAlertsAction:(id)action;
-(void)messageAlertsAction:(id)action;
-(void)reloadData;
-(void)resetNotificationSettigs;
-(void)showSoundPickerController:(int)controller;
-(void)updateTableViewHeader;
-(void)dealloc;
-(id)init;
@end

