/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import <Foundation/NSString.h>


@interface NSString (QRCode)
-(id)wa_QRCodeImageOfSize:(CGSize)size;
@end

@interface NSString (Additions)
+(id)wa_stringWithData:(id)data encodingHint:(unsigned)hint actualEncoding:(unsigned*)encoding;
+(id)digraphs;
-(id)wa_stringBetweenStartString:(id)string endString:(id)string2;
-(id)wa_componentsOfURLStringForIndexing;
-(id)wa_bestWebURLReturningMatchedText:(id*)text;
-(id)wa_htmlUnescapedString;
-(BOOL)wa_isIPAddress;
-(id)wa_decodedStringFromBase64;
-(BOOL)wa_hasVideoFileExtension;
-(id)wa_whatsAppIDFromJID;
-(id)wa_jidFromIdOrJID;
-(id)wa_jidFromWhatsAppID;
-(id)localPhoneNumberFormattedUsingCountryCode:(id)code;
-(id)unformattedPhoneNumber;
-(id)unformattedPhoneNumberFromJID;
-(id)formattedPhoneNumberFromJID;
-(id)formattedPhoneNumber;
-(id)phoneNumberForVoiceOver;
-(id)wa_stringBySubstitutingURLs:(id)urls;
-(id)wa_splitIntoPartsWithMaxParts:(unsigned)maxParts maxCharactersPerPart:(unsigned)part overflowed:(BOOL*)overflowed;
-(unsigned)wa_indexOfClosestWordBoundaryBeforeIndex:(unsigned)closestWordBoundaryBeforeIndex;
-(unsigned)wa_indexOfComposedCharacterContainingIndex:(unsigned)composedCharacterContainingIndex;
-(id)wa_redactedURLString;
-(id)wa_redactedString;
-(id)wa_stringByReplacingGreaterThanSignWithImageUsingColor:(id)imageUsingColor andFont:(id)font;
-(id)wa_substringWithComposedCharacterSequenceLength:(unsigned)composedCharacterSequenceLength;
-(unsigned)wa_lengthInCharacters;
-(id)wa_bestStringLanguage;
-(BOOL)isRTLText;
-(BOOL)isEmptyOrWhitespace;
-(id)wa_suffixWithMaximumLength:(unsigned)maximumLength;
-(id)wa_trimmedStringByNormalizingNewlines;
-(id)wa_trimmedString;
-(id)wa_stringByRemovingEmoji;
-(id)wa_stringByStandardizingEmoji;
-(id)wa_stringByRemovingVariationSelector;
-(id)mimeType;
-(id)tokens;
-(id)upperBoundSearchString;
-(id)normalizedString;
-(id)wa_URLEncodedString;
-(id)wa_nullSanitizedString;
-(id)wa_stringWithInterspersedZeroLengthSpaces;
@end

@interface NSString (Crypto)
-(id)wa_URLEncodedHexToBinary;
-(id)wa_decodedStringWithSalt:(id)salt;
-(id)wa_encodedStringWithSalt:(id)salt;
-(id)wa_decodedString;
-(id)wa_encodedString;
-(id)wa_SHA256String;
-(id)wa_MD5String;
-(id)wa_dataValue;
@end

@interface NSString (RegExp)
-(id)stringByReplacingMatchesInString:(id)string withTemplate:(id)aTemplate;
-(NSRange)rangeOfFirstMatchInString:(id)string;
@end

@interface NSString (XMPPBinaryCoder)
-(BOOL)wa_isHex8Encodable;
-(BOOL)wa_isNibble8Encodable;
@end

@interface NSString (Attachments)
+(id)wa_allCountryCombinations;
-(BOOL)wa_containsCustomEmoji;
@end

@interface NSString (VCardAdditions)
-(id)vCardSafeString;
@end

