/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSURL.h>


@interface NSURL (WhatsApp)
-(id)wa_normalizedWebURL;
-(id)wa_URLByAddingParameter:(id)parameter value:(id)value;
-(id)wa_URLByReplacingHost:(id)host;
@end

