/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@interface OpenInChromeController : _ABAddressBookCopyArrayOfAllGroups
{
}

+ (id)sharedInstance;
- (BOOL)openInChrome:(id)fp8 withCallbackURL:(id)fp12 createNewTab:(BOOL)fp16;
- (BOOL)openInChrome:(id)fp8;
- (BOOL)isChromeInstalled;

@end

