/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAViewController.h"

@class NSString, NSTimer, UIButton, UIImageView, UILabel, UIProgressView, UITextField, UIView, WAOverlayView;

@interface PassInputViewController : WAViewController
{
    int _uiBlockState;
    UIImageView *_imageViewStop;
    UIImageView *_imageViewStop2;
    WAOverlayView *_overlayView;
    float _keyboardHeight;
    NSTimer *_blockTimer;
    NSTimer *_callButtonTimer;
    NSTimer *_editButtonTimer;
    BOOL _shouldShowActivityIndicator;
    BOOL _registerRequestInProgress;
    NSString *_learnMoreUrl;
    NSString *_verificationCodeFromUrl;
    BOOL _changePhoneNumberMode;
    id <PassInputViewControllerDelegate> _delegate;
    UIView *_viewContainer;
    UILabel *_labelHelperText1;
    UILabel *_labelHelperText2;
    UIView *_viewCodeInputFields;
    UITextField *_textFieldCode;
    UITextField *_textFieldCode2;
    UILabel *_labelCode;
    UILabel *_labelCode2;
    UIView *_viewRetryButtons;
    UIButton *_buttonResend;
    UIButton *_buttonCall;
    UIView *_viewUIBlocked;
    UILabel *_labelUIBlocked;
    UIProgressView *_progressViewBlock;
}

- (void)setProgressViewBlock:(id)fp8;
- (id)progressViewBlock;
- (void)setLabelUIBlocked:(id)fp8;
- (id)labelUIBlocked;
- (void)setViewUIBlocked:(id)fp8;
- (id)viewUIBlocked;
- (void)setButtonCall:(id)fp8;
- (id)buttonCall;
- (void)setButtonResend:(id)fp8;
- (id)buttonResend;
- (void)setViewRetryButtons:(id)fp8;
- (id)viewRetryButtons;
- (void)setLabelCode2:(id)fp8;
- (id)labelCode2;
- (void)setLabelCode:(id)fp8;
- (id)labelCode;
- (void)setTextFieldCode2:(id)fp8;
- (id)textFieldCode2;
- (void)setTextFieldCode:(id)fp8;
- (id)textFieldCode;
- (void)setViewCodeInputFields:(id)fp8;
- (id)viewCodeInputFields;
- (void)setLabelHelperText2:(id)fp8;
- (id)labelHelperText2;
- (void)setLabelHelperText1:(id)fp8;
- (id)labelHelperText1;
- (void)setViewContainer:(id)fp8;
- (id)viewContainer;
- (void)setChangePhoneNumberMode:(BOOL)fp8;
- (BOOL)changePhoneNumberMode;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)codeValidationFailedWithError:(id)fp8;
- (void)codeValidatedWithResult:(id)fp8;
- (void)codeOrCallRequestFailedWithError:(id)fp8;
- (void)callRequestFinishedWithResult:(id)fp8;
- (void)codeRequestFinishedWithResult:(id)fp8;
- (void)setVerificationCodeFromUrl:(id)fp8;
- (void)launchedFromUrl:(id)fp8;
- (void)enterVerificationCodeFromUrl:(id)fp8;
- (void)cancelAction:(id)fp8;
- (void)callMeAction:(id)fp8;
- (void)resendCodeAction:(id)fp8;
- (void)codeEditedAction:(id)fp8;
- (BOOL)textFieldShouldBeginEditing:(id)fp8;
- (BOOL)textField:(id)fp8 shouldChangeCharactersInRange:(struct _NSRange)fp12 replacementString:(id)fp20;
- (int)halfCodeLength;
- (void)wa_applicationDidBecomeActive;
- (void)wa_tintColorDidChange;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)touchCatcherButtonTapped;
- (void)viewDidLoad;
- (void)requestSMSWithCode;
- (void)keyboardWillShow:(id)fp8;
- (void)activateCodeInputFieldIfPossible;
- (void)formatCodePresentation;
- (void)finishController;
- (void)setHeaderLabelText:(BOOL)fp8;
- (void)showAndReleaseLearnMoreAlert:(id)fp8 message:(id)fp12 url:(id)fp16;
- (void)showAndReleaseAppStoreAlert:(id)fp8;
- (void)showAndReleaseUnspecifiedErrorAlert;
- (void)showAndReleaseGenericAlert:(id)fp8;
- (void)showAndReleaseContactSupportAlert:(id)fp8 withContext:(id)fp12;
- (void)showAndReleaseCodeEntryFailedAlertWithTitle:(id)fp8 message:(id)fp12;
- (void)resetCodeInput;
- (void)checkEditAvailability:(id)fp8;
- (void)updateBlockState:(id)fp8;
- (void)checkPasscodeAttempts;
- (void)adjustHelperTextFont;
- (void)retryWithSavedPasscodeIfNeeded;
- (void)setUIBlockState:(int)fp8;
- (BOOL)blockStateIsBlocked;
- (void)startBlockTimer;
- (void)resizeHelperTextLabels;
- (void)layoutAllViews;
- (void)layoutUIBlockedView;
- (void)layoutRetryButtonsAnimated:(BOOL)fp8;
- (void)updateCallButtonTitle:(id)fp8;
- (void)enableCallButtonTimer:(BOOL)fp8;
- (void)hideOverlayWithCompletion:(id)fp(null) setViewTitle:(void)fp8;
- (void)showOverlay:(id)fp8;
- (id)authCode;
- (void)dealloc;
- (id)init;

@end

