/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAViewController.h"

@class UIButton, UIImageView, UILabel;

@interface PaymentEduViewController : WAViewController
{
    UIImageView *_imageViewWallpaper;
    struct UIEdgeInsets _greetingTextInsets;
    struct UIEdgeInsets _priceTextInsets;
    UIImageView *_imageServiceInfo;
    UILabel *_labelGreetingTop;
    UILabel *_labelGreetingBottom;
    UIButton *_blogPostButton;
    UIButton *_buttonContinue;
    UIButton *_buttonPayNow;
    UIButton *_buttonPayLater;
    id <PaymentEduControllerDelegate> _delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)blogPostButtonClicked:(id)fp8;
- (void)viewDidLayoutSubviews;
- (void)loadView;
- (void)payLaterAction:(id)fp8;
- (void)payNowAction:(id)fp8;
- (void)continueAction:(id)fp8;
- (void)layoutSubviews;
- (void)reloadServiceInfo;
- (id)initWithDelegate:(id)fp8;

@end

