/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol ProblemInputControllerDelegate <NSObject>
-(void)problemInputControllerDidCancel:(id)problemInputController;
-(void)problemInputController:(id)controller didFinishWithText:(id)text logsAttachment:(id)attachment imageAttachments:(id)attachments;
@end

