/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WATableViewController.h"

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"
#import "WAFAQBrowserViewControllerDelegate-Protocol.h"
#import "WAImageAttachmentContainerViewDelegate-Protocol.h"

@class NSArray, NSObject<OS_dispatch_group>, NSString, UIBarButtonItem, UITableViewCell, UITextView, WADoneWithSpinnerBarButtonItem, WAHTTPFetcher, WAImageAttachmentContainerView;

@interface ProblemInputController : WATableViewController <WAImageAttachmentContainerViewDelegate, UINavigationControllerDelegate, UIImagePickerControllerDelegate, UIGestureRecognizerDelegate, WAFAQBrowserViewControllerDelegate, UITextViewDelegate>
{
    UITableViewCell *_textViewCell;
    UITextView *_textView;
    WADoneWithSpinnerBarButtonItem *_doneButton;
    NSObject<OS_dispatch_group> *_logsGatheringDispatchGroup;
    NSString *_gzippedLogs;
    float _keyboardHeight;
    WAImageAttachmentContainerView *_imageAttachmentContainer;
    UIBarButtonItem *_dismissKeyboardBarButtonItem;
    UIBarButtonItem *_cancelBarButtonItem;
    BOOL _keyboardHidden;
    WAHTTPFetcher *_searchFetcher;
    NSArray *_imagesToSend;
    id <ProblemInputControllerDelegate> _delegate;
    NSString *_initialText;
    unsigned int _numberOfFAQSearchResultsReturned;
    unsigned int _numberOfFAQSearchResultsOpened;
}

- (unsigned int)numberOfFAQSearchResultsOpened;
- (unsigned int)numberOfFAQSearchResultsReturned;
- (void)setInitialText:(id)fp8;
- (id)initialText;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)faqBrowserViewControllerShouldProceedToEmail:(id)fp8;
- (void)cancelPendingSearch;
- (void)searchFAQ:(id)fp8 checkpoint:(id)fp(null) completion:(void)fp12;
- (void)imagePickerController:(id)fp8 didFinishPickingMediaWithInfo:(id)fp12;
- (void)imagePickerControllerDidCancel:(id)fp8;
- (void)imageAttachmentContainerViewDidDeleteImage:(id)fp8;
- (void)imageAttachmentContainerViewDidRequestAddImage:(id)fp8;
- (void)dismissKeyboard:(id)fp8;
- (void)keyboardWillHide:(id)fp8;
- (void)keyboardWillShow:(id)fp8;
- (void)textViewDidChange:(id)fp8;
- (void)textViewDidBeginEditing:(id)fp8;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 willSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForHeaderInSection:(int)fp12;
- (id)tableView:(id)fp8 titleForFooterInSection:(int)fp12;
- (id)tableView:(id)fp8 titleForHeaderInSection:(int)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)viewTapped:(id)fp8;
- (BOOL)gestureRecognizer:(id)fp8 shouldReceiveTouch:(id)fp12;
- (BOOL)gestureRecognizer:(id)fp8 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)fp12;
- (void)wa_applicationDidEnterBackground;
- (void)wa_fontSizeDidChange;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (void)cancelAction:(id)fp8;
- (void)proceedToEmail;
- (void)doneAction:(id)fp8;
- (void)updateButtonState;
- (BOOL)userHasEnteredSufficientText;
- (void)dealloc;
- (id)initWithStyle:(int)fp8;
- (id)init;

@end

