/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WAImageToImageTransitioning.h"
#import "UITextFieldDelegate.h"
#import "WAViewController.h"
#import "WASinglePhotoPickerControllerDelegate.h"
#import "WhatsApp-Structs.h"
#import "WANavigationControllerPopToAnimating.h"

@class UITableView, UILabel, UIActivityIndicatorView, NSLayoutConstraint, NSString, ACAccountStore, WAProgressHUD, UIImageView, UIImage, GroupIconViewController, WAProfileTableViewCell, UITextField, UIView, UIButton, UITableViewCell;
@protocol ProfileViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface ProfileViewController : WAViewController <WASinglePhotoPickerControllerDelegate, UITextFieldDelegate, WAImageToImageTransitioning, WANavigationControllerPopToAnimating> {
	UIImage* _tempProfilePicture;
	UIActivityIndicatorView* _aiGroupIcon;
	WAProgressHUD* _progressHUD;
	int _networkActivities;
	BOOL _modal;
	BOOL _photoModified;
	GroupIconViewController* _groupIconViewController;
	ACAccountStore* _accountStore;
	UIEdgeInsets _originalContentInset;
	float _keyboardHeight;
	UITableViewCell* _editStatusCell;
	UITableViewCell* _phoneNumberCell;
	BOOL _useDeviceName;
	id<ProfileViewControllerDelegate> _delegate;
	UITableView* _tableViewProfile;
	UIView* _viewTableHeader;
	UILabel* _labelHelperText;
	UIView* _viewProfilePhoto;
	NSLayoutConstraint* _profilePhotoHeightConstraint;
	NSLayoutConstraint* _labelHelperHeightConstraint;
	UIImageView* _imageProfilePhoto;
	UIButton* _buttonAddPhoto;
	UIButton* _buttonEditPhoto;
	WAProfileTableViewCell* _cellPushName;
	UITextField* _textFieldName;
	UILabel* _labelCharCount;
	UIView* _viewFacebookTitle;
	UILabel* _labelFacebookTitle;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) UILabel* labelFacebookTitle;
@property(retain, nonatomic) UIView* viewFacebookTitle;
@property(retain, nonatomic) UILabel* labelCharCount;
@property(retain, nonatomic) UITextField* textFieldName;
@property(retain, nonatomic) WAProfileTableViewCell* cellPushName;
@property(retain, nonatomic) UIButton* buttonEditPhoto;
@property(retain, nonatomic) UIButton* buttonAddPhoto;
@property(retain, nonatomic) UIImageView* imageProfilePhoto;
@property(retain, nonatomic) NSLayoutConstraint* labelHelperHeightConstraint;
@property(retain, nonatomic) NSLayoutConstraint* profilePhotoHeightConstraint;
@property(retain, nonatomic) UIView* viewProfilePhoto;
@property(retain, nonatomic) UILabel* labelHelperText;
@property(retain, nonatomic) UIView* viewTableHeader;
@property(retain, nonatomic) UITableView* tableViewProfile;
@property(assign, nonatomic) __weak id<ProfileViewControllerDelegate> delegate;
@property(assign, nonatomic) BOOL useDeviceName;
-(void).cxx_destruct;
-(void)keyboardDidHide:(id)keyboard;
-(void)keyboardWillHide:(id)keyboard;
-(void)keyboardDidShow:(id)keyboard;
-(void)keyboardWillShow:(id)keyboard;
-(void)adjustContentInsetForKeyboardHeight:(float)keyboardHeight;
-(void)textFieldDidEndEditing:(id)textField;
-(BOOL)textFieldShouldEndEditing:(id)textField;
-(void)textFieldDidBeginEditing:(id)textField;
-(BOOL)textFieldShouldReturn:(id)textField;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(void)singlePhotoPickerControllerDidCancel:(id)singlePhotoPickerController;
-(void)singlePhotoPickerController:(id)controller didFinishWithImage:(id)image;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view willSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view viewForHeaderInSection:(int)section;
-(float)tableView:(id)view heightForFooterInSection:(int)section;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)wa_applicationDidBecomeActive;
-(void)wa_fontSizeDidChange;
-(void)wa_tintColorDidChange;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)viewDidLayoutSubviews;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)chatManagerDidUpdateStatus:(id)chatManager;
-(void)updateStatusCell;
-(void)editStatus;
-(BOOL)shouldBeginCustomPopAnimationForAnimationIdentifier:(id)animationIdentifier;
-(id)popAnimationControllerFromViewController:(id)viewController;
-(id)popAnimationInteractionControllerFromViewController:(id)viewController;
-(void)finishTransitionWithView:(id)view context:(id)context;
-(id)viewForTransitionAnimationWithContext:(id)context;
-(void)prepareForTransitionWithContext:(id)context;
-(BOOL)shouldUseImageToImageTransitionForOperation:(int)operation fromViewController:(id)viewController toViewController:(id)viewController3 context:(id)context;
-(void)layoutTableHeader;
-(void)constrainTableHeader;
-(void)deleteProfilePhoto;
-(void)reallyShowImagePickerForSourceType:(int)sourceType;
-(void)showImagePickerForSourceType:(int)sourceType;
-(void)showProfilePhotoActivity:(BOOL)activity;
-(void)reloadProfilePicture;
-(void)profilePictureUpdated:(id)updated;
-(void)requestFBAccess;
-(void)renewCredentialsForAccount:(id)account;
-(void)importUsernameFromFBAccount:(id)fbaccount accountRenewed:(BOOL)renewed;
-(void)importProfilePhotoFromFBAccount:(id)fbaccount;
-(void)processFBPicture:(id)picture;
-(void)processFBAccountInfo:(id)info;
-(void)checkFacebookImportCompletion;
-(void)showOtherFacebookImportErrorAlert:(id)alert;
-(void)showFacebookAccessNotAllowedErrorAlert;
-(void)showFacebookNotConfiguredErrorAlert;
-(void)showStaleFacebookPasswordErrorAlert;
-(void)cancelAction:(id)action;
-(void)doneAction:(id)action;
-(void)textFieldValueChanged:(id)changed;
-(void)editPhotoAction:(id)action;
-(void)removeHUD;
-(void)showHUD:(id)hud;
-(void)layoutFBHelperText;
-(void)checkProfilePictureActivity:(id)activity;
-(void)updateTextFieldValues;
-(void)validateUserInput;
-(void)updateUI;
-(void)updateCharCount;
-(void)dealloc;
-(id)initWithProfileContollerDelegate:(id)profileContollerDelegate;
@end

