/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class UIImageView, NSTimer, UILabel;

__attribute__((visibility("hidden")))
@interface PropertyTableViewCell : UITableViewCell {
	UILabel* _labelLabel;
	UILabel* _labelValue;
	UILabel* _labelComment;
	UIImageView* _imageViewStar;
	BOOL _isFavorite;
	BOOL _valueHighlighted;
	BOOL _popupActive;
	NSTimer* _popupTimer;
}
@property(readonly, assign, nonatomic) BOOL popupActive;
@property(assign, nonatomic) BOOL valueHighlighted;
@property(assign, nonatomic) BOOL isFavorite;
@property(readonly, assign, nonatomic) UILabel* labelComment;
@property(readonly, assign, nonatomic) UILabel* labelValue;
@property(readonly, assign, nonatomic) UILabel* labelLabel;
+(float)heightForText:(id)text withFont:(id)font hasComment:(BOOL)comment hasStar:(BOOL)star cellWidth:(float)width;
+(id)commentFont;
+(id)valueFont;
+(id)labelFont;
+(id)commentTextColorSelected;
+(id)commentTextColorNormal;
+(id)valueTextColorHighlighted;
+(id)valueTextColorSelected;
+(id)valueTextColorNormal;
+(id)labelTextColorSelected;
+(id)labelTextColorNormal;
-(void).cxx_destruct;
-(void)didHideMenu;
-(void)showCopyPasteView:(id)view;
-(void)copy:(id)copy;
-(BOOL)canPerformAction:(SEL)action withSender:(id)sender;
-(BOOL)canBecomeFirstResponder;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)setHighlighted:(BOOL)highlighted animated:(BOOL)animated;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(void)layoutSubviews;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

