/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import </libobjc.A.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface SSZipArchive : NSObject {
	NSString* _path;
	NSString* _filename;
	void* _zip;
}
+(id)_dateWithMSDOSFormat:(unsigned long)msdosformat;
+(BOOL)createZipFileAtPath:(id)path withContentsOfDirectory:(id)directory keepParentDirectory:(BOOL)directory3;
+(BOOL)createZipFileAtPath:(id)path withContentsOfDirectory:(id)directory;
+(BOOL)createZipFileAtPath:(id)path withFilesAtPaths:(id)paths;
+(BOOL)unzipFileAtPath:(id)path toDestination:(id)destination overwrite:(BOOL)overwrite password:(id)password error:(id*)error delegate:(id)delegate progressHandler:(id)handler completionHandler:(id)handler8;
+(BOOL)unzipFileAtPath:(id)path toDestination:(id)destination progressHandler:(id)handler completionHandler:(id)handler4;
+(BOOL)unzipFileAtPath:(id)path toDestination:(id)destination overwrite:(BOOL)overwrite password:(id)password progressHandler:(id)handler completionHandler:(id)handler6;
+(BOOL)unzipFileAtPath:(id)path toDestination:(id)destination overwrite:(BOOL)overwrite password:(id)password error:(id*)error delegate:(id)delegate;
+(BOOL)unzipFileAtPath:(id)path toDestination:(id)destination delegate:(id)delegate;
+(BOOL)unzipFileAtPath:(id)path toDestination:(id)destination overwrite:(BOOL)overwrite password:(id)password error:(id*)error;
+(BOOL)unzipFileAtPath:(id)path toDestination:(id)destination;
-(void).cxx_destruct;
-(BOOL)close;
-(BOOL)writeData:(id)data filename:(id)filename;
-(BOOL)writeFileAtPath:(id)path withFileName:(id)fileName;
-(BOOL)writeFile:(id)file;
-(BOOL)writeFolderAtPath:(id)path withFolderName:(id)folderName;
-(void)zipInfo:(XXStruct_z_NMMB*)info setDate:(id)date;
-(BOOL)open;
-(id)initWithPath:(id)path;
@end

