/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSDate;

__attribute__((visibility("hidden")))
@interface Stat : NSObject {
	int _messagesSent;
	int _messagesReceived;
	int _callsSent;
	int _callsReceived;
	NSDate* _lastReset;
	long long _mediaBytesSent;
	long long _mediaBytesReceived;
	long long _systemBytesSent;
	long long _systemBytesReceived;
	long long _callBytesSent;
	long long _callBytesReceived;
}
@property(readonly, assign, nonatomic) NSDate* lastReset;
@property(assign, nonatomic) long long callBytesReceived;
@property(assign, nonatomic) long long callBytesSent;
@property(assign, nonatomic) int callsReceived;
@property(assign, nonatomic) int callsSent;
@property(assign, nonatomic) int messagesReceived;
@property(assign, nonatomic) int messagesSent;
@property(assign, nonatomic) long long systemBytesReceived;
@property(assign, nonatomic) long long systemBytesSent;
@property(assign, nonatomic) long long mediaBytesReceived;
@property(assign, nonatomic) long long mediaBytesSent;
+(void)optionallyLoadInteger:(int*)integer fromObject:(id)object;
+(void)optionallyLoadLongLong:(long long*)aLong fromObject:(id)object;
+(id)keysForBackup;
+(id)sharedManager;
+(void)didLoadUserDefaults:(id)defaults;
+(void)willSaveUserDefaults:(id)defaults;
+(void)registerForBackup;
-(void).cxx_destruct;
-(void)restoreFromDictionaryRepresentation:(id)dictionaryRepresentation;
-(void)checkForUpgrade;
-(void)reset:(BOOL)reset;
-(void)save;
-(void)load;
-(id)init;
@end

