/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@interface TimePeriodFormatter : _ABAddressBookCopyArrayOfAllGroups
{
}

+ (id)formatWithAppropriateTimeUnit:(long)fp8;
+ (id)pluralYears:(int)fp8;
+ (id)pluralMonths:(int)fp8;
+ (id)pluralDays:(int)fp8;
+ (id)pluralHours:(int)fp8;
+ (id)pluralMinutes:(int)fp8;
+ (id)pluralSeconds:(int)fp8;
- (id)stringFromTimeInterval:(double)fp8;

@end

