/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol UIDocumentPickerDelegate <NSObject>
-(void)documentPicker:(id)picker didPickDocumentAtURL:(id)url;
@optional
-(void)documentPickerWasCancelled:(id)cancelled;
@end

