/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CLLocationManagerDelegate.h"
#import "MKMapViewDelegate.h"
#import "WhatsApp-Structs.h"
#import "WAViewController.h"

@class UILabel, CLLocationManager, NSString, UIImageView, UIToolbar, MKMapView, CLGeocoder, CLLocation, UIBarButtonItem, WAMapTypeSegmentedControl, NSMutableArray, WAConversationHeaderView;
@protocol WALocationDataSource;

__attribute__((visibility("hidden")))
@interface UserLocationViewController : WAViewController <MKMapViewDelegate, CLLocationManagerDelegate> {
	WAMapTypeSegmentedControl* _segmentedControl;
	UIBarButtonItem* _barButtonSearch;
	UIBarButtonItem* _barButtonAction;
	UIBarButtonItem* _segmentedControlBarItem;
	UIImageView* _noMediaImage;
	UILabel* _noMediaLabelTitle;
	UILabel* _noMediaLabelText;
	WAConversationHeaderView* _headerView;
	int _lastKnownInterfaceOrientation;
	CLGeocoder* _geocoder;
	CLLocationManager* _locationManager;
	CLLocation* _currentLocation;
	NSMutableArray* _annotations;
	unsigned _regionType;
	int _locationIndex;
	double _zoomLevel;
	BOOL _showMyLocation;
	BOOL _singleLocation;
	BOOL _showMapTypeSelector;
	BOOL _locationAuthorized;
	MKMapView* _mapViewMain;
	UIToolbar* _toolbar;
	id<WALocationDataSource> _dataSource;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) __weak id<WALocationDataSource> dataSource;
@property(retain, nonatomic) UIToolbar* toolbar;
@property(retain, nonatomic) MKMapView* mapViewMain;
@property(assign, nonatomic) BOOL locationAuthorized;
@property(assign, nonatomic) BOOL showMapTypeSelector;
@property(assign, nonatomic) BOOL singleLocation;
@property(assign, nonatomic) BOOL showMyLocation;
-(void).cxx_destruct;
-(id)previewActionItems;
-(void)locationManager:(id)manager didFailWithError:(id)error;
-(void)locationManager:(id)manager didUpdateToLocation:(id)location fromLocation:(id)location3;
-(void)locationManager:(id)manager didChangeAuthorizationStatus:(int)status;
-(void)processLocationError:(id)error;
-(void)updateLocationDataWithCoordinate:(XXStruct_gLbvpC)coordinate withPlacemark:(id)placemark;
-(void)displayExpectedTravelTime:(double)time forAnnotation:(id)annotation;
-(void)calculateExpectedTravelTimeForAnnotation:(id)annotation;
-(void)mapView:(id)view regionDidChangeAnimated:(BOOL)region;
-(void)mapView:(id)view didAddAnnotationViews:(id)views;
-(id)mapView:(id)view viewForAnnotation:(id)annotation;
-(void)mapView:(id)view annotationView:(id)view2 calloutAccessoryControlTapped:(id)tapped;
-(void)directionsToHere;
-(void)searchAction:(id)action;
-(void)mapAction:(id)action;
-(void)mapTypeChanged:(id)changed;
-(void)showPlaceInfoAction:(id)action;
-(void)updateAnnotationsWithCurrentLocation;
-(void)reloadAnnotations;
-(id)findFirstGroupingWithAnnotations:(id)annotations;
-(void)layoutNoLocationsView;
-(void)setupToolbar;
-(void)updateMapRegionAnimated:(BOOL)animated;
-(void)updateHeaderViewToCurrentInterfaceOrientation;
-(void)updateNavBar;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)viewDidLayoutSubviews;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(id)initWithLocationDataSource:(id)locationDataSource;
@end

