/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSLock, NSOperationQueue, NSMutableDictionary, WAWaitOperation, NSPort, NSString, WAFinishOperation;

__attribute__((visibility("hidden")))
@interface WAActionManager : NSObject {
	NSOperationQueue* _queue;
	unsigned _options;
	int _canceling;
	int _finishing;
	NSPort* _mainThreadWaitPort;
	NSMutableDictionary* _phaseOperations;
	NSLock* _updatePhaseLock;
	unsigned _latestPhase;
	WAWaitOperation* _wait;
	WAFinishOperation* _finish;
	unsigned _phase;
	id _completion;
}
@property(readonly, assign, nonatomic) unsigned maximumPhase;
@property(readonly, assign, nonatomic) NSString* errorDomain;
@property(readonly, assign) BOOL canceled;
@property(copy, nonatomic) id completion;
@property(readonly, assign, nonatomic) float progress;
@property(readonly, assign, nonatomic) unsigned phase;
-(void).cxx_destruct;
-(float)progressForOperations:(id)operations;
-(void)setOperations:(id)operations forPhase:(unsigned)phase;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(void)incrementPhase;
-(void)setPhase:(unsigned)phase;
-(void)manuallyUpdatePhaseTo:(unsigned)to;
-(void)updatePhase;
-(void)runBlockOnMainThread:(id)thread waitUntilDone:(BOOL)done;
-(void)runBlock:(id)block;
-(void)waitForCompletion;
-(void)runMainThreadRunLoop;
-(BOOL)shouldFinish;
-(BOOL)shouldCancel;
-(void)cancelWithReason:(unsigned)reason;
-(void)finish;
-(id)errorForCode:(unsigned)code;
-(void)completeWithReason:(unsigned)reason;
-(void)addOperations:(id)operations;
-(void)addOperation:(id)operation;
-(void)start;
-(BOOL)checkOption:(unsigned)option;
-(void)dealloc;
-(id)initWithOptions:(unsigned)options;
-(id)init;
@end

