/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WATableViewController.h"

@class NSArray, NSDictionary;

@interface WAAddressBookCountryPicker : WATableViewController
{
    NSArray *_sectionTitles;
    NSDictionary *_countryMap;
    id <WAAddressBookCountryPickerDelegate> _delegate;
}

+ (id)pickerWithDelegate:(id)fp8;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 titleForHeaderInSection:(int)fp12;
- (int)tableView:(id)fp8 sectionForSectionIndexTitle:(id)fp12 atIndex:(int)fp16;
- (id)sectionIndexTitlesForTableView:(id)fp8;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (id)countryInfoForTableIndexPath:(id)fp8;
- (void)wa_fontSizeDidChange;
- (void)cancelAction:(id)fp8;
- (void)viewDidLoad;
- (id)initWithStyle:(int)fp8;

@end

