/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


__attribute__((visibility("hidden")))
@interface WAAddressBookUtilities : NSObject {
}
+(id)localizedNameOfSocialService:(id)socialService;
+(id)localizedNameOfIMService:(id)imservice;
+(id)localizedAddressBookLabel:(id)label;
+(id)predefinedLabelsForABPropertyID:(int)abpropertyID;
+(id)predefinedSocialServices;
+(id)predefinedIMServices;
+(id)predefinedDateLabels;
+(id)predefinedAddressLabels;
+(id)predefinedURLLabels;
+(id)predefinedEmailLabels;
+(id)predefinedPhoneLabels;
@end

