/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class NSArray, NSMutableArray, NSString;

@interface WAAggregateCallEvent : _ABAddressBookCopyArrayOfAllGroups
{
    NSMutableArray *_events;
    NSString *_numberStringForSearch;
    NSArray *_tokensForSearch;
    BOOL _useSubstringMatchingForSearch;
}

- (BOOL)useSubstringMatchingForSearch;
- (id)events;
- (void).cxx_destruct;
- (BOOL)mergeEventIfPossible:(id)fp8;
- (BOOL)showCallIcon;
- (BOOL)matchesSearchQuery:(id)fp8 words:(id)fp12;
- (id)tokensForSearch;
- (id)numberStringForSearch;
- (void)invalidateSearchInfo;
- (id)initWithEvent:(id)fp8;

@end

