/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UILabel.h>

@class NSString, NSTimer;

__attribute__((visibility("hidden")))
@interface WAAlternatingLabel : UILabel {
	NSTimer* _timer;
	int _index;
	NSString* _primaryText;
	NSString* _secondaryText;
	double _interval;
}
@property(assign, nonatomic) double interval;
@property(assign, nonatomic, getter=isAnimating) BOOL animating;
@property(copy, nonatomic) NSString* secondaryText;
@property(copy, nonatomic) NSString* primaryText;
-(void).cxx_destruct;
-(void)switchLabel:(id)label;
@end

