/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class UIImageView;

@interface WAAnimatedGearsView : _ABAddressBookCopyArrayOfAllGroups
{
    UIImageView *_gearsBase;
    UIImageView *_border;
    UIImageView *_spinner;
    BOOL _animating;
}

+ (struct CGSize)baseSize;
- (BOOL)isAnimating;
- (void).cxx_destruct;
- (void)stopAnimating;
- (void)startAnimating;
- (void)layoutSubviews;
- (void)setFrame:(struct CGRect)fp8;
- (void)configure;
- (void)initialize;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)fp8;

@end

