/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

#import "UICollectionViewDataSource-Protocol.h"

@class ALAssetsGroup, NSArray, PHAssetCollection, PHFetchResult;

@interface WAAssetCollection : _ABAddressBookCopyArrayOfAllGroups <UICollectionViewDataSource>
{
    unsigned int _mediaTypes;
    PHAssetCollection *_assetCollection;
    PHFetchResult *_fetchResult;
    ALAssetsGroup *_assetsGroup;
    BOOL _useReverseOrderForCollectionView;
    NSArray *_assets;
}

+ (id)sortedAssetCollectionsWithCollections:(id)fp8;
+ (void)fetchAllCollectionsForMediaTypes:(unsigned int)fp8 completion:(id)fp(null);
+ (void)fetchAllAssetsFromAssetsGroup:(id)fp8 completion:(id)fp(null);
- (void)setUseReverseOrderForCollectionView:(BOOL)fp8;
- (BOOL)useReverseOrderForCollectionView;
- (id)assets;
- (void).cxx_destruct;
- (int)indexOfCollectionViewMediaPickerAsset:(id)fp8;
- (id)collectionViewMediaPickerAssetAtIndex:(int)fp8;
- (id)collectionView:(id)fp8 cellForItemAtIndexPath:(id)fp12;
- (int)collectionView:(id)fp8 numberOfItemsInSection:(int)fp12;
- (int)numberOfVideos;
- (int)numberOfPhotos;
- (BOOL)canQueryCountOfMediaType;
- (void)storeCountOfVideosInCameraRoll:(int)fp8;
- (void)storeCountOfPhotosInCameraRoll:(int)fp8;
- (void)stopCachingThumbnailsOfPixelSize:(struct CGSize)fp8 inRange:(struct _NSRange)fp16;
- (void)startCachingThumbnailsOfPixelSize:(struct CGSize)fp8 inRange:(struct _NSRange)fp16;
- (BOOL)updateWithChangeInstance:(id)fp8;
- (id)phAssetAtIndex:(unsigned int)fp8;
- (void)fetchAssetsFromPhotosFrameworkWithCompletionHandler:(id)fp(null);
- (void)fetchAssetsFromAssetsLibraryWithCompletionHandler:(id)fp(null);
- (void)fetchAssetsWithCompletionHandler:(id)fp(null);
- (void)refreshWithCompletionHandler:(id)fp(null);
- (id)posterImage;
- (id)localIdentifier;
- (unsigned int)assetCount;
- (unsigned int)estimatedAssetCount;
- (id)localizedTitle;
- (id)allAssetCollectionsFromMoments:(id)fp8;
- (id)fetchResultsForAssetsWithMediaTypes:(unsigned int)fp8 inCollection:(id)fp12;
- (id)fetchResult;
- (id)initWithAssetsGroup:(id)fp8 mediaTypes:(unsigned int)fp12;
- (id)initWithAssetCollection:(id)fp8 mediaTypes:(unsigned int)fp12;

@end

