/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAMessageCell.h"

@class NSString, NSTimer, UIButton, UIImageView, UILabel, UIProgressView, UISlider, UITapGestureRecognizer;

@interface WAAudioMessageCell : WAMessageCell
{
    UIButton *_buttonPlayPauseDownload;
    BOOL _playerWasPlaying;
    UISlider *_playerScrubber;
    UITapGestureRecognizer *_voiceOverSingleTapGesture;
    UIProgressView *_progressView;
    UISlider *_uploadScrubber;
    NSTimer *_uploadProgressUpdateTimer;
    int _uploadProgressPosition;
    UIImageView *_micIndicator;
    UIImageView *_mediaThumbnail;
    UILabel *_labelAudioDuration;
    UIImageView *_broadcastImageView;
    BOOL _allowVoiceOverAnnouncement;
    BOOL _uploadOrDownloadInProgress;
    BOOL _announceUploadOrDownloadCompletion;
    NSString *_voiceOverPositionText;
    BOOL _allowVoiceOverAction;
    int _audioDuration;
    float _scrubberSkipValue;
}

+ (float)maximumBubbleWidthForCellWidth:(float)fp8;
+ (struct CGSize)contentSizeForCellData:(id)fp8 maxWidth:(float)fp12;
+ (id)cellReuseIdentifier;
+ (void)initialize;
- (void).cxx_destruct;
- (void)updateControlsForCurrentVoiceOverStatus;
- (void)handleSingleTapVoiceOverOnly:(id)fp8;
- (void)voiceOverStatusChanged:(id)fp8;
- (void)accessibilityDecrement;
- (void)accessibilityIncrement;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityPositionString;
- (id)accessibilityHintText;
- (id)accessibilityValue;
- (id)accessibilityLabel;
- (void)playerScrubberDraggingEnded:(id)fp8;
- (void)playerScrubberDraggingStarted:(id)fp8;
- (void)playOrPauseAudio:(id)fp8;
- (void)startDownloadingAudio:(id)fp8;
- (void)cancelUploadOrDownload:(id)fp8;
- (void)uploadProgressUpdate:(id)fp8;
- (void)updatePlayedIndication;
- (void)updateDurationLabel;
- (void)updatePushToTalkControls;
- (void)layoutSubviews;
- (void)setBubbleHighlighted:(BOOL)fp8 animated:(BOOL)fp12;
- (void)setProgress:(float)fp8;
- (void)configureCellWithAnimation:(BOOL)fp8;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)setCellData:(id)fp8 delegate:(id)fp12;
- (void)dealloc;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;

@end

