/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import <UIKit/UIImageView.h>


__attribute__((visibility("hidden")))
@interface WAAutoCropImageView : UIImageView {
	float _cropInset;
	CGPoint _focusPoint;
}
@property(readonly, assign, nonatomic) CGRect contentsRect;
@property(assign, nonatomic) float cropInset;
@property(assign, nonatomic) CGPoint focusPoint;
-(void)updateContentsRect;
-(id)actionForLayer:(id)layer forKey:(id)key;
-(void)setFrame:(CGRect)frame;
-(void)setBounds:(CGRect)bounds;
-(void)setImage:(id)image;
-(id)initWithFrame:(CGRect)frame;
@end

