/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIActionSheet.h>

@class UIImage;

__attribute__((visibility("hidden")))
@interface WAAudioRouteActionSheet : UIActionSheet {
	UIImage* _selectedButtonGlyphImage;
}
@property(retain, nonatomic) UIImage* selectedButtonGlyphImage;
+(id)iconImageViewInButton:(id)button;
+(id)showInViewIfPossible:(id)viewIfPossible;
-(void).cxx_destruct;
-(id)_availableRoutes;
-(id)buttonAtIndex:(int)index;
-(id)initWithType:(unsigned)type;
@end

