/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WATableViewController.h"

@class NSIndexPath, UILabel, NSString, UIView, WAAutoBackupSettings;

__attribute__((visibility("hidden")))
@interface WAAutobackupSettingsViewController : WATableViewController {
	NSIndexPath* _selectedIndexPath;
	float _sideTextMargin;
	WAAutoBackupSettings* _autoBackupSettings;
	UIView* _viewFooter;
	float _cachedWidthFooter;
	UILabel* _labelFooter;
}
@property(retain, nonatomic) UILabel* labelFooter;
@property(assign, nonatomic) float cachedWidthFooter;
@property(retain, nonatomic) UIView* viewFooter;
@property(retain, nonatomic) WAAutoBackupSettings* autoBackupSettings;
@property(readonly, assign, nonatomic) NSString* bottomText;
@property(readonly, assign, nonatomic) float sideTextMargin;
@property(retain, nonatomic) NSIndexPath* selectedIndexPath;
+(id)stringForSequence:(id)sequence;
+(unsigned)autoBackupFrequencyForIndexPath:(id)indexPath;
+(id)indexForAutoBackupFrequency:(unsigned)autoBackupFrequency;
+(id)disableCellularDataSequence;
-(void).cxx_destruct;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)tableView:(id)view viewForFooterInSection:(int)section;
-(float)tableView:(id)view heightForFooterInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)wa_fontSizeDidChange;
-(void)layoutFooterView;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(id)initWithAutoBackupSettings:(id)autoBackupSettings;
-(id)init;
-(id)initWithStyle:(int)style;
@end

