/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAActionManager.h"

@class NSDate, WAChatStorage, WACloudBackupManager, WAFieldStatsEventICloudBackup;

@interface WABackup : WAActionManager
{
    BOOL _additionalSpaceRequired;
    BOOL _includeVideos;
    BOOL _didTransferToCloud;
    WACloudBackupManager *_manager;
    WAChatStorage *_storage;
    WAFieldStatsEventICloudBackup *_event;
    NSDate *_startDate;
    unsigned int _backupVersion;
    unsigned long long _potentialSize;
    unsigned long long _additionalSpaceAmount;
    unsigned long long _actualSize;
}

- (void)setDidTransferToCloud:(BOOL)fp8;
- (BOOL)didTransferToCloud;
- (void)setBackupVersion:(unsigned int)fp8;
- (unsigned int)backupVersion;
- (void)setIncludeVideos:(BOOL)fp8;
- (BOOL)includeVideos;
- (void)setStartDate:(id)fp8;
- (id)startDate;
- (id)event;
- (id)storage;
- (id)manager;
- (void)setActualSize:(unsigned long long)fp8;
- (unsigned long long)actualSize;
- (void)setAdditionalSpaceAmount:(unsigned long long)fp8;
- (unsigned long long)additionalSpaceAmount;
- (void)setAdditionalSpaceRequired:(BOOL)fp8;
- (BOOL)additionalSpaceRequired;
- (void)setPotentialSize:(unsigned long long)fp8;
- (unsigned long long)potentialSize;
- (void).cxx_destruct;
- (void)sendFieldStatsWithError:(id)fp8;
- (void)phaseCompleted:(id)fp8;
- (void)initializeFieldStats;
- (BOOL)test:(int)fp8 didPass:(BOOL)fp12;
- (unsigned int)maximumPhase;
- (id)errorForCode:(unsigned int)fp8;
- (id)errorDomain;
- (void)start;
- (id)initWithManager:(id)fp8 chatStorage:(id)fp12 options:(unsigned int)fp16 completion:(id)fp(null);
- (id)initWithOptions:(unsigned int)fp8;

@end

