/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIViewControllerAnimatedTransitioning.h"
#import </libobjc.A.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface WABasicPresentationAnimationController : NSObject <UIViewControllerAnimatedTransitioning> {
	BOOL _presenting;
	double _duration;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) double duration;
@property(assign, nonatomic, getter=isPresenting) BOOL presenting;
-(void)animateDismissTransition:(id)transition;
-(void)animatePresentTransition:(id)transition;
-(void)animateTransition:(id)transition;
-(double)transitionDuration:(id)duration;
-(id)init;
@end

