/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>
#import "WhatsApp-Structs.h"

@class UILabel, NSString, WAAnimatedGearsView, NSMutableArray;

__attribute__((visibility("hidden")))
@interface WABackupInfoTableCell : UITableViewCell {
	WAAnimatedGearsView* _gearsView;
	UILabel* _labelHelperText;
	NSMutableArray* _detailLabels;
}
@property(retain, nonatomic) NSMutableArray* detailLabels;
@property(readonly, assign, nonatomic) UILabel* labelHelperText;
@property(retain, nonatomic) NSString* detailText;
@property(readonly, assign, nonatomic) WAAnimatedGearsView* gearsView;
-(void).cxx_destruct;
-(UIEdgeInsets)layoutMargins;
-(float)heightForContentWidth:(float)contentWidth;
-(void)updateFonts;
-(void)layoutSubviews;
-(id)init;
-(id)initWithCoder:(id)coder;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

