/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

#import "UIViewControllerAnimatedTransitioning-Protocol.h"

@interface WABasicPresentationAnimationController : _ABAddressBookCopyArrayOfAllGroups <UIViewControllerAnimatedTransitioning>
{
    BOOL _presenting;
    double _duration;
}

- (void)setDuration:(double)fp8;
- (double)duration;
- (void)setPresenting:(BOOL)fp8;
- (BOOL)isPresenting;
- (void)animateDismissTransition:(id)fp8;
- (void)animatePresentTransition:(id)fp8;
- (void)animateTransition:(id)fp8;
- (double)transitionDuration:(id)fp8;
- (id)init;

@end

