/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class WAChatStorage, NSMutableSet, NSSet, NSMutableArray;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface WABlockedContactsList : NSObject {
	NSMutableSet* _allContacts;
	NSMutableSet* _pendingContacts;
	WAChatStorage* _storage;
	NSObject<OS_dispatch_queue>* _saveQueue;
	BOOL _synchronizationInProgress;
	BOOL _needsUpstreamSync;
	NSMutableArray* _upstreamSyncWebClientRequestIDs;
	id _upstreamSyncWebClientCompletionHandler;
	BOOL _needsDownstreamSync;
}
@property(readonly, assign, nonatomic) NSSet* jids;
@property(readonly, assign, nonatomic) unsigned size;
-(void).cxx_destruct;
-(void)setNeedsDownstreamSync;
-(void)setNeedsUpstreamSync;
-(void)unblockJID:(id)jid webClientRequestID:(id)anId completion:(id)completion;
-(void)blockJID:(id)jid webClientRequestID:(id)anId completion:(id)completion;
-(void)xmppConnectionStateDidChange:(id)xmppConnectionState;
-(void)savePendingContacts;
-(void)saveBlockedContactsToChatStorage:(id)chatStorage;
-(void)requestListFromServer;
-(void)sendListToServer;
-(void)synchronize;
-(void)processBlockedContactsFromServer:(id)server;
-(BOOL)isJIDBlocked:(id)blocked;
-(void)loadContactsIfNecessary;
-(id)initWithChatStorage:(id)chatStorage;
@end

