/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>
#import "WhatsApp-Structs.h"

@class WAAggregateCallEvent, UILabel, NSLayoutConstraint, UIImageView;

__attribute__((visibility("hidden")))
@interface WACallHistoryTableViewCell : UITableViewCell {
	WAAggregateCallEvent* _aggregateCallEvent;
	NSLayoutConstraint* _dateLabelRightEdgeConstraint;
	unsigned _lastCellState;
	UIImageView* _outgoingCallIconView;
	UILabel* _dateLabel;
	UILabel* _eventCountLabel;
	UILabel* _displayNameLabel;
	UILabel* _detailLabel;
}
@property(retain, nonatomic) UILabel* detailLabel;
@property(retain, nonatomic) UILabel* displayNameLabel;
@property(readonly, assign, nonatomic) UILabel* eventCountLabel;
@property(readonly, assign, nonatomic) UILabel* dateLabel;
@property(readonly, assign, nonatomic) UIImageView* outgoingCallIconView;
+(UIEdgeInsets)preferredSeparatorInset;
+(float)preferredRowHeight;
+(void)initialize;
-(void).cxx_destruct;
-(id)infoIconImageView;
-(void)willTransitionToState:(unsigned)state;
-(void)prepareForReuse;
-(void)applyFonts;
-(void)layoutSubviews;
-(id)accessibilityLabel;
-(void)configureWithAggregateCallEvent:(id)aggregateCallEvent;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

