/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class WABatchDispatcher, NSArray, NSMutableArray;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface WACallLogger : NSObject {
	NSMutableArray* _allEvents;
	NSMutableArray* _aggregateEvents;
	NSMutableArray* _missedCallAggregateEvents;
	NSMutableArray* _indexPathsOfUnmissedCallAggregateEvents;
	NSObject<OS_dispatch_queue>* _saveQueue;
	BOOL _dirty;
	WABatchDispatcher* _syncDidFinishNotificationDispatcher;
}
@property(assign, nonatomic) int missedCallCount;
@property(readonly, assign, nonatomic) NSArray* indexPathsOfUnmissedCallAggregateEvents;
@property(readonly, assign, nonatomic) NSArray* missedCallOnlyAggregateEvents;
@property(readonly, assign, nonatomic) NSArray* aggregateEvents;
+(id)peerDisplayNameForUnknownWhatsAppID:(id)unknownWhatsAppID;
+(id)sharedLogger;
-(void).cxx_destruct;
-(void)printAllEvents;
-(void)synchronize;
-(void)applicationWillTerminate:(id)application;
-(void)applicationWillEnterForeground:(id)application;
-(void)applicationDidEnterBackground:(id)application;
-(id)aggregateEventsForTextSearchQuery:(id)textSearchQuery numberSearchQuery:(id)query;
-(void)reloadAllContactNames;
-(void)syncManagerDidFinishSync:(id)syncManager;
-(void)processMissedCallOnlyAggregateEvents;
-(void)clearAllCallEvents;
-(void)removeAggregateCallEvent:(id)event;
-(void)addCallEvent:(id)event;
-(void)rebuildAggregateCallEvents;
-(void)dealloc;
-(id)init;
@end

