/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol WACameraControllerDelegate <NSObject>
- (void)cameraControllerDidCancelVideoRecording:(id)fp8;
- (void)cameraController:(id)fp8 videoRecordingDidFinishRecordingToFile:(id)fp12;
- (void)cameraController:(id)fp8 videoRecordingDidFailWithError:(id)fp12;
- (void)cameraControllerDidReceiveRuntimeErrorNotification:(id)fp8;
- (void)cameraController:(id)fp8 didDetectQRCode:(id)fp12;
- (void)cameraControllerDidChangeFlashActiveState:(id)fp8;
- (void)cameraControllerDidUpdateFaceObjects:(id)fp8;
- (void)cameraControllerDidChangePreviewImageSize:(id)fp8;
- (void)cameraControllerDidResetPointOfInterest:(id)fp8;
- (void)cameraControllerSessionDidStopRunning:(id)fp8;
- (void)cameraControllerSessionDidBeginRunning:(id)fp8;
@end

