/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol WACaptionBarDelegate <NSObject>
-(void)captionBarDidChangeText:(id)captionBar;
-(void)captionBarDidFinishEditing:(id)captionBar;
-(void)captionBarDidHideKeyboard:(id)captionBar;
-(void)captionBarWillHideKeyboard:(id)captionBar;
-(void)captionBarWillShowKeyboard:(id)captionBar;
@end

