/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>

@class UIImageView, WACameraFaceObject;

__attribute__((visibility("hidden")))
@interface WACameraPreviewFaceView : UIView {
	UIImageView* _outlineImageView;
	WACameraFaceObject* _faceObject;
}
@property(readonly, assign, nonatomic) WACameraFaceObject* faceObject;
-(void).cxx_destruct;
-(void)updateFrame;
-(void)fadeOutAfterDelay:(double)delay;
-(id)initWithFaceObject:(id)faceObject;
@end

