/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol WACaptionBarDelegate <NSObject>
- (void)captionBarDidChangeText:(id)fp8;
- (void)captionBarDidFinishEditing:(id)fp8;
- (void)captionBarDidHideKeyboard:(id)fp8;
- (void)captionBarWillHideKeyboard:(id)fp8;
- (void)captionBarWillShowKeyboard:(id)fp8;
@end

