/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class UILabel, UIView, NSLayoutConstraint, WAProfilePictureThumbnailView;

__attribute__((visibility("hidden")))
@interface WAChatDatabaseStatsTableViewCell : UITableViewCell {
	BOOL _includeDocumentStats;
	UIView* _containerView;
	WAProfilePictureThumbnailView* _imageViewContactPicture;
	UILabel* _nameLabel;
	UILabel* _detailLabel;
	UILabel* _textType;
	UILabel* _imageType;
	UILabel* _videoType;
	UILabel* _audioType;
	UILabel* _locationType;
	UILabel* _contactType;
	UILabel* _documentType;
	UILabel* _totalType;
	UILabel* _textCount;
	UILabel* _imageCount;
	UILabel* _videoCount;
	UILabel* _audioCount;
	UILabel* _locationCount;
	UILabel* _contactCount;
	UILabel* _documentCount;
	UILabel* _totalCount;
	UILabel* _imageSize;
	UILabel* _videoSize;
	UILabel* _audioSize;
	UILabel* _documentSize;
	UILabel* _totalSize;
	NSLayoutConstraint* _nameToDetailConstraint;
	NSLayoutConstraint* _nameToContainerConstraint;
}
@property(retain, nonatomic) NSLayoutConstraint* nameToContainerConstraint;
@property(retain, nonatomic) NSLayoutConstraint* nameToDetailConstraint;
@property(retain, nonatomic) UILabel* totalSize;
@property(retain, nonatomic) UILabel* documentSize;
@property(retain, nonatomic) UILabel* audioSize;
@property(retain, nonatomic) UILabel* videoSize;
@property(retain, nonatomic) UILabel* imageSize;
@property(retain, nonatomic) UILabel* totalCount;
@property(retain, nonatomic) UILabel* documentCount;
@property(retain, nonatomic) UILabel* contactCount;
@property(retain, nonatomic) UILabel* locationCount;
@property(retain, nonatomic) UILabel* audioCount;
@property(retain, nonatomic) UILabel* videoCount;
@property(retain, nonatomic) UILabel* imageCount;
@property(retain, nonatomic) UILabel* textCount;
@property(retain, nonatomic) UILabel* totalType;
@property(retain, nonatomic) UILabel* documentType;
@property(retain, nonatomic) UILabel* contactType;
@property(retain, nonatomic) UILabel* locationType;
@property(retain, nonatomic) UILabel* audioType;
@property(retain, nonatomic) UILabel* videoType;
@property(retain, nonatomic) UILabel* imageType;
@property(retain, nonatomic) UILabel* textType;
@property(retain, nonatomic) UILabel* detailLabel;
@property(retain, nonatomic) UILabel* nameLabel;
@property(retain, nonatomic) WAProfilePictureThumbnailView* imageViewContactPicture;
@property(retain, nonatomic) UIView* containerView;
+(float)preferredRowHeightExpanded:(BOOL)expanded;
-(void).cxx_destruct;
-(void)setDetailLabelHidden:(BOOL)hidden withAnimation:(BOOL)animation;
-(void)formatCellWithRecord:(id)record detailType:(int)type;
-(void)layoutViews;
-(void)createDetailLabels;
-(void)setLabelFonts;
-(id)createDetailLabelWithAlignment:(int)alignment dark:(BOOL)dark;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

