/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@interface WAChatBarManagerFactory : _ABAddressBookCopyArrayOfAllGroups
{
}

+ (BOOL)isInteractiveKeyboardDraggingSupported;
+ (id)PTTButtonAccessibilityHint;
+ (BOOL)isPTTRecordingInProgress;
+ (void)setPTTRecordingInProgress:(BOOL)fp8;
+ (id)chatBarManagerWithInitialWidth:(float)fp8;

@end

