/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <CoreData/NSManagedObject.h>

@class NSString, NSNumber, NSDate, WAChatSession;

__attribute__((visibility("hidden")))
@interface WAChatProperties : NSManagedObject {
}
@property(retain, nonatomic) WAChatSession* chatSession;
@property(retain, nonatomic) NSDate* muteDate;
@property(retain, nonatomic) NSNumber* alerts;
@property(retain, nonatomic) NSString* soundName;
@property(retain, nonatomic) NSNumber* enabled;
@end

