/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

#import "WAMediaProgressDelegate-Protocol.h"

@class AVSpeechUtterance, NSArray, NSDate, NSMutableArray, NSNumber, WAMediaDataPresentationController, WAMergedContact;

@interface WAChatCellData : _ABAddressBookCopyArrayOfAllGroups <WAMediaProgressDelegate>
{
    NSDate *_date;
    NSMutableArray *_messages;
    AVSpeechUtterance *_currentUtterance;
    WAMergedContact *_vCardContact;
    BOOL _disallowMerging;
    BOOL _disallowBubbleHeader;
    BOOL _selected;
    BOOL _longTimestampFormat;
    BOOL _fromMe;
    BOOL _chatIsSuspicious;
    BOOL _mergedWithNextMessage;
    BOOL _mergedWithPreviousMessage;
    BOOL _searchResult;
    BOOL _unreadAllVoice;
    BOOL _didAnnounceMediaUploadOrDownloadStatus;
    BOOL _vCardActionsAllowed;
    short _sessionType;
    WAMediaDataPresentationController *_presentationController;
    unsigned int _type;
    unsigned int _bubbleDirection;
    float _progress;
    NSArray *_textMessages;
    float _lastHeight;
    NSNumber *_unreadCount;
    unsigned int _pttPlayerState;
    float _pttPlayerProgress;
    struct CGSize _lastSize;
    struct UIEdgeInsets _cellInsets;
}

+ (BOOL)textEffectsEnabled;
+ (id)divider;
+ (void)initialize;
- (void)setVCardActionsAllowed:(BOOL)fp8;
- (BOOL)vCardActionsAllowed;
- (void)setDidAnnounceMediaUploadOrDownloadStatus:(BOOL)fp8;
- (BOOL)didAnnounceMediaUploadOrDownloadStatus;
- (void)setPttPlayerProgress:(float)fp8;
- (float)pttPlayerProgress;
- (void)setPttPlayerState:(unsigned int)fp8;
- (unsigned int)pttPlayerState;
- (void)setUnreadAllVoice:(BOOL)fp8;
- (BOOL)unreadAllVoice;
- (void)setUnreadCount:(id)fp8;
- (id)unreadCount;
- (short)sessionType;
- (void)setSearchResult:(BOOL)fp8;
- (BOOL)isSearchResult;
- (void)setLastSize:(struct CGSize)fp8;
- (struct CGSize)lastSize;
- (void)setLastHeight:(float)fp8;
- (float)lastHeight;
- (id)messages;
- (void)setTextMessages:(id)fp8;
- (id)textMessages;
- (void)setMergedWithPreviousMessage:(BOOL)fp8;
- (BOOL)mergedWithPreviousMessage;
- (void)setMergedWithNextMessage:(BOOL)fp8;
- (BOOL)mergedWithNextMessage;
- (void)setChatIsSuspicious:(BOOL)fp8;
- (BOOL)chatIsSuspicious;
- (BOOL)isFromMe;
- (void)setLongTimestampFormat:(BOOL)fp8;
- (BOOL)longTimestampFormat;
- (void)setProgress:(float)fp8;
- (float)progress;
- (void)setSelected:(BOOL)fp8;
- (BOOL)selected;
- (void)setBubbleDirection:(unsigned int)fp8;
- (unsigned int)bubbleDirection;
- (void)setCellInsets:(struct UIEdgeInsets)fp8;
- (struct UIEdgeInsets)cellInsets;
- (void)setDisallowBubbleHeader:(BOOL)fp8;
- (BOOL)disallowBubbleHeader;
- (void)setDisallowMerging:(BOOL)fp8;
- (BOOL)disallowMerging;
- (unsigned int)type;
- (id)presentationController;
- (void).cxx_destruct;
- (void)stopSpeakingContent;
- (void)startSpeakingContent;
- (BOOL)isSpeakingContent;
- (void)textToSpeechEngineDidFinishSpeechUtterance:(id)fp8;
- (void)textToSpeechEngineDidCancelSpeechUtterance:(id)fp8;
- (BOOL)containsSpeakableContent;
- (void)setProgress:(float)fp8 forMessage:(id)fp12;
- (id)dividerText;
- (id)fullEventText;
- (id)vCardContact;
- (id)vCardContactImage;
- (id)vCardContactName;
- (CDAnonymousStruct15)locationCoordinate;
- (id)placeURL;
- (id)placeAddress;
- (id)placeName;
- (void)queueDownloadOfUndownloadedMedia;
- (BOOL)containsUndownloadedMedia;
- (void)reloadPresentationController;
- (id)mediaThumbnail;
- (id)mediaURLString;
- (id)fullMediaPath;
- (struct CGSize)thumbnailSize;
- (BOOL)mediaLoading;
- (long long)fileSize;
- (BOOL)canDoPartialMergeWithCellData:(id)fp8;
- (BOOL)canDoFullMergeWithMessage:(id)fp8;
- (id)messageStrings;
- (void)regenerateTextMessages;
- (void)removeMessage:(id)fp8;
- (void)addMessage:(id)fp8 addToFront:(BOOL)fp12;
- (void)fontSizeDidChange:(id)fp8;
- (void)removeObjectFromMessagesAtIndex:(unsigned int)fp8;
- (void)insertObject:(id)fp8 inMessagesAtIndex:(unsigned int)fp12;
- (id)textMessageForText:(id)fp8;
- (BOOL)canBeForwarded;
- (BOOL)requiresBroadcastListIcon;
- (unsigned int)footerStatus;
- (id)nameColor;
- (id)shortName;
- (id)pushName;
- (id)fromName;
- (id)messageID;
- (BOOL)needToShowAlert;
- (id)allUnsentMessages;
- (BOOL)isSenderUnknown;
- (BOOL)isGroupMessage;
- (BOOL)isSending;
- (BOOL)isStarred;
- (BOOL)skipCellLayout;
- (id)messageTimestampString;
- (unsigned int)messageStatus;
- (unsigned int)mediaOrigin;
- (unsigned int)messageType;
- (id)message;
- (id)date;
- (void)dealloc;
- (id)initWithMessage:(id)fp8 highlightedTerms:(id)fp12;
- (id)initWithType:(unsigned int)fp8;
- (id)init;

@end

