/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSIndexPath, NSArray, NSSet, NSMutableArray;
@protocol WAChatMessagesControllerDelegate;

__attribute__((visibility("hidden")))
@interface WAChatMessagesController : NSObject {
	NSMutableArray* _sections;
	BOOL _showReportSpamCell;
	id<WAChatMessagesControllerDelegate> _delegate;
	NSSet* _highlightedTerms;
}
@property(readonly, assign, nonatomic, getter=isEmpty) BOOL empty;
@property(retain, nonatomic) NSSet* highlightedTerms;
@property(readonly, assign, nonatomic) NSArray* sections;
@property(readonly, assign, nonatomic) unsigned messageCount;
@property(readonly, assign, nonatomic) NSIndexPath* reportSpamCellIndexPath;
@property(readonly, assign, nonatomic) NSIndexPath* dividerIndexPath;
@property(readonly, assign, nonatomic) NSIndexPath* bottomMostIndexPath;
@property(assign, nonatomic) BOOL showReportSpamCell;
@property(assign, nonatomic) __weak id<WAChatMessagesControllerDelegate> delegate;
-(void).cxx_destruct;
-(void)prependMessages:(id)messages withConfigurationBlock:(id)configurationBlock;
-(BOOL)appendMessages:(id)messages currentUnreadCount:(int)count searchResultMessageIDs:(id)ids dividerBehavior:(unsigned)behavior withConfigurationBlock:(id)configurationBlock;
-(id)lastMessage;
-(void)clearSearchResultIndicators;
-(void)deleteChatCellDataObjects:(id)objects updatingIndexPaths:(id)paths;
-(void)deleteChatCellDataObjects:(id)objects;
-(unsigned)removeMessages:(id)messages;
-(void)enumerateChatCellDataUsingBlock:(id)block;
-(BOOL)removeReportSpamCell;
-(BOOL)removeUnreadDivider;
-(id)chatCellDataForMessage:(id)message;
-(id)allSelectedMessages;
-(id)allSelectedCellDataObjects;
-(id)allUnsentMessagesAroundCellData:(id)data cellDataObjectCount:(unsigned*)count;
-(BOOL)hasEditableMessages;
-(void)removeChatCellDataAtIndexPath:(id)indexPath;
-(id)indexPathOfChatCellData:(id)chatCellData;
-(id)indexPathOfMessage:(id)message;
-(id)chatCellDataAtIndexPath:(id)indexPath;
-(id)indexPathOfRowFollowingRowAtIndexPath:(id)indexPath;
-(void)removeAllMessages;
-(id)titleForSection:(int)section;
-(int)numberOfRowsInSection:(int)section;
-(int)numberOfSections;
-(void)getDay:(int*)day month:(int*)month year:(int*)year fromDate:(id)date;
-(id)init;
@end

