/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol WAChatBarManager <NSObject>
- (id)pttButton;
- (id)attachMediaButton;
- (void)setKeyboardPresentationDisabled:(BOOL)fp8;
- (BOOL)isKeyboardPresentationDisabled;
- (void)setEnabled:(BOOL)fp8;
- (BOOL)isEnabled;
- (BOOL)shouldAutorotate;
- (void)setInteractiveKeyboardDraggingEnabled:(BOOL)fp8;
- (BOOL)interactiveKeyboardDraggingEnabled;
- (void)setChatBarAlpha:(float)fp8;
- (float)chatBarAlpha;
- (void)setScrollToBottomOnShowKeyboardOnAppear:(BOOL)fp8;
- (BOOL)scrollToBottomOnShowKeyboardOnAppear;
- (void)setShowKeyboardOnAppear:(BOOL)fp8;
- (BOOL)showKeyboardOnAppear;
- (BOOL)interactiveKeyboardDraggingInProgress;
- (void)setText:(id)fp8;
- (id)text;
- (float)bottomInset;
- (float)contentViewHeight;
- (id)contentView;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)cancelPTTRecording;
- (void)setPTTRecordingTime:(double)fp8;
- (void)setNeedsUpdateButtons;
- (void)showPopupMenuForMessageCell:(id)fp8;
- (void)endDraggingChatBarWithTranslation:(float)fp8;
- (void)updateChatBarDraggingWithTranslation:(float)fp8;
- (BOOL)beginDraggingChatBar;
- (void)ensureKeyboardHidden;
- (void)delegateWillDisappearWithoutInteraction;
- (void)didChangeInterfaceOrientation;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8;
- (void)willChangeInterfaceOrientation;
- (void)hideKeyboard;
- (BOOL)isKeyboardVisible;
- (void)makeKeyboardWindowKeyWindow;
- (void)makeMainApplicationWindowKeyWindow;
- (void)restoreKeyWindow;
@end

