/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class UILabel, NSString, UIView, _WAChatSessionCellIndicatorsView, WALabel, WAProfilePictureThumbnailView;
@protocol WAChatSessionCellDelegate;

__attribute__((visibility("hidden")))
@interface WAChatSessionCell : UITableViewCell {
	float _currentFontSize;
	BOOL _muted;
	BOOL _archived;
	BOOL _showGroupParticipants;
	BOOL _ignoreExternalUpdates;
	BOOL _unknownContact;
	BOOL _showLocationIcon;
	BOOL _showCameraIcon;
	BOOL _showCamcorderIcon;
	BOOL _showContactIcon;
	BOOL _showDocumentIcon;
	NSString* _jid;
	int _unreadCount;
	id<WAChatSessionCellDelegate> _delegate;
	UIView* _containerView;
	WALabel* _nameLabel;
	UILabel* _senderLabel;
	UILabel* _timeLabel;
	_WAChatSessionCellIndicatorsView* _indicatorsView;
	UIView* _lastMessageContainer;
	WALabel* _messageLabel;
	UILabel* _activityLabel;
	WAProfilePictureThumbnailView* _imageViewContactPicture;
	NSString* _messageText;
	unsigned _pushToTalkIconType;
	NSString* _chatActivityText;
}
@property(copy, nonatomic) NSString* chatActivityText;
@property(assign, nonatomic) unsigned pushToTalkIconType;
@property(assign, nonatomic) BOOL showDocumentIcon;
@property(assign, nonatomic) BOOL showContactIcon;
@property(assign, nonatomic) BOOL showCamcorderIcon;
@property(assign, nonatomic) BOOL showCameraIcon;
@property(assign, nonatomic) BOOL showLocationIcon;
@property(copy, nonatomic) NSString* messageText;
@property(assign, nonatomic) BOOL unknownContact;
@property(retain, nonatomic) WAProfilePictureThumbnailView* imageViewContactPicture;
@property(retain, nonatomic) UILabel* activityLabel;
@property(retain, nonatomic) WALabel* messageLabel;
@property(retain, nonatomic) UIView* lastMessageContainer;
@property(retain, nonatomic) _WAChatSessionCellIndicatorsView* indicatorsView;
@property(retain, nonatomic) UILabel* timeLabel;
@property(retain, nonatomic) UILabel* senderLabel;
@property(retain, nonatomic) WALabel* nameLabel;
@property(retain, nonatomic) UIView* containerView;
@property(assign, nonatomic) __weak id<WAChatSessionCellDelegate> delegate;
@property(readonly, assign, nonatomic, getter=isResizingSideButtons) BOOL resizingSideButtons;
@property(assign, nonatomic) BOOL ignoreExternalUpdates;
@property(assign, nonatomic) int unreadCount;
@property(assign, nonatomic) BOOL showGroupParticipants;
@property(assign, nonatomic) BOOL archived;
@property(assign, nonatomic) BOOL muted;
@property(copy, nonatomic) NSString* jid;
+(BOOL)moreOptionsMenuSupported;
+(id)documentIconImageHighlighted;
+(id)documentIconImage;
+(id)contactIconImageHighlighted;
+(id)contactIconImage;
+(id)camcorderIconImageHighlighted;
+(id)camcorderIconImage;
+(id)cameraIconImageHighlighted;
+(id)cameraIconImage;
+(id)locationIconImageHighlighted;
+(id)locationIconImage;
+(id)microphoneImageHighlighted;
+(id)microphoneImageForPTTIconType:(unsigned)ptticonType;
+(id)cellWithReuseIdentifier:(id)reuseIdentifier;
-(void).cxx_destruct;
-(void)xmppConnectionChatStateDidChange:(id)xmppConnectionChatState;
-(void)waMessageUpdated:(id)updated;
-(void)hideSideButtonsAnimated:(BOOL)animated completion:(id)completion;
-(void)cancelResizingSideButtons;
-(void)reloadFonts;
-(void)reconfigureWithMessage:(id)message;
-(void)configureWithChatSession:(id)chatSession message:(id)message;
-(id)accessibilityLabel;
-(BOOL)isAccessibilityElement;
-(void)setChatActivityText:(id)text animated:(BOOL)animated;
-(void)setHighlighted:(BOOL)highlighted animated:(BOOL)animated;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(void)prepareForReuse;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

