/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import "WAShapeView.h"

@class UIColor;

__attribute__((visibility("hidden")))
@interface WACircularActivityView : WAShapeView {
	BOOL _animating;
	BOOL _hidesWhenStopped;
	UIColor* _color;
}
@property(assign) BOOL hidesWhenStopped;
@property(retain, nonatomic) UIColor* color;
@property(assign, nonatomic) float barWidth;
-(void).cxx_destruct;
-(void)stopAnimating;
-(void)startAnimating;
-(BOOL)isAnimating;
-(void)applicationWillEnterForeground:(id)application;
-(void)updateVisibility;
-(void)tintColorDidChange;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

