/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WAWaitOperation.h"

@class WAActionManager, WAChatStorage;

__attribute__((visibility("hidden")))
@interface WACleanUpBackupOperation : WAWaitOperation {
	BOOL _disconnected;
	BOOL _locked;
	BOOL _dropped;
	WAActionManager* _actionManager;
	WAChatStorage* _storage;
}
@property(readonly, assign, nonatomic) WAChatStorage* storage;
@property(readonly, assign, nonatomic) WAActionManager* actionManager;
@property(assign) BOOL dropped;
@property(assign) BOOL locked;
@property(assign) BOOL disconnected;
-(void).cxx_destruct;
-(void)reloadStore;
-(void)releaseLock;
-(void)reenableConnection;
-(void)storeWasDropped;
-(void)syncManagerLockWasAcquired;
-(void)serverWasDisconnected;
-(void)cancel;
-(void)run;
-(id)initWithActionManager:(id)actionManager andStorage:(id)storage;
-(id)initWithCount:(int)count dependenciesRequired:(BOOL)required;
@end

