/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSMutableDictionary, NSSet, NSString;

__attribute__((visibility("hidden")))
@interface WACloudStatus : NSObject {
	unsigned _mode;
	id _fileIncluder;
	unsigned _listenerIndex;
	NSMutableDictionary* _listeners;
}
@property(retain, nonatomic) NSMutableDictionary* listeners;
@property(assign, nonatomic) unsigned listenerIndex;
@property(readonly, assign, nonatomic) unsigned listenerCount;
@property(readonly, assign, nonatomic) NSSet* errorCodes;
@property(readonly, assign, nonatomic) float completedPercent;
@property(readonly, assign, nonatomic) unsigned long long completedSize;
@property(readonly, assign, nonatomic) unsigned long long totalSize;
@property(copy, nonatomic) id fileIncluder;
@property(readonly, assign, nonatomic) BOOL inProgress;
@property(readonly, assign, nonatomic, getter=isValid) BOOL valid;
@property(readonly, assign, nonatomic) NSString* modeAsString;
@property(readonly, assign, nonatomic) unsigned mode;
+(id)statusForDownloadingWithManager:(id)manager;
+(id)statusForUploadingWithManager:(id)manager;
-(void).cxx_destruct;
-(void)removeListener:(id)listener;
-(id)addListenerWithBlock:(id)block;
-(id)nextUniqueListenerIdentifier;
-(void)postUpdatedNotification;
-(BOOL)checkError:(unsigned)error;
-(void)forceRefresh;
-(id)initWithMode:(unsigned)mode;
-(id)init;
@end

