/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WACloudBackupManager.h"

@class NSString, NSURL;

__attribute__((visibility("hidden")))
@interface WACloudBackupManager_Documents : WACloudBackupManager {
	NSString* _capturedRemoteBackupPath;
	id _ubiquityURL;
}
@property(readonly, assign, nonatomic) NSString* remoteBackupPath;
@property(retain, nonatomic) NSURL* ubiquityURL;
+(BOOL)getValue:(BOOL*)value ofKey:(id)key forPath:(id)path;
+(BOOL)getFileDownloaded:(BOOL*)downloaded forPath:(id)path;
+(BOOL)getFileDownloading:(BOOL*)downloading forPath:(id)path;
+(BOOL)startFileDownloading:(id)downloading;
+(BOOL)startFileDownloading:(id)downloading error:(id*)error;
+(id)phoneNumberFromBackupInfoFilePath:(id)backupInfoFilePath;
-(void).cxx_destruct;
-(BOOL)extractToTmp;
-(BOOL)evictFiles;
-(void)removeCloudItemsAtPaths:(id)paths;
-(void)fixCloudAccount;
-(void)loadUbiquityURL;
-(void)ubiquityIdentityTokenDidChange;
-(id)remoteBackupPathEnumeratorWithProperties:(id)properties;
-(void)downloadMetadataForAllBackups;
-(void)deleteBackup:(id)backup withOptions:(unsigned)options completion:(id)completion;
-(BOOL)isUserRegistered_cached;
-(id)createDownloadOperationWithRestore:(id)restore;
-(id)createUploadOperationWithBackup:(id)backup fromOperation:(id)operation;
-(void)configureCloudOperation:(id)operation;
-(void)startCurrentAction;
-(id)createDownloadStatus;
-(id)createUploadStatus;
-(void)reportUploadStatusFinished:(id)finished;
-(id)createPreviousBackup;
-(id)statisticsFileName;
-(id)buildRemoteBackupPath:(id)path;
-(id)localRestorePath;
-(id)localBackupPath;
-(BOOL)initialized;
-(BOOL)availableEstimate;
-(BOOL)available;
-(id)initWithAutoBackupSettings:(id)autoBackupSettings errorManager:(id)manager;
@end

