/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class UIView;

@interface WAContactActionTableViewCell : _ABAddressBookCopyArrayOfAllGroups
{
    UIView *_topEdge;
    UIView *_bottomEdge;
}

- (void).cxx_destruct;
- (void)setShowTopEdge:(BOOL)fp8;
- (BOOL)showTopEdge;
- (void)setShowBottomEdge:(BOOL)fp8;
- (BOOL)showBottomEdge;
- (void)layoutSubviews;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;

@end

