/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class WAChatStorage, WAContactsStorage, NSArray;
@protocol WAContactsSearchControllerDelegate;

__attribute__((visibility("hidden")))
@interface WAContactsSearchController : NSObject {
	WAChatStorage* _chatStorage;
	WAContactsStorage* _contactsStorage;
	id<WAContactsSearchControllerDelegate> _delegate;
	NSArray* _allContactInfos;
}
@property(retain, nonatomic) NSArray* allContactInfos;
@property(assign, nonatomic) __weak id<WAContactsSearchControllerDelegate> delegate;
-(void).cxx_destruct;
-(id)contactsMatchingText:(id)text;
-(id)contactsMatchingJIDs:(id)jids;
-(void)loadIfNeeded;
-(void)reset;
-(void)syncManagerDidFinishSync:(id)syncManager;
-(void)dealloc;
-(id)initWithChatStorage:(id)chatStorage contactsStorage:(id)storage;
@end

