/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WAContactMultiValueEditingCell.h"


__attribute__((visibility("hidden")))
@interface WAContactSocialEditingCell : WAContactMultiValueEditingCell {
}
-(void)contactPropertyTextFieldValueChanged:(id)changed;
-(void)reconfigure;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

