/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class NSLayoutConstraint, UILabel, UIView;

@interface WAContactInfoSectionHeaderView : _ABAddressBookCopyArrayOfAllGroups
{
    UILabel *_titleLabel;
    UIView *_topBorder;
    UIView *_bottomBorder;
    NSLayoutConstraint *_titleHorizontalConstraint;
    NSLayoutConstraint *_backgroundViewBottomConstraint;
    UIView *_backgroundView;
    BOOL _extendsLowerEdge;
    struct UIEdgeInsets _insets;
}

- (BOOL)extendsLowerEdge;
- (struct UIEdgeInsets)insets;
- (void).cxx_destruct;
- (void)setBottomEdgeHidden:(BOOL)fp8;
- (BOOL)bottomEdgeHidden;
- (void)setTopEdgeHidden:(BOOL)fp8;
- (BOOL)topEdgeHidden;
- (void)setText:(id)fp8;
- (id)text;
- (void)setExtendsLowerEdge:(BOOL)fp8;
- (void)setInsets:(struct UIEdgeInsets)fp8;
- (void)updateConstraints;
- (id)initWithFrame:(struct CGRect)fp8;

@end

