/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <CoreData/NSManagedObject.h>

@class NSString, NSDate, NSSet, NSNumber, NSArray, WAContactSection;

__attribute__((visibility("hidden")))
@interface WAContact : NSManagedObject {
}
@property(retain, nonatomic) NSSet* children;
@property(retain, nonatomic) WAContact* parent;
@property(readonly, assign, nonatomic) NSString* displayNameShort;
@property(readonly, assign, nonatomic) NSString* displayNameMedium;
@property(readonly, assign, nonatomic) NSString* displayNameLong;
@property(retain, nonatomic) NSDate* lastModifiedDate;
@property(retain, nonatomic) WAContactSection* section;
@property(retain, nonatomic) NSSet* phones;
@property(retain, nonatomic) NSNumber* sort;
@property(retain, nonatomic) NSArray* tokens;
@property(retain, nonatomic) NSString* highlightedName;
@property(retain, nonatomic) NSString* indexName;
@property(retain, nonatomic) NSString* firstName;
@property(retain, nonatomic) NSString* nickname;
@property(retain, nonatomic) NSString* fullName;
@property(retain, nonatomic) NSNumber* abUserID;
+(id)mergedContactWithParent:(id)parent includeChildren:(BOOL)children dedupeProperties:(BOOL)properties;
+(BOOL)isABPersonRecordReadony:(void*)readony;
+(id)allLinkedNonWhatsAppPhonesWithParent:(id)parent includeChildren:(BOOL)children;
+(id)allLinkedWhatsAppPhonesWithParent:(id)parent includeChildren:(BOOL)children;
-(id)individualContactAsMergedContact;
-(id)mergedContactForEditing;
-(id)mergedContact;
-(id)allLinkedAddressBookIDs;
-(id)allLinkedNonWhatsAppPhones;
-(id)allLinkedWhatsAppPhones;
@end

