/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class UIImage;

__attribute__((visibility("hidden")))
@interface WAContactInfoPhotoUnit : NSObject {
	UIImage* _image;
}
@property(readonly, assign, nonatomic) UIImage* image;
+(id)contactInfoPhotoUnitForRecord:(void*)record;
-(void).cxx_destruct;
-(id)initWithRecord:(void*)record;
@end

