/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@interface WAContactPopup : _ABAddressBookCopyArrayOfAllGroups
{
    int _imageTag;
}

+ (id)popupWithAnnotation:(id)fp8 reuseIdentifier:(id)fp12;
- (void)setImageTag:(int)fp8;
- (int)imageTag;
- (void)setAnnotation:(id)fp8;
- (id)initWithAnnotation:(id)fp8 reuseIdentifier:(id)fp12;

@end

