/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class WAContactProperty, UIView;

__attribute__((visibility("hidden")))
@interface WAContactPropertyCell : UITableViewCell {
	BOOL _isActionButton;
	UIView* _topSeparator;
	UIView* _bottomSeparator;
	id _delegate;
	WAContactProperty* _contactProperty;
}
@property(retain, nonatomic) WAContactProperty* contactProperty;
@property(assign, nonatomic) __weak id delegate;
+(float)rowHeight;
+(float)rowHeightForContactProperty:(id)contactProperty;
+(id)cellForWAContactProperty:(id)wacontactProperty withReuseIdentifier:(id)reuseIdentifier;
+(Class)cellClassForWAContactProperty:(id)wacontactProperty;
-(void).cxx_destruct;
-(void)configureAsDeleteContactRow;
-(void)configureAsAddValueRowForABProperty:(int)abproperty;
-(void)reconfigure;
-(void)refreshTextColor;
-(void)tintColorDidChange;
-(void)layoutSubviews;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

