/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import "NSCopying.h"
#import "NSFastEnumeration.h"
#import </libobjc.A.h>

@class NSArray, NSMutableArray;

__attribute__((visibility("hidden")))
@interface WAContactMultiValueProperty : NSObject <NSCopying, NSFastEnumeration> {
	NSMutableArray* _deletedProperties;
	int _abPropertyID;
	NSArray* _properties;
}
@property(retain, nonatomic) NSArray* properties;
@property(readonly, assign) unsigned count;
@property(readonly, assign, nonatomic) NSArray* deletedProperties;
@property(assign, nonatomic) int abPropertyID;
+(id)propertyWithABProperty:(int)abproperty properties:(id)properties;
-(void).cxx_destruct;
-(id)copyWithZone:(NSZone*)zone;
-(unsigned)hash;
-(BOOL)isEqualToProperty:(id)property;
-(BOOL)isEqual:(id)equal;
-(unsigned)countByEnumeratingWithState:(XXStruct_kFm5bA*)state objects:(id*)objects count:(unsigned)count;
-(void)enumeratePropertiesAtIndexes:(id)indexes options:(unsigned)options usingBlock:(id)block;
-(void)enumeratePropertiesWithOptions:(unsigned)options usingBlock:(id)block;
-(void)enumeratePropertiesUsingBlock:(id)block;
-(id)propertiesPassingTest:(id)test;
-(unsigned)indexOfPropertyIdenticalTo:(id)to;
-(void)removePropertyAtIndex:(unsigned)index;
-(void)addPropertiesFromArray:(id)array;
-(void)addProperty:(id)property;
-(id)objectAtIndexedSubscript:(unsigned)indexedSubscript;
-(id)propertyAtIndex:(unsigned)index;
-(id)lastProperty;
-(id)firstProperty;
-(id)init;
-(id)initWithABProperty:(int)abproperty properties:(id)properties;
@end

