/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import <UIKit/UIImageView.h>


__attribute__((visibility("hidden")))
@interface WACropAwareImageView : UIImageView {
	float _fixedHeight;
	CGRect _normalizedCropRect;
}
@property(assign, nonatomic) float fixedHeight;
@property(assign, nonatomic) CGRect normalizedCropRect;
+(CGRect)transformNormalizedCropRect:(CGRect)rect forImageOrientation:(int)imageOrientation;
-(void)recalculateImageMetrics;
-(void)setImage:(id)image;
-(id)initWithFrame:(CGRect)frame;
@end

