/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WAPercentDrivenInteractiveTransitioning.h"
#import </libobjc.A.h>

@class NSString, CADisplayLink;
@protocol UIViewControllerAnimatedTransitioning, UIViewControllerContextTransitioning;

__attribute__((visibility("hidden")))
@interface WACustomPercentDrivenInteractiveTransition : NSObject <WAPercentDrivenInteractiveTransitioning> {
	id<UIViewControllerContextTransitioning> _transitionContext;
	id<UIViewControllerAnimatedTransitioning> _animator;
	CADisplayLink* _displayLink;
	float _percentComplete;
	double _initialTimeOffset;
	float _completionSpeed;
	id _updateHandler;
}
@property(copy, nonatomic) id updateHandler;
@property(assign, nonatomic) float completionSpeed;
@property(readonly, assign, nonatomic) float percentComplete;
@property(readonly, assign, nonatomic) float duration;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(void)removeAllAnimationsInLayer:(id)layer;
-(void)didFinishTransition;
-(void)animate:(id)animate;
-(void)completeTransition;
-(void)setPercentComplete:(float)complete;
-(void)finishInteractiveTransition;
-(void)cancelInteractiveTransition;
-(void)updateInteractiveTransition:(float)transition;
-(void)startInteractiveTransition:(id)transition;
-(id)initWithAnimator:(id)animator;
-(id)init;
@end

