/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSManagedObjectContext, NSArray;

__attribute__((visibility("hidden")))
@interface WADatabaseResultsFetcher : NSObject {
	NSManagedObjectContext* _sourceManagedObjectContext;
	NSManagedObjectContext* _destinationManagedObjectContext;
	NSArray* _objectIDs;
	NSArray* _relationshipKeyPathsForPrefetching;
}
@property(readonly, assign, nonatomic) unsigned objectCount;
@property(retain, nonatomic) NSArray* relationshipKeyPathsForPrefetching;
@property(retain, nonatomic) NSArray* objectIDs;
@property(retain, nonatomic) NSManagedObjectContext* destinationManagedObjectContext;
@property(retain, nonatomic) NSManagedObjectContext* sourceManagedObjectContext;
+(id)nullFetcher;
-(void).cxx_destruct;
-(id)fetchResults;
@end

