/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import <UIKit/UIView.h>

@class UILabel, NSString, UIImageView;
@protocol WADateBubbleViewDelegate;

__attribute__((visibility("hidden")))
@interface WADateBubbleView : UIView {
	UIImageView* _bubbleImageView;
	UILabel* _titleLabel;
	UIView* _backgroundView;
	UIView* _maskView;
	UIImageView* _blurredBackgroundView;
	UIImageView* _highlightsImageView;
	BOOL _useBlurredBackground;
	id<WADateBubbleViewDelegate> _delegate;
	float _floating;
	int _sectionIndex;
	CGRect _toFrame;
}
@property(assign, nonatomic) CGRect toFrame;
@property(assign, nonatomic) int sectionIndex;
@property(assign, nonatomic) float floating;
@property(copy, nonatomic) NSString* title;
@property(assign, nonatomic) __weak id<WADateBubbleViewDelegate> delegate;
+(float)preferredHeight;
-(void).cxx_destruct;
-(id)accessibilityValue;
-(CGRect)accessibilityFrame;
-(BOOL)isAccessibilityElement;
-(void)fadeOutIfNeededWithAnimation:(BOOL)animation;
-(void)fadeInWithAnimation:(BOOL)animation;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
@end

