/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WAStaticTableViewController.h"

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface WADebugSpotlightViewController : WAStaticTableViewController {
	NSMutableDictionary* _chatSessionRowsDictionary;
	NSMutableDictionary* _phoneRowsDictionary;
	NSMutableDictionary* _messageRowsDictionary;
}
-(void).cxx_destruct;
-(id)titleForSpotlightStatus:(int)spotlightStatus;
-(id)addSectionWithTitle:(id)title includingNotIndexable:(BOOL)indexable;
-(void)populateRowsInDictionary:(id)dictionary entityName:(id)name context:(id)context;
-(void)setupTableView;
-(void)reloadTable;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

