/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class _WADirectionsButtonContentView;

@interface WADirectionsButton : _ABAddressBookCopyArrayOfAllGroups
{
    _WADirectionsButtonContentView *_contentView;
    double _expectedTravelTime;
}

+ (id)stringFromTimeInterval:(double)fp8;
+ (id)button;
- (double)expectedTravelTime;
- (void).cxx_destruct;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)setExpectedTravelTime:(double)fp8;
- (void)configureForLegacyOS;
- (void)configureWithETA;
- (void)configure;
- (void)layoutSubviews;

@end

