/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIBarButtonItem.h>


__attribute__((visibility("hidden")))
@interface WADoneWithSpinnerBarButtonItem : UIBarButtonItem {
	unsigned _buttonStyle;
}
@property(assign, nonatomic) unsigned buttonStyle;
@property(assign, nonatomic) BOOL spinnerHidden;
+(id)buttonWithTarget:(id)target action:(SEL)action;
-(void)done:(id)done;
-(void)sizeToFit;
-(id)initWithTitle:(id)title;
-(id)initWithCoder:(id)coder;
-(id)init;
@end

