/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import "WAMessageHelper.h"


__attribute__((visibility("hidden")))
@interface WADocumentMessageHelper : WAMessageHelper {
}
+(id)stringRepresentationForNotificationForMessage:(id)message;
+(id)stringRepresentationForChatForMessage:(id)message;
+(id)stringRepresentationForMessage:(id)message;
+(CGSize)preferredXMPPThumbnailSizeWithSourceImageSize:(CGSize)sourceImageSize;
+(BOOL)needsImageLoader;
-(id)activitySubjectForActivityType:(id)activityType;
-(id)activityItemForActivityType:(id)activityType;
-(id)activityPlaceholderItem;
-(id)largeImageForMessageImageLoaderWithInfo:(id)info;
-(id)smallImageForMessageImageLoaderWithInfo:(id)info;
-(BOOL)shouldCacheLargeTransformedImage:(id)image fromOriginalImage:(id)originalImage info:(id)info;
-(id)newImageLoader;
-(void)storeOutgoingMedia:(id)media completion:(id)completion;
-(id)dataFromXMPPThumbnailImage:(id)xmppthumbnailImage;
@end

