/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAE2eMessage.h"

@interface WAE2eMessageV1 : WAE2eMessage
{
}

- (void)setDecryptedData:(id)fp8;
- (id)dataToEncrypt;
- (int)version;

@end

