/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class NSData, NSMutableArray, NSString;

@interface WAE2eMessage : _ABAddressBookCopyArrayOfAllGroups
{
    NSString *_jid;
    NSString *_participant;
    NSString *_stanzaId;
    NSString *_conversation;
    NSData *_encryptedData;
    int _ciphertextMessageType;
    NSMutableArray *_participantMessages;
    NSString *_phash;
}

- (void)setPhash:(id)fp8;
- (id)phash;
- (void)setParticipantMessages:(id)fp8;
- (id)participantMessages;
- (void)setCiphertextMessageType:(int)fp8;
- (int)ciphertextMessageType;
- (void)setEncryptedData:(id)fp8;
- (id)encryptedData;
- (void)setConversation:(id)fp8;
- (id)conversation;
- (void)setStanzaId:(id)fp8;
- (id)stanzaId;
- (void)setParticipant:(id)fp8;
- (id)participant;
- (void)setJid:(id)fp8;
- (id)jid;
- (void).cxx_destruct;
- (void)setDecryptedData:(id)fp8;
- (id)dataToEncrypt;
- (int)version;
- (long long)recipientId;
- (long long)recepientIdForJid:(id)fp8;
- (id)initWithJID:(id)fp8 participant:(id)fp12 stanzaId:(id)fp16;
- (id)initForMessage:(id)fp8;

@end

