/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol WAEditableImageScrollViewEditingDelegate <NSObject>
- (void)editableImageScrollViewDidEndUserScrolling:(id)fp8;
- (void)editableImageScrollViewDidScroll:(id)fp8;
- (void)editableImageScrollViewDidBeginUserScrolling:(id)fp8;
- (void)editableImageScrollViewDidEndZooming:(id)fp8 withView:(id)fp12 atScale:(float)fp16;
- (void)editableImageScrollViewWillBeginZooming:(id)fp8 withView:(id)fp12;
@end

