/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

#import "WAEditableImageRotationToolDelegate-Protocol.h"
#import "WAEditableImageScrollViewEditingDelegate-Protocol.h"
#import "WAImageCropToolViewDelegate-Protocol.h"

@class CAShapeLayer, UIButton, UIImageView, UIView, UIVisualEffectView, WAEditableImageRotationTool, WAEditableImageScrollView, WAImageCropToolView, WAMultiSendMediaItem;

@interface WAEditableImageEditingView : _ABAddressBookCopyArrayOfAllGroups <WAEditableImageRotationToolDelegate, WAEditableImageScrollViewEditingDelegate, WAImageCropToolViewDelegate>
{
    WAEditableImageScrollView *_scrollView;
    UIImageView *_renderedImageView;
    WAImageCropToolView *_cropToolView;
    WAEditableImageRotationTool *_rotationTool;
    unsigned int _deferredRenderingCounter;
    UIButton *_resetButton;
    UIButton *_aspectRatioButton;
    BOOL _suppressRotationToolUpdates;
    unsigned int _suppressLayoutCounter;
    BOOL _isCropRectSmallerThanCropArea;
    BOOL _snapToMinZoomScale;
    UIVisualEffectView *_blurEffectView;
    CAShapeLayer *_blurEffectMask;
    unsigned int _hideBlurCounter;
    struct CGRect _initialCropRect;
    struct CGSize _initialCropSize;
    struct CGSize _lastLayoutSize;
    UIView *_bottomAreaTouchBlocker;
    BOOL _allowsRotation;
    WAMultiSendMediaItem *_item;
    id <WAEditableImageEditingViewDelegate> _delegate;
    double _aspectRatio;
    struct UIEdgeInsets _contentInset;
}

- (double)aspectRatio;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (BOOL)allowsRotation;
- (struct UIEdgeInsets)contentInset;
- (id)item;
- (void).cxx_destruct;
- (void)animateCropAreaToFillBounds;
- (void)imageCropToolViewCropRectDidFinishChanging:(id)fp8;
- (void)imageCropToolViewCropRectDidChange:(id)fp8;
- (void)imageCropToolViewCropRectWillBeginChanging:(id)fp8;
- (void)editableImageScrollViewDidEndUserScrolling:(id)fp8;
- (void)editableImageScrollViewDidScroll:(id)fp8;
- (void)editableImageScrollViewDidBeginUserScrolling:(id)fp8;
- (void)editableImageScrollViewDidEndZooming:(id)fp8 withView:(id)fp12 atScale:(float)fp16;
- (void)editableImageScrollViewWillBeginZooming:(id)fp8 withView:(id)fp12;
- (void)editableImageRotationToolDidEndChangingAngle:(id)fp8;
- (void)editableImageRotationToolDidChangeAngle:(id)fp8;
- (void)editableImageRotationToolDidBeginChangingAngle:(id)fp8;
- (void)presentAspectRatioOptions;
- (void)setAspectRatio:(double)fp8;
- (void)aspectRatioButtonTapped:(id)fp8;
- (void)stopHidingBlur;
- (void)beginHidingBlur;
- (void)animateOutWithImageView:(id)fp8 completion:(id)fp(null);
- (void)animateInWithImageView:(id)fp8 completion:(id)fp(null);
- (void)endDeferredRendering;
- (void)beginDeferredRendering;
- (void)resetTransform:(id)fp8;
- (void)animateToTransformInfo:(CDAnonymousStruct18)fp8;
- (void)prepareToCancelCropping;
- (void)setItem:(id)fp8;
- (void)reloadImagesFromCurrentItem;
- (void)setContentInset:(struct UIEdgeInsets)fp8;
- (CDAnonymousStruct18)updateAnchorPoint:(struct CGPoint)fp8 cropSize:(struct CGSize)fp16 ofTransformInfo:(CDAnonymousStruct18)fp24;
- (void)updateAnchorPointAndCropSizeFromInterface;
- (void)relayout;
- (void)updateResetButton;
- (void)updateCropToolViewLimits;
- (void)layoutSubviews;
- (void)setAllowsRotation:(BOOL)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

