/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAViewController.h"

@class UIButton, UIImageView, UILabel;

@interface WAExpiredBuildNotificationViewController : WAViewController
{
    UIImageView *_iconImageView;
    UILabel *_primaryLabel;
    UIButton *_appStoreButton;
    UILabel *_footerLabel;
}

- (void)setFooterLabel:(id)fp8;
- (id)footerLabel;
- (void)setAppStoreButton:(id)fp8;
- (id)appStoreButton;
- (void)setPrimaryLabel:(id)fp8;
- (id)primaryLabel;
- (void)setIconImageView:(id)fp8;
- (id)iconImageView;
- (void).cxx_destruct;
- (void)openAppStore:(id)fp8;
- (unsigned int)supportedInterfaceOrientations;
- (void)updateLayout;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

@end

