/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WAFieldStatsEvent.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface WAFieldStatsEventRegCode : WAFieldStatsEvent {
	NSString* _app_version;
	NSString* _device_name;
	NSString* _os_version;
	NSString* _location_code;
	NSString* _language_code;
	double _platform;
	double _mcc;
	double _mnc;
	double _network_radio_type;
	double _reg_asn;
	double _reg_provider;
	double _reg_provider_type;
	double _reg_status;
	double _reg_is_new;
	double _reg_bucket;
	double _reg_entered;
	double _reg_simnum;
	double _reg_copiedrc;
	double _reg_hasinrc;
	double _reg_rcmatch;
	double _reg_sms_count;
	double _reg_self_count;
	double _reg_voice_count;
	double _reg_mistyped;
	double _reg_cost;
}
@property(assign, nonatomic) double reg_cost;
@property(assign, nonatomic) double reg_mistyped;
@property(assign, nonatomic) double reg_voice_count;
@property(assign, nonatomic) double reg_self_count;
@property(assign, nonatomic) double reg_sms_count;
@property(assign, nonatomic) double reg_rcmatch;
@property(assign, nonatomic) double reg_hasinrc;
@property(assign, nonatomic) double reg_copiedrc;
@property(assign, nonatomic) double reg_simnum;
@property(assign, nonatomic) double reg_entered;
@property(assign, nonatomic) double reg_bucket;
@property(assign, nonatomic) double reg_is_new;
@property(assign, nonatomic) double reg_status;
@property(assign, nonatomic) double reg_provider_type;
@property(assign, nonatomic) double reg_provider;
@property(retain, nonatomic) NSString* language_code;
@property(retain, nonatomic) NSString* location_code;
@property(assign, nonatomic) double reg_asn;
@property(assign, nonatomic) double network_radio_type;
@property(assign, nonatomic) double mnc;
@property(assign, nonatomic) double mcc;
@property(retain, nonatomic) NSString* os_version;
@property(retain, nonatomic) NSString* device_name;
@property(retain, nonatomic) NSString* app_version;
@property(assign, nonatomic) double platform;
-(void).cxx_destruct;
-(void)submit;
-(id)init;
@end

