/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WAFieldStatsEvent.h"


__attribute__((visibility("hidden")))
@interface WAFieldStatsEventChatConnection : WAFieldStatsEvent {
	double _chat_port;
	double _chat_state;
	double _chat_socket_connect_t;
	double _chat_login_t;
	double _chat_post_login_t;
	double _chat_connected_t;
}
@property(assign, nonatomic) double chat_connected_t;
@property(assign, nonatomic) double chat_post_login_t;
@property(assign, nonatomic) double chat_login_t;
@property(assign, nonatomic) double chat_socket_connect_t;
@property(assign, nonatomic) double chat_state;
@property(assign, nonatomic) double chat_port;
-(void)submit;
-(id)init;
@end

