/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAFieldStatsEvent.h"

@class NSString;

@interface WAFieldStatsEventCdbRegeneration : WAFieldStatsEvent
{
    NSString *_s40_cdb_name;
    double _s40_cdb_file_size;
    double _s40_cdb_journal_file_size;
    double _s40_cdb_regenerate_t;
}

- (void)setS40_cdb_regenerate_t:(double)fp8;
- (double)s40_cdb_regenerate_t;
- (void)setS40_cdb_journal_file_size:(double)fp8;
- (double)s40_cdb_journal_file_size;
- (void)setS40_cdb_file_size:(double)fp8;
- (double)s40_cdb_file_size;
- (void)setS40_cdb_name:(id)fp8;
- (id)s40_cdb_name;
- (void).cxx_destruct;
- (void)submit;
- (id)init;

@end

