/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WAFieldStatsEvent.h"


__attribute__((visibility("hidden")))
@interface WAFieldStatsEventProfilePicUpload : WAFieldStatsEvent {
	double _profile_pic_upload_result;
	double _retry_count;
	double _profile_pic_upload_t;
	double _profile_pic_size;
}
@property(assign, nonatomic) double profile_pic_size;
@property(assign, nonatomic) double profile_pic_upload_t;
@property(assign, nonatomic) double retry_count;
@property(assign, nonatomic) double profile_pic_upload_result;
-(void)submit;
-(id)init;
@end

