/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAFieldStatsEvent.h"

@class NSString;

@interface WAFieldStatsEventWebcResourceLoad : WAFieldStatsEvent
{
    NSString *_webc_resource_name;
    double _webc_resource_cached;
    double _webc_resource_duration;
}

- (void)setWebc_resource_duration:(double)fp8;
- (double)webc_resource_duration;
- (void)setWebc_resource_cached:(double)fp8;
- (double)webc_resource_cached;
- (void)setWebc_resource_name:(id)fp8;
- (id)webc_resource_name;
- (void).cxx_destruct;
- (void)submit;
- (id)init;

@end

