/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import </libobjc.A.h>

@class NSMutableArray;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface WAFieldStats : NSObject {
	sFILE* _file;
	long _fileOffset;
	int _recordCount;
	unsigned _timestamp;
	int _missedUpdateCount;
	BOOL _rotatedExists;
	BOOL _isInsideEvent;
	BOOL _isNew;
	NSMutableArray* _cachedRecords;
	NSObject<OS_dispatch_queue>* _queue;
}
+(id)sharedManager;
-(void).cxx_destruct;
-(void)preCacheKnownDimensions;
-(BOOL)addRecordToCache:(id)cache;
-(id)findCachedRecord:(int)record uniqueId:(unsigned)anId;
-(BOOL)rotateFile;
-(void)appendRecord:(id)record;
-(void)postWrite;
-(BOOL)preWrite:(id)write;
-(int)writeRecord:(id)record;
-(int)writeRecord:(id)record offset:(long)offset;
-(void)closeFieldStatsFile;
-(BOOL)openFieldStatsFile;
-(BOOL)createFile;
-(BOOL)openFile;
-(int)readRecordFromFile:(sFILE*)file record:(out id*)record;
-(id)rotatedFileName;
-(id)fileName;
-(id)fieldStatsDirectory;
-(BOOL)isFileExists:(id)exists;
-(unsigned)unixTimestamp;
-(void)numericRecord:(unsigned)record type:(int)type value:(double)value;
-(void)stringRecord:(unsigned)record stringValue:(id)value;
-(double)qNaN;
-(void)event:(int)event records:(id)records;
-(void)metric:(int)metric timer:(double)timer;
-(void)metric:(int)metric gauge:(double)gauge;
-(void)metric:(int)metric increment:(int)increment;
-(void)clearNumericDimension:(int)dimension;
-(void)clearStringDimension:(int)dimension;
-(void)dimension:(int)dimension numericValue:(double)value;
-(void)dimension:(int)dimension stringValue:(id)value;
-(void)clearStatsData;
-(id)statsData;
-(void)rotateFieldstatsFileAndUpload;
-(BOOL)isReadyToSend;
-(id)init;
@end

