/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WABackupOperation.h"

@class WAActionManager;

@interface WAFinishOperation : WABackupOperation
{
    WAActionManager *_manager;
    unsigned int _code;
}

- (void)setCode:(unsigned int)fp8;
- (unsigned int)code;
- (void).cxx_destruct;
- (void)run;
- (id)initWithActionManager:(id)fp8 code:(unsigned int)fp12;
- (id)initWithDependenciesRequired:(BOOL)fp8;

@end

