/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WAFieldStatsEvent.h"


__attribute__((visibility("hidden")))
@interface WAFieldStatsEventChatdAckedRetries : WAFieldStatsEvent {
	double _test_bucket;
	double _chatd_acked_retry_count;
	double _chatd_acked_time;
}
@property(assign, nonatomic) double chatd_acked_time;
@property(assign, nonatomic) double chatd_acked_retry_count;
@property(assign, nonatomic) double test_bucket;
-(void)submit;
-(id)init;
@end

