/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAFieldStatsEvent.h"

@interface WAFieldStatsEventChatdAckedRetries : WAFieldStatsEvent
{
    double _test_bucket;
    double _chatd_acked_retry_count;
    double _chatd_acked_time;
}

- (void)setChatd_acked_time:(double)fp8;
- (double)chatd_acked_time;
- (void)setChatd_acked_retry_count:(double)fp8;
- (double)chatd_acked_retry_count;
- (void)setTest_bucket:(double)fp8;
- (double)test_bucket;
- (void)submit;
- (id)init;

@end

