/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WAFieldStatsEvent.h"


__attribute__((visibility("hidden")))
@interface WAFieldStatsEventGroupMute : WAFieldStatsEvent {
	double _group_size;
	double _group_mute_t;
}
@property(assign, nonatomic) double group_mute_t;
@property(assign, nonatomic) double group_size;
-(void)submit;
-(id)init;
@end

