/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAFieldStatsEvent.h"

@interface WAFieldStatsEventPushReceive : WAFieldStatsEvent
{
    double _push_receive_while_offline;
    double _push_receive_delay_t;
    double _network_change_delay_t;
}

- (void)setNetwork_change_delay_t:(double)fp8;
- (double)network_change_delay_t;
- (void)setPush_receive_delay_t:(double)fp8;
- (double)push_receive_delay_t;
- (void)setPush_receive_while_offline:(double)fp8;
- (double)push_receive_while_offline;
- (void)submit;
- (id)init;

@end

