/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAFieldStatsEvent.h"

@class NSString;

@interface WAFieldStatsEventLocationPicker : WAFieldStatsEvent
{
    NSString *_location_picker_failure_description;
    NSString *_location_picker_query_string;
    double _location_picker_places_source;
    double _location_picker_places_source_default;
    double _location_picker_result_type;
    double _location_picker_places_response;
    double _location_picker_full_screen;
    double _location_picker_requests_count;
    double _location_picker_places_count;
    double _location_picker_selected_place_index;
    double _location_picker_spend_t;
}

- (void)setLocation_picker_spend_t:(double)fp8;
- (double)location_picker_spend_t;
- (void)setLocation_picker_selected_place_index:(double)fp8;
- (double)location_picker_selected_place_index;
- (void)setLocation_picker_places_count:(double)fp8;
- (double)location_picker_places_count;
- (void)setLocation_picker_requests_count:(double)fp8;
- (double)location_picker_requests_count;
- (void)setLocation_picker_query_string:(id)fp8;
- (id)location_picker_query_string;
- (void)setLocation_picker_full_screen:(double)fp8;
- (double)location_picker_full_screen;
- (void)setLocation_picker_failure_description:(id)fp8;
- (id)location_picker_failure_description;
- (void)setLocation_picker_places_response:(double)fp8;
- (double)location_picker_places_response;
- (void)setLocation_picker_result_type:(double)fp8;
- (double)location_picker_result_type;
- (void)setLocation_picker_places_source_default:(double)fp8;
- (double)location_picker_places_source_default;
- (void)setLocation_picker_places_source:(double)fp8;
- (double)location_picker_places_source;
- (void).cxx_destruct;
- (void)submit;
- (id)init;

@end

