/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WAFieldStatsEvent.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface WAFieldStatsEventWebcResourceLoad : WAFieldStatsEvent {
	NSString* _webc_resource_name;
	double _webc_resource_cached;
	double _webc_resource_duration;
}
@property(assign, nonatomic) double webc_resource_duration;
@property(assign, nonatomic) double webc_resource_cached;
@property(retain, nonatomic) NSString* webc_resource_name;
-(void).cxx_destruct;
-(void)submit;
-(id)init;
@end

