/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


__attribute__((visibility("hidden")))
@interface WAFieldStatsEventChatConnectionProbe : NSObject {
	double _startTime;
	double _completionTime;
	double _connectionEstablishedTime;
	int _port;
	unsigned _state;
}
@property(assign, nonatomic) unsigned state;
@property(assign, nonatomic) int port;
-(void)submitEvent;
-(BOOL)canTransitionToState:(unsigned)state;
-(id)init;
@end

