/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WAFieldStatsEvent.h"


__attribute__((visibility("hidden")))
@interface WAFieldStatsEventMediaDownload : WAFieldStatsEvent {
	double _media_type;
	double _media_download_result;
	double _retry_count;
	double _media_used_cdn;
	double _e2e_media_encryption;
	double _media_download_t;
	double _media_size;
}
@property(assign, nonatomic) double media_size;
@property(assign, nonatomic) double media_download_t;
@property(assign, nonatomic) double e2e_media_encryption;
@property(assign, nonatomic) double media_used_cdn;
@property(assign, nonatomic) double retry_count;
@property(assign, nonatomic) double media_download_result;
@property(assign, nonatomic) double media_type;
-(void)submit;
-(id)init;
@end

