/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@interface WAFileUtilities : _ABAddressBookCopyArrayOfAllGroups
{
}

+ (void)logFilesRecursivelyAtDirectoryURL:(id)fp8;
+ (void)showTemporaryFilesWithCompletionHandler:(id)fp(null);
+ (void)initialize;

@end

