/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WAFieldStatsEvent.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface WAFieldStatsEventTest : WAFieldStatsEvent {
	NSString* _language_code;
	NSString* _location_code;
	NSString* _device_name;
	NSString* _os_version;
	NSString* _app_version;
	double _mcc;
	double _mnc;
	double _platform;
	double _test_gauge;
	double _test_timer;
}
@property(assign, nonatomic) double test_timer;
@property(assign, nonatomic) double test_gauge;
@property(retain, nonatomic) NSString* app_version;
@property(retain, nonatomic) NSString* os_version;
@property(retain, nonatomic) NSString* device_name;
@property(retain, nonatomic) NSString* location_code;
@property(retain, nonatomic) NSString* language_code;
@property(assign, nonatomic) double platform;
@property(assign, nonatomic) double mnc;
@property(assign, nonatomic) double mcc;
-(void).cxx_destruct;
-(void)submit;
-(id)init;
@end

