/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAFieldStatsEvent.h"

@interface WAFieldStatsEventFsBuffer : WAFieldStatsEvent
{
    double _fs_buffer_error;
    double _client_ts;
    double _fs_buffer_size;
    double _fs_num_metrics;
    double _fs_num_dimensions;
    double _fs_buffer_age;
    double _fs_client_time_skew;
    double _fs_time_shift;
}

- (void)setFs_time_shift:(double)fp8;
- (double)fs_time_shift;
- (void)setFs_client_time_skew:(double)fp8;
- (double)fs_client_time_skew;
- (void)setFs_buffer_age:(double)fp8;
- (double)fs_buffer_age;
- (void)setFs_num_dimensions:(double)fp8;
- (double)fs_num_dimensions;
- (void)setFs_num_metrics:(double)fp8;
- (double)fs_num_metrics;
- (void)setFs_buffer_size:(double)fp8;
- (double)fs_buffer_size;
- (void)setClient_ts:(double)fp8;
- (double)client_ts;
- (void)setFs_buffer_error:(double)fp8;
- (double)fs_buffer_error;
- (void)submit;
- (id)init;

@end

