/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAFieldStatsEvent.h"

@interface WAFieldStatsEventICloudBackup : WAFieldStatsEvent
{
    double _icloud_backup_result;
    double _icloud_backup_age;
    double _icloud_backup_include_videos;
    double _icloud_t;
    double _icloud_chatdb_size;
    double _icloud_searchdb_size;
    double _icloud_calllog_size;
    double _icloud_media_tar_size;
    double _icloud_media_tar_t;
    double _icloud_thumb_tar_size;
    double _icloud_thumb_tar_t;
    double _icloud_media_tar_estimate;
    double _icloud_thumb_tar_estimate;
    double _icloud_video_tar_size;
    double _icloud_video_tar_estimate;
    double _icloud_video_tar_t;
}

- (void)setIcloud_video_tar_t:(double)fp8;
- (double)icloud_video_tar_t;
- (void)setIcloud_video_tar_estimate:(double)fp8;
- (double)icloud_video_tar_estimate;
- (void)setIcloud_video_tar_size:(double)fp8;
- (double)icloud_video_tar_size;
- (void)setIcloud_thumb_tar_estimate:(double)fp8;
- (double)icloud_thumb_tar_estimate;
- (void)setIcloud_media_tar_estimate:(double)fp8;
- (double)icloud_media_tar_estimate;
- (void)setIcloud_thumb_tar_t:(double)fp8;
- (double)icloud_thumb_tar_t;
- (void)setIcloud_thumb_tar_size:(double)fp8;
- (double)icloud_thumb_tar_size;
- (void)setIcloud_media_tar_t:(double)fp8;
- (double)icloud_media_tar_t;
- (void)setIcloud_media_tar_size:(double)fp8;
- (double)icloud_media_tar_size;
- (void)setIcloud_calllog_size:(double)fp8;
- (double)icloud_calllog_size;
- (void)setIcloud_searchdb_size:(double)fp8;
- (double)icloud_searchdb_size;
- (void)setIcloud_chatdb_size:(double)fp8;
- (double)icloud_chatdb_size;
- (void)setIcloud_t:(double)fp8;
- (double)icloud_t;
- (void)setIcloud_backup_include_videos:(double)fp8;
- (double)icloud_backup_include_videos;
- (void)setIcloud_backup_age:(double)fp8;
- (double)icloud_backup_age;
- (void)setIcloud_backup_result:(double)fp8;
- (double)icloud_backup_result;
- (void)submit;
- (id)init;

@end

