/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAFieldStatsEvent.h"

@interface WAFieldStatsEventRestore : WAFieldStatsEvent
{
    double _backup_restore_result;
    double _backup_restore_is_full;
    double _backup_restore_is_wifi;
    double _backup_restore_retry_count;
    double _backup_restore_include_videos;
    double _backup_restore_t;
    double _backup_restore_total_size;
    double _backup_restore_chatdb_size;
    double _backup_restore_media_size;
    double _backup_restore_transfer_size;
    double _backup_restore_transfer_failed_size;
    double _backup_restore_media_file_count;
    double _backup_restore_network_request_count;
}

- (void)setBackup_restore_network_request_count:(double)fp8;
- (double)backup_restore_network_request_count;
- (void)setBackup_restore_media_file_count:(double)fp8;
- (double)backup_restore_media_file_count;
- (void)setBackup_restore_transfer_failed_size:(double)fp8;
- (double)backup_restore_transfer_failed_size;
- (void)setBackup_restore_transfer_size:(double)fp8;
- (double)backup_restore_transfer_size;
- (void)setBackup_restore_media_size:(double)fp8;
- (double)backup_restore_media_size;
- (void)setBackup_restore_chatdb_size:(double)fp8;
- (double)backup_restore_chatdb_size;
- (void)setBackup_restore_total_size:(double)fp8;
- (double)backup_restore_total_size;
- (void)setBackup_restore_t:(double)fp8;
- (double)backup_restore_t;
- (void)setBackup_restore_include_videos:(double)fp8;
- (double)backup_restore_include_videos;
- (void)setBackup_restore_retry_count:(double)fp8;
- (double)backup_restore_retry_count;
- (void)setBackup_restore_is_wifi:(double)fp8;
- (double)backup_restore_is_wifi;
- (void)setBackup_restore_is_full:(double)fp8;
- (double)backup_restore_is_full;
- (void)setBackup_restore_result:(double)fp8;
- (double)backup_restore_result;
- (void)submit;
- (id)init;

@end

