/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAFieldStatsEvent.h"

@class NSString;

@interface WAFieldStatsEventRegCode : WAFieldStatsEvent
{
    NSString *_app_version;
    NSString *_device_name;
    NSString *_os_version;
    NSString *_location_code;
    NSString *_language_code;
    double _platform;
    double _mcc;
    double _mnc;
    double _network_radio_type;
    double _reg_asn;
    double _reg_provider;
    double _reg_provider_type;
    double _reg_status;
    double _reg_is_new;
    double _reg_bucket;
    double _reg_entered;
    double _reg_simnum;
    double _reg_copiedrc;
    double _reg_hasinrc;
    double _reg_rcmatch;
    double _reg_sms_count;
    double _reg_self_count;
    double _reg_voice_count;
    double _reg_mistyped;
    double _reg_cost;
}

- (void)setReg_cost:(double)fp8;
- (double)reg_cost;
- (void)setReg_mistyped:(double)fp8;
- (double)reg_mistyped;
- (void)setReg_voice_count:(double)fp8;
- (double)reg_voice_count;
- (void)setReg_self_count:(double)fp8;
- (double)reg_self_count;
- (void)setReg_sms_count:(double)fp8;
- (double)reg_sms_count;
- (void)setReg_rcmatch:(double)fp8;
- (double)reg_rcmatch;
- (void)setReg_hasinrc:(double)fp8;
- (double)reg_hasinrc;
- (void)setReg_copiedrc:(double)fp8;
- (double)reg_copiedrc;
- (void)setReg_simnum:(double)fp8;
- (double)reg_simnum;
- (void)setReg_entered:(double)fp8;
- (double)reg_entered;
- (void)setReg_bucket:(double)fp8;
- (double)reg_bucket;
- (void)setReg_is_new:(double)fp8;
- (double)reg_is_new;
- (void)setReg_status:(double)fp8;
- (double)reg_status;
- (void)setReg_provider_type:(double)fp8;
- (double)reg_provider_type;
- (void)setReg_provider:(double)fp8;
- (double)reg_provider;
- (void)setLanguage_code:(id)fp8;
- (id)language_code;
- (void)setLocation_code:(id)fp8;
- (id)location_code;
- (void)setReg_asn:(double)fp8;
- (double)reg_asn;
- (void)setNetwork_radio_type:(double)fp8;
- (double)network_radio_type;
- (void)setMnc:(double)fp8;
- (double)mnc;
- (void)setMcc:(double)fp8;
- (double)mcc;
- (void)setOs_version:(id)fp8;
- (id)os_version;
- (void)setDevice_name:(id)fp8;
- (id)device_name;
- (void)setApp_version:(id)fp8;
- (id)app_version;
- (void)setPlatform:(double)fp8;
- (double)platform;
- (void).cxx_destruct;
- (void)submit;
- (id)init;

@end

