/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAFieldStatsEvent.h"

@class NSString;

@interface WAFieldStatsEventRegCostEvent : WAFieldStatsEvent
{
    NSString *_app_version;
    NSString *_device_name;
    NSString *_os_version;
    double _platform;
    double _mcc;
    double _mnc;
    double _reg_provider;
    double _reg_provider_type;
    double _reg_bucket;
    double _reg_sms_count;
    double _reg_self_count;
    double _reg_voice_count;
    double _reg_cost;
}

- (void)setReg_cost:(double)fp8;
- (double)reg_cost;
- (void)setReg_voice_count:(double)fp8;
- (double)reg_voice_count;
- (void)setReg_self_count:(double)fp8;
- (double)reg_self_count;
- (void)setReg_sms_count:(double)fp8;
- (double)reg_sms_count;
- (void)setReg_bucket:(double)fp8;
- (double)reg_bucket;
- (void)setReg_provider_type:(double)fp8;
- (double)reg_provider_type;
- (void)setReg_provider:(double)fp8;
- (double)reg_provider;
- (void)setMnc:(double)fp8;
- (double)mnc;
- (void)setMcc:(double)fp8;
- (double)mcc;
- (void)setOs_version:(id)fp8;
- (id)os_version;
- (void)setDevice_name:(id)fp8;
- (id)device_name;
- (void)setApp_version:(id)fp8;
- (id)app_version;
- (void)setPlatform:(double)fp8;
- (double)platform;
- (void).cxx_destruct;
- (void)submit;
- (id)init;

@end

