/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITableViewDataSource.h"
#import "WhatsApp-Structs.h"
#import </libobjc.A.h>

@class NSString, NSArray;
@protocol WAForwardPickerDataSourceDelegate;

__attribute__((visibility("hidden")))
@interface WAForwardPickerDataSource : NSObject <UITableViewDataSource> {
	NSArray* _sections;
	int _totalCount;
	id<WAForwardPickerDataSourceDelegate> _delegate;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, copy, nonatomic) NSString* title;
@property(assign, nonatomic) __weak id<WAForwardPickerDataSourceDelegate> delegate;
@property(readonly, assign, nonatomic) UIEdgeInsets separatorInset;
@property(readonly, assign, nonatomic) BOOL showsEmptyListView;
@property(readonly, assign, nonatomic) BOOL allowsSearch;
@property(readonly, assign, nonatomic, getter=isLoaded) BOOL loaded;
@property(readonly, assign, nonatomic) int totalCount;
-(void).cxx_destruct;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(int)tableView:(id)view sectionForSectionIndexTitle:(id)sectionIndexTitle atIndex:(int)index;
-(id)sectionIndexTitlesForTableView:(id)tableView;
-(id)tableView:(id)view titleForHeaderInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)contactInfoAtIndexPath:(id)indexPath;
-(void)setNeedsReloadSections;
-(id)loadSections;
-(id)allContactInfos;
-(id)sections;
-(id)init;
@end

