/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WAContactsSearchControllerDelegate.h"
#import "WhatsApp-Structs.h"
#import "WAForwardPickerDataSource.h"

@class WAContactsSearchController, NSString, NSArray;

__attribute__((visibility("hidden")))
@interface WAForwardPickerSearchDataSource : WAForwardPickerDataSource <WAContactsSearchControllerDelegate> {
	WAContactsSearchController* _searchController;
	NSArray* _searchResults;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(void)contactsSearchControllerDelegateDidInvalidateSearchResults:(id)contactsSearchControllerDelegate;
-(void)updateSearchText:(id)text;
-(id)loadSections;
-(void)configureWithContactsFromDataSource:(id)dataSource;
-(BOOL)allowsSearch;
-(id)init;
@end

