/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UISearchDisplayDelegate.h"
#import "WATableViewController.h"
#import "WAForwardPickerDataSourceDelegate.h"

@class NSMutableDictionary, UISegmentedControl, NSArray, UIToolbar, NSString, WAForwardPickerSearchDataSource, _WAForwardPickerEmptyListView;
@protocol WAForwardPickerViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface WAForwardPickerViewController : WATableViewController <WAForwardPickerDataSourceDelegate, UISearchDisplayDelegate> {
	UISegmentedControl* _segmentedControl;
	NSArray* _dataSources;
	WAForwardPickerSearchDataSource* _searchDataSource;
	int _currentSourceType;
	NSMutableDictionary* _savedContentOffsets;
	BOOL _needsAdjustContentOffset;
	_WAForwardPickerEmptyListView* _emptyListView;
	UIToolbar* _toolbar;
	BOOL _requiresConfirmation;
	id _completionHandler;
	id<WAForwardPickerViewControllerDelegate> _delegate;
	NSArray* _requiredCapabilities;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSArray* requiredCapabilities;
@property(assign, nonatomic) __weak id<WAForwardPickerViewControllerDelegate> delegate;
@property(copy, nonatomic) id completionHandler;
@property(assign, nonatomic) BOOL requiresConfirmation;
+(id)controller;
-(void).cxx_destruct;
-(BOOL)shouldProceedWithContactInfo:(id)contactInfo;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view willSelectRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(void)forwardPickerSearchDataSourceDidChangeContent:(id)forwardPickerSearchDataSource;
-(BOOL)isSearchBarShownForForwardPickerDataSource:(id)forwardPickerDataSource;
-(BOOL)shouldShowSearchBar;
-(void)searchWithCriteria:(id)criteria;
-(void)searchDisplayControllerWillEndSearch:(id)searchDisplayController;
-(void)searchDisplayControllerWillBeginSearch:(id)searchDisplayController;
-(BOOL)searchDisplayController:(id)controller shouldReloadTableForSearchString:(id)searchString;
-(id)confirmationTextForContactInfo:(id)contactInfo;
-(id)currentDataSource;
-(void)updateViewForCurrentSource;
-(void)setDataSourceType:(int)type;
-(void)segmentedControlDidChange:(id)segmentedControl;
-(void)cancel:(id)cancel;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)wa_fontSizeDidChange;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidLayoutSubviews;
-(void)viewDidLoad;
-(void)awakeFromNib;
@end

