/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WATableViewController.h"

#import "UISearchDisplayDelegate-Protocol.h"
#import "WAForwardPickerDataSourceDelegate-Protocol.h"

@class NSArray, NSMutableDictionary, UISegmentedControl, UIToolbar, WAForwardPickerSearchDataSource, _WAForwardPickerEmptyListView;

@interface WAForwardPickerViewController : WATableViewController <WAForwardPickerDataSourceDelegate, UISearchDisplayDelegate>
{
    UISegmentedControl *_segmentedControl;
    NSArray *_dataSources;
    WAForwardPickerSearchDataSource *_searchDataSource;
    int _currentSourceType;
    NSMutableDictionary *_savedContentOffsets;
    BOOL _needsAdjustContentOffset;
    _WAForwardPickerEmptyListView *_emptyListView;
    UIToolbar *_toolbar;
    BOOL _requiresConfirmation;
    id _completionHandler;
    id <WAForwardPickerViewControllerDelegate> _delegate;
}

+ (id)controller;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setCompletionHandler:(id)fp(null);
- (id)completionHandler;
- (void)setRequiresConfirmation:(BOOL)fp8;
- (BOOL)requiresConfirmation;
- (void).cxx_destruct;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 willSelectRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForHeaderInSection:(int)fp12;
- (void)forwardPickerSearchDataSourceDidChangeContent:(id)fp8;
- (BOOL)isSearchBarShownForForwardPickerDataSource:(id)fp8;
- (BOOL)shouldShowSearchBar;
- (void)searchWithCriteria:(id)fp8;
- (void)searchDisplayControllerWillEndSearch:(id)fp8;
- (void)searchDisplayControllerWillBeginSearch:(id)fp8;
- (BOOL)searchDisplayController:(id)fp8 shouldReloadTableForSearchString:(id)fp12;
- (id)confirmationTextForContactInfo:(id)fp8;
- (id)currentDataSource;
- (void)updateViewForCurrentSource;
- (void)setDataSourceType:(int)fp8;
- (void)segmentedControlDidChange:(id)fp8;
- (void)cancel:(id)fp8;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)wa_fontSizeDidChange;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)awakeFromNib;

@end

