/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <CoreData/NSManagedObject.h>

@class NSString, NSNumber, NSDate, WAGroupMember, WAChatSession;

__attribute__((visibility("hidden")))
@interface WAGroupInfo : NSManagedObject {
}
@property(retain, nonatomic) NSNumber* state;
@property(retain, nonatomic) WAGroupMember* lastMessageOwner;
@property(retain, nonatomic) NSDate* subjectTimestamp;
@property(retain, nonatomic) NSString* subjectOwnerJID;
@property(retain, nonatomic) NSString* picturePath;
@property(retain, nonatomic) NSString* pictureID;
@property(retain, nonatomic) WAChatSession* chatSession;
@property(retain, nonatomic) NSString* creatorJID;
@property(retain, nonatomic) NSDate* creationDate;
@property(retain, nonatomic) NSString* sourceJID;
@end

