/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WABasicCameraViewController.h"
#import "WAForwardPickerViewControllerDelegate.h"
#import "WhatsApp-Structs.h"

@class NSString, WADropDownAlertView, NSData, UIImageView, WAShapeView, WAE2eFingerprint, WACircularProgressView, _WAQRCodeScanResultView, _WAVerificationCodeView, UIView, UIButton, WATimer, WAConversationHeaderView, UITapGestureRecognizer;

__attribute__((visibility("hidden")))
@interface WAIdentityVerificationViewController : WABasicCameraViewController <WAForwardPickerViewControllerDelegate> {
	WAConversationHeaderView* _titleView;
	UIView* _qrCodeContainer;
	UIImageView* _qrCodeImageView;
	_WAQRCodeScanResultView* _qrCodeScanResultView;
	WATimer* _removeQRCodeScanResultTimer;
	UIView* _verificationCodeContainer;
	UIButton* _scanCodeButton;
	_WAVerificationCodeView* _verificationCodeView;
	BOOL _cameraVisible;
	BOOL _qrCodeScanResultVisible;
	BOOL _suppressLayoutOfCameraPreview;
	UITapGestureRecognizer* _qrCodeTapGesture;
	WAShapeView* _maskView;
	WAShapeView* _cameraViewfinder;
	WACircularProgressView* _qrCodeScanProgressView;
	float _viewfinderRadius;
	WADropDownAlertView* _incorrectLocalNumberAlert;
	WADropDownAlertView* _incorrectRemoteNumberAlert;
	NSString* _jid;
	NSString* _verificationCode;
	NSData* _lastQRCode;
	WAE2eFingerprint* _fingerprint;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) WAE2eFingerprint* fingerprint;
@property(copy, nonatomic) NSData* lastQRCode;
@property(copy, nonatomic) NSString* verificationCode;
@property(copy, nonatomic) NSString* jid;
+(BOOL)startCameraAutomatically;
+(BOOL)statusBarHidden;
+(int)cameraMode;
+(id)dataFromQRCodeData:(id)qrcodeData;
+(id)controllerForJID:(id)jid;
+(BOOL)canPresentIdentifyVerificationScreenForJID:(id)jid fromViewController:(id)viewController;
-(void).cxx_destruct;
-(id)forwardPicker:(id)picker confirmationButtonTitleForContactInfo:(id)contactInfo;
-(id)forwardPicker:(id)picker confirmationTextForContactInfo:(id)contactInfo;
-(BOOL)forwardPicker:(id)picker shouldProceedWithContactInfo:(id)contactInfo;
-(void)forwardPickerDidCancel:(id)forwardPicker;
-(void)forwardPicker:(id)picker didSelectContactInfo:(id)info;
-(void)shareCodeAction:(id)action;
-(void)removeQRCodeScanResultViewAnimated:(BOOL)animated;
-(void)animateLastPartOfQRCodeScanResult:(BOOL)qrcodeScanResult;
-(void)animateQRCodeScanResult:(BOOL)result;
-(void)setCameraVisible:(BOOL)visible animated:(BOOL)animated completion:(id)completion;
-(void)handleTapToFocus:(id)focus;
-(void)cameraController:(id)controller didDetectQRCode:(id)code;
-(void)cameraControllerSessionDidBeginRunning:(id)cameraControllerSession;
-(void)didCreateCameraController;
-(void)scanCodeAction:(id)action;
-(void)handleQRCodeTap:(id)tap;
-(id)formattedVerificationCodeSplittingLines:(BOOL)lines;
-(void)layoutVerificationCodeText;
-(void)updateTitleViewToCurrentInterfaceOrientation;
-(void)wa_fontSizeDidChange;
-(void)wa_applicationDidEnterBackground;
-(void)deviceOrientationDidChangeWithAnimation:(BOOL)deviceOrientation;
-(BOOL)shouldAutorotate;
-(void)viewDidLayoutSubviews;
-(void)viewDidLoad;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

