/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol WAImageToImageTransitioning <NSObject>
- (void)finishTransitionWithView:(id)fp8 context:(id)fp12;
- (id)viewForTransitionAnimationWithContext:(id)fp8;
- (void)prepareForTransitionWithContext:(id)fp8;
- (BOOL)shouldUseImageToImageTransitionForOperation:(int)fp8 fromViewController:(id)fp12 toViewController:(id)fp16 context:(id)fp20;
@end

