/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIPanGestureRecognizer.h>

@class UIViewController;
@protocol WAImageToImagePanPopGestureRecognizerDelegate;

__attribute__((visibility("hidden")))
@interface WAImageToImagePanPopGestureRecognizer : UIPanGestureRecognizer {
	UIViewController* _parentViewController;
	int _transitionState;
}
@property(assign, nonatomic) id<WAImageToImagePanPopGestureRecognizerDelegate> delegate;
-(void).cxx_destruct;
-(void)handleGestureRecognizer:(id)recognizer;
-(id)initWithParentViewController:(id)parentViewController;
@end

