/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import <UIKit/UIView.h>
#import "WAImageAttachmentViewDelegate.h"

@class NSArray, NSMutableArray, NSString, UIScrollView;
@protocol WAImageAttachmentContainerViewDelegate;

__attribute__((visibility("hidden")))
@interface WAImageAttachmentContainerView : UIView <WAImageAttachmentViewDelegate> {
	UIScrollView* _scrollView;
	NSMutableArray* _attachments;
	BOOL _removeButtonsHidden;
	id<WAImageAttachmentContainerViewDelegate> _delegate;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL removeButtonsHidden;
@property(readonly, assign, nonatomic) NSArray* attachedImages;
@property(assign, nonatomic) __weak id<WAImageAttachmentContainerViewDelegate> delegate;
-(void).cxx_destruct;
-(void)imageAttachmentViewDidRequestAddImage:(id)imageAttachmentView;
-(void)imageAttachmentViewDidRequestRemoveImage:(id)imageAttachmentView;
-(void)attachImage:(id)image;
-(void)addAttachment:(id)attachment;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
@end

