/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAStaticTableViewController.h"

@class UISwitch, WATableRow;

@interface WAInAppNotificationsViewController : WAStaticTableViewController
{
    UISwitch *_switchInAppVibrate;
    UISwitch *_switchInAppSounds;
    WATableRow *_rowInAppAlerts;
}

+ (id)controller;
- (void).cxx_destruct;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (void)inAppSoundsAction:(id)fp8;
- (void)inAppVibrateAction:(id)fp8;
- (void)reloadData;
- (void)setupTableView;
- (void)viewDidLoad;
- (id)init;

@end

