/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WATableViewController.h"
#import "WAContactInfoEditCellDelegate.h"
#import "LabelPickerViewControllerDelegate.h"

@class NSString, WAContactInfoNameUnit, WAContactInfoEditCell, WAContactInfoPhotoUnit, WAContactInfoTableHeaderView;
@protocol WAInfoInputViewControllerDelegate;

@interface WAInfoInputViewController : WATableViewController <WAContactInfoEditCellDelegate, LabelPickerViewControllerDelegate> {
	WAContactInfoNameUnit* _contactNameUnit;
	WAContactInfoPhotoUnit* _contactPhotoUnit;
	WAContactInfoTableHeaderView* _tableHeader;
	WAContactInfoEditCell* _textFieldCell;
	id<WAInfoInputViewControllerDelegate> _delegate;
	void* _displayedPerson;
	int _propertyType;
	NSString* _propertyValue;
	NSString* _labelValue;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(copy, nonatomic) NSString* labelValue;
@property(copy, nonatomic) NSString* propertyValue;
@property(assign, nonatomic) int propertyType;
@property(assign, nonatomic) void* displayedPerson;
@property(assign, nonatomic) __weak id<WAInfoInputViewControllerDelegate> delegate;
-(void).cxx_destruct;
-(void)labelPickerViewController:(id)controller didSelectLabel:(id)label;
-(void)labelPickerViewControllerDidCancel:(id)labelPickerViewController;
-(void)labelButtonTappedInCell:(id)cell;
-(int)tableView:(id)view editingStyleForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)presentLabelPicker;
-(void)textFieldValueChanged:(id)changed;
-(void)saveAction:(id)action;
-(void)cancelAction:(id)action;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)validateUserInput;
-(void)dealloc;
-(id)init;
-(id)initWithDelegate:(id)delegate;
@end

