/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

#import "NSSecureCoding-Protocol.h"

@class NSString;

@interface WAInetAddress : _ABAddressBookCopyArrayOfAllGroups <NSSecureCoding>
{
    unsigned char _family;
    NSString *_ip;
}

+ (BOOL)supportsSecureCoding;
- (unsigned char)family;
- (id)ip;
- (void).cxx_destruct;
- (id)description;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)socketAddressForPort:(unsigned short)fp8;
- (id)initWithAddress:(id)fp8 family:(unsigned char)fp12;

@end

