/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UITextViewDelegate-Protocol.h"

@protocol WAInputTextViewDelegate <UITextViewDelegate>
- (void)textViewDictationDidEnd:(id)fp8;
- (void)textViewDidPasteImage:(id)fp8;
- (void)textView:(id)fp8 needsHeightChangedTo:(float)fp12;
- (float)textViewMaximumHeight:(id)fp8;
@end

