/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WAPersistentJobDelegate.h"
#import "WAJobRequirementProviderDelegate.h"
#import </libobjc.A.h>

@class NSMutableDictionary, WALinkedList, NSMutableSet, WAJobPersistentStore;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface WAJobManager : NSObject <WAPersistentJobDelegate, WAJobRequirementProviderDelegate> {
	NSObject<OS_dispatch_queue>* _eventQueue;
	WAJobPersistentStore* _store;
	BOOL _jobRunloopInProgress;
	NSMutableSet* _activeGroupIds;
	WALinkedList* _pendingJobs;
	NSMutableDictionary* _requirementProviders;
}
+(id)sharedManager;
-(void).cxx_destruct;
-(void)requirementStatusChanged;
-(void)didUnblock:(id)unblock withResult:(unsigned)result;
-(BOOL)handleResult:(unsigned)result forJob:(id)job;
-(void)executeIterationCompleteForJob:(id)job withResult:(unsigned)result;
-(BOOL)requirementsMet:(id)met;
-(BOOL)runNextAvailableJob;
-(void)executeJobImpl;
-(void)executeJobs;
-(void)requirementProviderForName:(id)name withCompletionBlock:(id)completionBlock;
-(void)addRequirementProviders:(id)providers;
-(void)addRequirementProvider:(id)provider;
-(void)addJob:(id)job;
-(void)loadStore:(id)store;
-(id)init;
@end

