/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class UILabel;

@interface WAListTableViewCell : _ABAddressBookCopyArrayOfAllGroups
{
    UILabel *_nameLabel;
    UILabel *_participantsLabel;
}

+ (id)cellWithReuseIdentifier:(id)fp8;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)systemAccessoryView;
- (void)setSystemAccessoryViewHidden:(BOOL)fp8;
- (void)willTransitionToState:(unsigned int)fp8;
- (void)configureWithList:(id)fp8;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;

@end

