/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


__attribute__((visibility("hidden")))
@interface WALinkedListNode : NSObject {
	WALinkedListNode* _prev;
	WALinkedListNode* _next;
	id _object;
	unsigned _token;
}
@property(assign, nonatomic) unsigned token;
@property(retain, nonatomic) id object;
@property(retain, nonatomic) WALinkedListNode* next;
@property(retain, nonatomic) WALinkedListNode* prev;
-(void).cxx_destruct;
-(id)init;
@end

