/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import <UIKit/UIButton.h>

@class CALayer;

__attribute__((visibility("hidden")))
@interface WAMaskedTextButton : UIButton {
	CALayer* _maskLayer;
}
+(id)button;
-(void).cxx_destruct;
-(void)drawLayer:(id)layer inContext:(CGContextRef)context;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
@end

