/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class UILabel, UIProgressView, NSLayoutConstraint, WAMediaRestore, UIImageView, NSObject;
@protocol OS_dispatch_source;

__attribute__((visibility("hidden")))
@interface WAMediaRestoreTableViewCell : UITableViewCell {
	BOOL _showProgressView;
	UILabel* _labelTitle;
	UIProgressView* _progressView;
	UILabel* _labelError;
	UIImageView* _imageViewIcon;
	WAMediaRestore* _currentMediaRestore;
	NSLayoutConstraint* _constraintLabelErrorToProgressView;
	NSObject<OS_dispatch_source>* _timer;
}
@property(retain, nonatomic) NSObject<OS_dispatch_source>* timer;
@property(retain, nonatomic) NSLayoutConstraint* constraintLabelErrorToProgressView;
@property(assign, nonatomic) BOOL showProgressView;
@property(retain, nonatomic) WAMediaRestore* currentMediaRestore;
@property(retain, nonatomic) UIImageView* imageViewIcon;
@property(retain, nonatomic) UILabel* labelError;
@property(retain, nonatomic) UIProgressView* progressView;
@property(retain, nonatomic) UILabel* labelTitle;
+(float)progressForOperation:(id)operation;
+(id)textForStatus:(unsigned)status;
+(id)textForOperation:(id)operation;
+(id)textForPreparing;
+(id)loadFromNib;
-(void).cxx_destruct;
-(void)stopTimer;
-(void)startTimer;
-(void)timerDidFire;
-(void)mediaRestoreOperationDidUpdate:(id)mediaRestoreOperation;
-(void)recentMediaStatusUpdated:(id)updated;
-(void)updateConstraints;
-(void)layoutSubviews;
-(void)updateFonts;
-(void)updateColors;
-(void)awakeFromNib;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
-(id)initWithCoder:(id)coder;
@end

