/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@interface WAMediaGalleryLayoutAttributes : _ABAddressBookCopyArrayOfAllGroups
{
    BOOL _translucent;
}

- (void)setTranslucent:(BOOL)fp8;
- (BOOL)translucent;
- (BOOL)isEqual:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;

@end

