/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

#import "NSFetchedResultsControllerDelegate-Protocol.h"

@class NSFetchedResultsController, NSMutableArray, NSString;

@interface WAMediaManager : _ABAddressBookCopyArrayOfAllGroups <NSFetchedResultsControllerDelegate>
{
    NSMutableArray *_chatSessions;
    BOOL _databaseAccessAvailable;
    BOOL _needsReset;
    BOOL _loadOnChatStorageDidLoadDatabase;
    NSFetchedResultsController *_resultsController;
    int _cachedPhotoCount;
    int _cachedVideoCount;
    int _cachedTotalItemCount;
    int _currentMonth;
    int _currentYear;
    NSString *_title;
}

+ (void)initialize;
- (void)setTitle:(id)fp8;
- (id)title;
- (void).cxx_destruct;
- (id)titleForHeaderInSection:(int)fp8;
- (int)numberOfRowsInSection:(int)fp8;
- (int)numberOfSections;
- (void)chatStorageDidLoadDatabase:(id)fp8;
- (void)chatStorageWillUnloadDatabase:(id)fp8;
- (void)controllerDidChangeContent:(id)fp8;
- (void)controller:(id)fp8 didChangeObject:(id)fp12 atIndexPath:(id)fp16 forChangeType:(unsigned int)fp20 newIndexPath:(id)fp24;
- (void)controller:(id)fp8 didChangeSection:(id)fp12 atIndex:(unsigned int)fp16 forChangeType:(unsigned int)fp20;
- (void)controllerWillChangeContent:(id)fp8;
- (void)deleteMessagesAtIndexPaths:(id)fp8;
- (id)indexPathOfMessage:(id)fp8;
- (id)messageAtIndexPath:(id)fp8;
- (void)loadIfNeeded;
- (unsigned int)numberOfVideos;
- (unsigned int)numberOfPhotos;
- (BOOL)isForSingleItem;
- (unsigned int)countOfMessageType:(unsigned int)fp8;
- (BOOL)isResultSetEmpty;
- (void)reset;
- (void)setNeedsReset;
- (unsigned int)numberOfItems;
- (id)indexPathFromIndex:(unsigned int)fp8;
- (unsigned int)indexFromIndexPath:(id)fp8;
- (BOOL)isGroupChatMedia;
- (void)chatStorageDidReplaceChatSession:(id)fp8;
- (void)setChatSessions:(id)fp8;
- (id)chatSessions;
- (void)updateDateFormatters;
- (void)currentLocaleDidChange:(id)fp8;
- (void)handleSignificantTimeChange:(id)fp8;
- (void)dealloc;
- (id)init;

@end

