/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class NSMutableArray, NSString;

@interface WAMediaCache : _ABAddressBookCopyArrayOfAllGroups
{
    NSString *_cacheFile;
    NSMutableArray *_items;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)synchronize;
- (void)saveItem:(id)fp8;
- (id)mediaCacheItem;
- (id)itemByHash:(id)fp8;
- (id)init;

@end

