/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSSecureCoding.h"
#import </libobjc.A.h>

@class NSString, NSData, NSURL;

__attribute__((visibility("hidden")))
@interface WAMessageMetadata : NSObject <NSSecureCoding> {
	unsigned _type;
	NSData* _imageData;
	NSString* _matchedText;
	NSString* _title;
	NSString* _snippet;
	NSURL* _originalURL;
	NSURL* _canonicalURL;
}
@property(copy, nonatomic) NSURL* canonicalURL;
@property(copy, nonatomic) NSURL* originalURL;
@property(copy, nonatomic) NSString* snippet;
@property(copy, nonatomic) NSString* title;
@property(copy, nonatomic) NSString* matchedText;
@property(retain, nonatomic) NSData* imageData;
@property(readonly, assign, nonatomic) unsigned type;
+(BOOL)supportsSecureCoding;
-(void).cxx_destruct;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(id)initWithWebPageMetadata:(id)webPageMetadata;
-(id)initWithType:(unsigned)type;
-(id)init;
@end

