/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class UIImageView, UIView, WAMediaPickerAsset, WAMediaPickerVideoAssetOverlayView, WAPieProgressView;

@interface WAMediaPickerAssetView : _ABAddressBookCopyArrayOfAllGroups
{
    UIImageView *_checkmarkImageView;
    UIView *_dimmingView;
    BOOL _isHighlighted;
    WAMediaPickerVideoAssetOverlayView *_videoOverlayView;
    WAMediaPickerAsset *_mediaPickerAsset;
    WAPieProgressView *_progressView;
    BOOL _showsCheckmarkWhenSelected;
    BOOL _selected;
    BOOL _imageDimmed;
    UIImageView *_imageView;
}

- (void)setImageDimmed:(BOOL)fp8;
- (BOOL)imageDimmed;
- (BOOL)isSelected;
- (id)imageView;
- (void)setShowsCheckmarkWhenSelected:(BOOL)fp8;
- (BOOL)showsCheckmarkWhenSelected;
- (void).cxx_destruct;
- (void)mediaPickerAssetDidUpdateDownloadProgress:(id)fp8;
- (void)performSelectionRefusedAnimation;
- (id)accessibilityLabel;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)touchesCancelled:(id)fp8 withEvent:(id)fp12;
- (void)touchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)setSelected:(BOOL)fp8;
- (void)configureWithMediaPickerAsset:(id)fp8;
- (void)configureWithPHAsset:(id)fp8;
- (void)installProgressViewIfNeeded;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

