/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAMediaPickerLibraryTableViewCell.h"

@class UIColor, UIImageView, UIView;

@interface WAMediaPickerLibraryTableViewCell7 : WAMediaPickerLibraryTableViewCell
{
    UIImageView *_mainImageView;
    UIImageView *_imageView2;
    UIImageView *_imageView3;
    UIView *_bottomBorder;
    BOOL _hasPosterImage;
    UIColor *_imageViewBackgroundColor;
}

+ (int)preferredSeparatorStyle;
+ (float)preferredHeight;
- (void).cxx_destruct;
- (void)reapplyBackgroundColors;
- (void)setHighlighted:(BOOL)fp8 animated:(BOOL)fp12;
- (void)setSelected:(BOOL)fp8 animated:(BOOL)fp12;
- (void)updateWithAssetCount:(unsigned int)fp8;
- (void)setImageViewBackgroundColor:(id)fp8;
- (void)configureWithAssetCollection:(id)fp8;
- (void)setBottomBorderHidden:(BOOL)fp8;
- (BOOL)isBottomBorderHidden;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;

@end

