/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAActionManager.h"

@class WACloudInteractionOperation;

@interface WAMediaRestore : WAActionManager
{
    WACloudInteractionOperation *_downloadOperation;
}

+ (void)previousBackupChanged:(id)fp8;
+ (void)checkForRequiredMediaRestore;
+ (void)restoreMediaAtNextOpportunity;
+ (id)currentRestore;
- (void)setDownloadOperation:(id)fp8;
- (id)downloadOperation;
- (void).cxx_destruct;
- (void)extractRelevantFilesFromPath:(id)fp8 withInfo:(id)fp12;
- (void)downloadRelevantFilesInDirectory:(id)fp8 withInfo:(id)fp12;
- (void)start;
- (id)errorDomain;
- (id)initWithOptions:(unsigned int)fp8;

@end

