/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class WAMessageBulkDeletionHelper, WAProgressAlertController;

__attribute__((visibility("hidden")))
@interface WAMessageBulkDeletionController : NSObject {
	WAMessageBulkDeletionHelper* _deletionHelper;
	WAProgressAlertController* _progressController;
	WAMessageBulkDeletionController* _retainedSelf;
}
-(void).cxx_destruct;
-(void)deleteMessagesFromViewController:(id)viewController completion:(id)completion;
-(id)initWithOptions:(id)options;
@end

