/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class NSCache, UIImageView, UIView, WALabel;

@interface WAMediaCaptionView : _ABAddressBookCopyArrayOfAllGroups
{
    WALabel *_textLabel;
    WALabel *_secondaryLabel;
    struct CGRect _secondaryImageRect;
    float _blendAmount;
    NSCache *_heightCache;
    UIImageView *_gradientView;
    UIView *_gradientViewContainer;
    UIView *_topBorder;
    UIView *_secondaryTopBorder;
    BOOL _isOcclusionLocked;
    struct CGRect _imageRect;
}

- (struct CGRect)imageRect;
- (void).cxx_destruct;
- (void)updateObstructedAppearanceBlendingOverlap:(float)fp8 withOverlap:(float)fp12;
- (void)updateOcclusionAppearance;
- (void)lockOcclusionAppearanceWithAnimation:(BOOL)fp8;
- (void)unlockOcclusionAppearanceWithAnimation:(BOOL)fp8;
- (float)overlapBetweenRect:(struct CGRect)fp8 andView:(id)fp24;
- (void)setImageRect:(struct CGRect)fp8;
- (void)setText:(id)fp8 onLabel:(id)fp12;
- (void)showText:(id)fp8 imageRect:(struct CGRect)fp12 blendedWithText:(id)fp28 imageRect:(struct CGRect)fp32 blendAmount:(float)fp48;
- (void)setText:(id)fp8 imageRect:(struct CGRect)fp12;
- (id)text;
- (void)setFont:(id)fp8;
- (id)font;
- (void)setBounds:(struct CGRect)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (void)layoutSubviews;
- (void)resizeToFit;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8 forLabel:(id)fp16;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

