/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface WAMediaCache : NSObject {
	NSString* _cacheFile;
	NSMutableArray* _items;
}
+(id)sharedInstance;
-(void).cxx_destruct;
-(void)synchronize;
-(void)saveItem:(id)item;
-(id)mediaCacheItem;
-(id)itemByHash:(id)hash;
-(id)init;
@end

