/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class NSManagedObjectContext, NSManagedObjectID, NSMutableArray, NSObject<OS_dispatch_queue>;

@interface WAMessageDeletionContext : _ABAddressBookCopyArrayOfAllGroups
{
    NSMutableArray *_messages;
    BOOL _orphaned;
    NSManagedObjectContext *_moc;
    NSManagedObjectID *_commonChatSessionObjectID;
    BOOL _hasCommonChatSession;
    NSObject<OS_dispatch_queue> *_ioQueue;
}

- (void).cxx_destruct;
- (void)deleteEmptyDirectoriesFrom:(id)fp8 to:(id)fp12;
- (void)deleteMediaFileAtPaths:(id)fp8;
- (id)xmppThumbPathWithDuplicatesInMessages:(id)fp8;
- (void)evaluate;
- (void)addMessage:(id)fp8;
- (id)initWithManagedObjectContext:(id)fp8 orphanedState:(BOOL)fp12;

@end

