/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UICollectionViewDelegateFlowLayout.h"
#import "WAMediaGalleryCellMenuDelegate.h"
#import "WAMediaGallery.h"
#import "UICollectionViewDataSource.h"
#import "WhatsApp-Structs.h"
#import "WAImageToImageTransitioning.h"
#import "UIViewControllerPreviewingDelegate.h"
#import "WASavedContentBrowserChildViewController.h"
#import "WANavigationControllerPopToAnimating.h"

@class UILabel, NSString, UIImageView, NSMutableSet, UICollectionView, WAMediaManager, WAMediaGalleryFlowLayout, NSMutableIndexSet, NSIndexPath, UIView, UIBarButtonItem, NSMutableArray;

__attribute__((visibility("hidden")))
@interface WAMediaGalleryViewController : WASavedContentBrowserChildViewController <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, WAImageToImageTransitioning, WANavigationControllerPopToAnimating, WAMediaGalleryCellMenuDelegate, UIViewControllerPreviewingDelegate, WAMediaGallery> {
	UILabel* _mediaCountLabel;
	UIBarButtonItem* _editBarButton;
	UIBarButtonItem* _cancelBarButton;
	UIBarButtonItem* _deleteBarButton;
	UIBarButtonItem* _shareItemsBarButton;
	BOOL _editing;
	BOOL _footerVisible;
	BOOL _needsAutoScroll;
	BOOL _tallScreen;
	UIView* _transitionAnimationSourceView;
	NSIndexPath* _messageIndexPathForTransitionAnimation;
	NSMutableSet* _selectedIndexPaths;
	NSMutableArray* _selectedMessagesBeforeMediaManagerContentChange;
	BOOL _mediaManagerUpdateInProgress;
	BOOL _ignoreMediaManagerNotifications;
	NSMutableIndexSet* _insertedSections;
	NSMutableArray* _insertedIndexPaths;
	NSMutableIndexSet* _deletedSections;
	NSMutableArray* _deletedIndexPaths;
	NSMutableArray* _moveInfoToProcess;
	BOOL _isPerformingFancyRotation;
	UIImageView* _beforeRotationSnapshotImageView;
	UIImageView* _afterRotationSnapshotImageView;
	UIView* _whiteBackgroundView;
	NSIndexPath* _thumbnailIndexPathToRestore;
	WAMediaGalleryFlowLayout* _portraitLayout;
	WAMediaGalleryFlowLayout* _landscapeLayout;
	WAMediaManager* _mediaManager;
	NSIndexPath* _indexPathOfMessageToScrollToWhenAppearing;
	UICollectionView* _collectionView;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) UICollectionView* collectionView;
@property(retain, nonatomic) NSIndexPath* indexPathOfMessageToScrollToWhenAppearing;
@property(retain, nonatomic) WAMediaManager* mediaManager;
+(id)controller;
-(void).cxx_destruct;
-(void)previewingContext:(id)context commitViewController:(id)controller;
-(id)previewingContext:(id)context viewControllerForLocation:(CGPoint)location;
-(id)previewActionsForMessage:(id)message;
-(BOOL)shouldBeginCustomPopAnimationForAnimationIdentifier:(id)animationIdentifier;
-(id)popAnimationControllerFromViewController:(id)viewController;
-(id)popAnimationInteractionControllerFromViewController:(id)viewController;
-(void)finishTransitionWithView:(id)view context:(id)context;
-(id)viewForTransitionAnimationWithContext:(id)context;
-(void)prepareForTransitionWithContext:(id)context;
-(BOOL)shouldUseImageToImageTransitionForOperation:(int)operation fromViewController:(id)viewController toViewController:(id)viewController3 context:(id)context;
-(CGSize)collectionView:(id)view layout:(id)layout referenceSizeForFooterInSection:(int)section;
-(CGSize)collectionView:(id)view layout:(id)layout referenceSizeForHeaderInSection:(int)section;
-(void)collectionView:(id)view didDeselectItemAtIndexPath:(id)indexPath;
-(void)collectionView:(id)view didSelectItemAtIndexPath:(id)indexPath;
-(void)collectionView:(id)view didUnhighlightItemAtIndexPath:(id)indexPath;
-(void)collectionView:(id)view didHighlightItemAtIndexPath:(id)indexPath;
-(void)collectionView:(id)view performAction:(SEL)action forItemAtIndexPath:(id)indexPath withSender:(id)sender;
-(BOOL)collectionView:(id)view canPerformAction:(SEL)action forItemAtIndexPath:(id)indexPath withSender:(id)sender;
-(BOOL)collectionView:(id)view shouldShowMenuForItemAtIndexPath:(id)indexPath;
-(id)collectionView:(id)view viewForSupplementaryElementOfKind:(id)kind atIndexPath:(id)indexPath;
-(id)collectionView:(id)view cellForItemAtIndexPath:(id)indexPath;
-(int)collectionView:(id)view numberOfItemsInSection:(int)section;
-(int)numberOfSectionsInCollectionView:(id)collectionView;
-(void)menuControllerDidHideMenu:(id)menuController;
-(BOOL)canPerformAction:(SEL)action forMediaGalleryCell:(id)mediaGalleryCell withSender:(id)sender;
-(void)copyMessageInCell:(id)cell;
-(void)markMessageAsStarredInCell:(id)cell;
-(void)mediaManagerDidDeleteSection:(id)mediaManager;
-(void)mediaManagerDidInsertSection:(id)mediaManager;
-(void)mediaManagerDidMoveItem:(id)mediaManager;
-(void)mediaManagerDidDeleteItem:(id)mediaManager;
-(void)mediaManagerDidInsertItem:(id)mediaManager;
-(void)mediaManagerDidChangeContent:(id)mediaManager;
-(void)mediaManagerWillChangeContent:(id)mediaManager;
-(void)forwardMessages:(id)messages toContactInfo:(id)contactInfo;
-(void)shareMessages:(id)messages;
-(void)shareSelectedItems:(id)items;
-(void)deleteMediaAtIndexPaths:(id)indexPaths;
-(void)deleteSelectedMedia;
-(void)askToDeleteMessage:(id)deleteMessage;
-(void)deleteAction:(id)action;
-(void)presentMediaAtIndexPath:(id)indexPath;
-(void)cancelAction:(id)action;
-(void)editAction:(id)action;
-(void)updateCollectionViewLayoutToCurrentInterfaceOrientationIfNecessary;
-(void)scrollAutomaticallyToRelevantItem;
-(void)updateCollectionViewInsets;
-(void)updateEditingWithAnimation:(BOOL)animation;
-(void)updateSelection;
-(void)updateFooter;
-(void)updateMainVisibleView;
-(id)noItemsViewImage;
-(id)noItemsViewSubheading;
-(id)noItemsViewHeading;
-(id)uniqueIdentifier;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(id)collectionViewSnapshot;
-(void)viewWillLayoutSubviews;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)wa_fontSizeDidChange;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

