/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIDocumentPickerDelegate.h"
#import "UIDocumentMenuDelegate.h"
#import "UIToolbarDelegate.h"
#import "WAMediaPickerDataSource.h"
#import "UINavigationControllerDelegate.h"
#import "PHPhotoLibraryChangeObserver.h"
#import "WANavigationController.h"

@class UILabel, NSString, WAMediaPickerLibraryViewController, NSSet, NSMutableSet, WAMediaPickerLibraryController, UIToolbar, UIView, NSMutableArray, WAMediaPickerAsset, NSTimer;
@protocol WAMediaPickerControllerDelegate;

__attribute__((visibility("hidden")))
@interface WAMediaPickerController : WANavigationController <PHPhotoLibraryChangeObserver, UINavigationControllerDelegate, UIDocumentPickerDelegate, UIDocumentMenuDelegate, UIToolbarDelegate, WAMediaPickerDataSource> {
	int _originalStatusBarStyle;
	NSSet* _initiallySelectedAssetIdentifiers;
	NSMutableArray* _selectedAssetIdentifiers;
	NSTimer* _updateNavigationBarTimer;
	WAMediaPickerLibraryViewController* _libraryViewController;
	BOOL _alreadyNotifiedDelegateOfFirstApperarance;
	UIView* _alertToolbarContainerView;
	UIToolbar* _alertToolbar;
	UILabel* _alertLabel;
	NSMutableArray* _newlySelectedAssets;
	NSMutableSet* _assetsToUnload;
	WAMediaPickerAsset* _lastSelectedAsset;
	NSMutableArray* _externalItems;
	int _preexistingExternalItemCount;
	WAMediaPickerLibraryController* _libraryController;
	int _maximumSelectionCount;
	id _lastUsedAssetCollectionIdentifier;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) id lastUsedAssetCollectionIdentifier;
@property(assign, nonatomic) int maximumSelectionCount;
@property(assign, nonatomic) __weak id<UINavigationControllerDelegate, WAMediaPickerControllerDelegate> delegate;
@property(retain, nonatomic) WAMediaPickerLibraryController* libraryController;
+(id)supportedDocumentTypes;
+(Class)toolbarClass;
+(id)mediaPicker;
-(void).cxx_destruct;
-(void)documentPicker:(id)picker didPickDocumentAtURL:(id)url;
-(void)documentMenuWasCancelled:(id)cancelled;
-(void)documentMenu:(id)menu didPickDocumentPicker:(id)picker;
-(void)selectExternalItem:(id)item;
-(void)showMaximumSelectionCountExceededError;
-(void)recheckSelectedAssetURLsWithCompletionHandler:(id)completionHandler;
-(void)recheckSelectedAssetIdentifiers;
-(void)setInitiallySelectedAssetIdentifiers:(id)identifiers preexistingExternalItemCount:(int)count;
-(id)selectedAssetIdentifiers;
-(void)toggleSelectionOfMediaPickerAsset:(id)mediaPickerAsset;
-(BOOL)allowsMultipleSelection;
-(void)deselectAssetIdentifiers:(id)identifiers;
-(void)clearSelection;
-(BOOL)canAddMoreMediaPickerAssets;
-(BOOL)canSelectMediaPickerAsset:(id)asset;
-(void)setDoneButtonSpinnerHidden:(BOOL)hidden;
-(void)showDoneButtonSpinner;
-(id)mediaPickerItemsFromIdentifiers:(id)identifiers assets:(id)assets;
-(void)dismiss;
-(int)totalSelectedItemCount;
-(void)cancel:(id)cancel;
-(void)unloadPreviouslySelectedAssets;
-(void)updateNavigationBar;
-(void)updateToolbarWithWarningText:(id)warningText;
-(void)updateNavigationBarAndToolbar;
-(id)toolbarItems;
-(id)popViewControllerAnimated:(BOOL)animated;
-(void)pushViewController:(id)controller animated:(BOOL)animated;
-(void)viewDidLayoutSubviews;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(int)positionForBar:(id)bar;
-(void)setUpAlertToolbar;
-(void)setAlertToolbarText:(id)text animated:(BOOL)animated;
-(void)notifyViewAppearanceCompletion;
-(void)pushLastUsedAssetCollection;
-(void)presentModallyFromViewController:(id)viewController completion:(id)completion;
-(void)assetsLibraryChanged:(id)changed;
-(void)photoLibraryDidChange:(id)photoLibrary;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

