/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class UILabel, UIView;

@interface WAMediaGallerySectionHeaderView : _ABAddressBookCopyArrayOfAllGroups
{
    UIView *_backgroundView;
    UILabel *_titleLabel;
    BOOL _translucent;
    BOOL _blurDisabled;
}

- (BOOL)blurDisabled;
- (BOOL)translucent;
- (void).cxx_destruct;
- (void)setBlurDisabled:(BOOL)fp8;
- (void)setTranslucent:(BOOL)fp8;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)applyLayoutAttributes:(id)fp8;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)fp8;

@end

