/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol WAMessageCellDelegate <NSObject>
-(void)messageCell:(id)cell willShowMoreOptionsForTextBlock:(id)textBlock completionHandler:(id)handler;
-(void)messageCell:(id)cell didSelectTextBlock:(id)block;
-(void)markAsStarredMessageInCell:(id)cell;
-(void)replyMessageSenderFromCell:(id)cell;
-(void)addMessageSenderInCell:(id)cell;
-(void)deleteMessagesInCell:(id)cell;
-(void)forwardMessagesInCell:(id)cell;
-(void)messageCell:(id)cell didRequestOpenPlaceURL:(id)url;
-(void)handleDoubleTapInCell:(id)cell;
-(void)handleSingleTapInCell:(id)cell;
-(void)invertSelectionForCell:(id)cell;
-(void)cancelMediaUploadOrDownloadInCell:(id)cell;
-(void)viewMediaInCell:(id)cell;
-(void)downloadMediaInCell:(id)cell;
-(void)alertButtonTappedInCell:(id)cell;
@optional
-(void)messageCell:(id)cell swipeGestureDidChange:(id)swipeGesture;
-(void)inviteVCardPersonFromCell:(id)cell;
-(void)messageVCardPersonFromCell:(id)cell;
-(void)saveVCardPersonFromCell:(id)cell;
-(void)detailsForMessageInCell:(id)cell;
@end

