/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSFetchedResultsControllerDelegate.h"
#import </libobjc.A.h>

@class NSMutableDictionary, NSString, NSArray, NSFetchedResultsController, NSMutableArray;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface WAMediaManager : NSObject <NSFetchedResultsControllerDelegate> {
	NSMutableArray* _chatSessions;
	BOOL _databaseAccessAvailable;
	BOOL _needsReset;
	BOOL _loadOnChatStorageDidLoadDatabase;
	NSFetchedResultsController* _resultsController;
	int _cachedPhotoCount;
	int _cachedVideoCount;
	int _cachedTotalItemCount;
	int _currentMonth;
	int _currentYear;
	NSObject<OS_dispatch_queue>* _thumbnailQueue;
	NSMutableDictionary* _thumbnailCache;
	NSString* _title;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSArray* chatSessions;
@property(readonly, assign, nonatomic) unsigned numberOfVideos;
@property(readonly, assign, nonatomic) unsigned numberOfPhotos;
@property(readonly, assign, nonatomic) unsigned numberOfItems;
@property(copy, nonatomic) NSString* title;
+(void)initialize;
-(void).cxx_destruct;
-(void)removeCachedThumbnailForObjectID:(id)objectID;
-(void)setThumbnailPath:(id)path forObjectID:(id)objectID;
-(id)internalSetThumbnailPath:(id)path forObjectID:(id)objectID;
-(id)thumbnailForMessage:(id)message;
-(id)thumbnailAtIndexPath:(id)indexPath;
-(void)stopCachingAllThumbnails;
-(void)stopCachingThumbnailsAtIndexPaths:(id)indexPaths;
-(void)startCachingThumbnailsAtIndexPaths:(id)indexPaths;
-(id)titleForHeaderInSection:(int)section;
-(int)numberOfRowsInSection:(int)section;
-(int)numberOfSections;
-(void)chatStorageDidLoadDatabase:(id)chatStorage;
-(void)chatStorageWillUnloadDatabase:(id)chatStorage;
-(void)controllerDidChangeContent:(id)controller;
-(void)controller:(id)controller didChangeObject:(id)object atIndexPath:(id)indexPath forChangeType:(unsigned)changeType newIndexPath:(id)path;
-(void)controller:(id)controller didChangeSection:(id)section atIndex:(unsigned)index forChangeType:(unsigned)changeType;
-(void)controllerWillChangeContent:(id)controller;
-(void)deleteMessagesAtIndexPaths:(id)indexPaths;
-(id)indexPathOfMessage:(id)message;
-(id)accessibilityLabelForItemAtIndexPath:(id)indexPath;
-(id)messageAtIndexPath:(id)indexPath;
-(void)loadIfNeeded;
-(BOOL)isForSingleItem;
-(unsigned)countOfMessageType:(unsigned)messageType;
-(BOOL)isResultSetEmpty;
-(void)reset;
-(void)setNeedsReset;
-(id)indexPathFromIndex:(unsigned)index;
-(unsigned)indexFromIndexPath:(id)indexPath;
-(BOOL)isGroupChatMedia;
-(void)chatStorageDidReplaceChatSession:(id)chatStorage;
-(void)updateDateFormatters;
-(void)currentLocaleDidChange:(id)currentLocale;
-(void)handleSignificantTimeChange:(id)change;
-(void)dealloc;
-(id)init;
@end

