/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class WAMessageImageLoaderInfo, _WAMessageImageLoaderFuture;
@protocol WAMessageImageLoaderDataSource;

__attribute__((visibility("hidden")))
@interface WAMessageImageLoader : NSObject {
	WAMessageImageLoaderInfo* _info;
	_WAMessageImageLoaderFuture* _smallImageFuture;
	_WAMessageImageLoaderFuture* _blurredImageFuture;
	_WAMessageImageLoaderFuture* _largeImageFuture;
	int _requestsInFlight;
	id<WAMessageImageLoaderDataSource> _dataSource;
}
@property(readonly, assign, nonatomic) __weak id<WAMessageImageLoaderDataSource> dataSource;
+(void)writeImage:(id)image toFileURL:(id)fileURL;
-(void).cxx_destruct;
-(void)requestImageWithQuality:(unsigned)quality options:(unsigned)options resultHandler:(id)handler;
-(void)setImage:(id)image forQuality:(unsigned)quality;
-(void)invalidateWithUpdatedLocation:(id)updatedLocation;
-(void)invalidateWithUpdatedThumbnailFileURL:(id)updatedThumbnailFileURL;
-(void)invalidateWithUpdatedMediaFileURL:(id)updatedMediaFileURL;
-(void)removeCachedImages;
-(void)endRetainingCachedImages;
-(void)beginRetainingCachedImages;
-(id)initWithDataSource:(id)dataSource info:(id)info;
@end

