/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import "WANoOpGestureRecognizerTouchDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import <UIKit/UIImageView.h>

@class UITapGestureRecognizer, UILongPressGestureRecognizer, WANoOpGestureRecognizer, NSString;

__attribute__((visibility("hidden")))
@interface WAMessageCellSubview : UIImageView <WANoOpGestureRecognizerTouchDelegate, UIGestureRecognizerDelegate> {
	UITapGestureRecognizer* _singleTapGestureRecognizer;
	UITapGestureRecognizer* _doubleTapGestureRecognizer;
	UILongPressGestureRecognizer* _longPressGestureRecognizer;
	WANoOpGestureRecognizer* _monitorRecognizer;
	BOOL _needsSetGestureDependencies;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(BOOL)gestureRecognizer:(id)recognizer shouldReceiveTouch:(id)touch;
-(void)internalHandleLongPressGesture:(id)gesture;
-(void)internalHandleDoubleTapGesture:(id)gesture;
-(void)internalHandleTapGesture:(id)gesture;
-(void)noOpGestureRecognizerDidEndTrackingTouches:(id)noOpGestureRecognizer;
-(void)noOpGestureRecognizerDidBeginTrackingTouches:(id)noOpGestureRecognizer;
-(BOOL)supportsDoubleTapGesture;
-(id)parentMessageCell;
-(void)didMoveToWindow;
-(id)initWithFrame:(CGRect)frame;
@end

