/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class NSDate, NSString;

@interface WAMediaCacheItem : _ABAddressBookCopyArrayOfAllGroups
{
    NSString *_path;
    NSString *_mediaHash;
    NSDate *_timestamp;
}

+ (void)insertMediaCacheItemWithReferenceURL:(id)fp8 storedAtPath:(id)fp12;
+ (id)mediaCacheItemForReferenceURL:(id)fp8;
- (void)setTimestamp:(id)fp8;
- (id)timestamp;
- (void)setMediaHash:(id)fp8;
- (id)mediaHash;
- (void)setPath:(id)fp8;
- (id)path;
- (void).cxx_destruct;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;

@end

