/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

#import "NSSecureCoding-Protocol.h"

@class NSData, NSString, NSURL;

@interface WAMessageMetadata : _ABAddressBookCopyArrayOfAllGroups <NSSecureCoding>
{
    unsigned int _type;
    NSData *_imageData;
    NSString *_matchedText;
    NSString *_title;
    NSString *_snippet;
    NSURL *_originalURL;
    NSURL *_canonicalURL;
}

+ (BOOL)supportsSecureCoding;
- (void)setCanonicalURL:(id)fp8;
- (id)canonicalURL;
- (void)setOriginalURL:(id)fp8;
- (id)originalURL;
- (void)setSnippet:(id)fp8;
- (id)snippet;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setMatchedText:(id)fp8;
- (id)matchedText;
- (void)setImageData:(id)fp8;
- (id)imageData;
- (unsigned int)type;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithWebPageMetadata:(id)fp8;
- (id)initWithType:(unsigned int)fp8;
- (id)init;

@end

