/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import <UIKit/UIView.h>

@class WAMessageFooterView, TextBlock, NSArray, _WAMessageTextViewInternal, UIImageView;
@protocol WAMessageTextViewDelegate;

__attribute__((visibility("hidden")))
@interface WAMessageTextView : UIView {
	UIImageView* _listIconImageView;
	TextBlock* _selectedTextBlock;
	BOOL _isHandlingLongPress;
	BOOL _showListIcon;
	BOOL _flippedHorizontally;
	float _dividerWidth;
	id<WAMessageTextViewDelegate> _delegate;
	WAMessageFooterView* _footerView;
	_WAMessageTextViewInternal* _messageTextViewInternal;
	UIView* _listIconSeparatorView;
	NSArray* _textMessages;
}
@property(readonly, assign, nonatomic) BOOL flippedHorizontally;
@property(readonly, assign, nonatomic) BOOL showListIcon;
@property(readonly, assign, nonatomic) NSArray* textMessages;
@property(readonly, assign, nonatomic) UIView* listIconSeparatorView;
@property(readonly, assign, nonatomic) _WAMessageTextViewInternal* messageTextViewInternal;
@property(readonly, assign, nonatomic) UIImageView* listIconImageView;
@property(readonly, assign, nonatomic) WAMessageFooterView* footerView;
@property(assign, nonatomic) __weak id<WAMessageTextViewDelegate> delegate;
@property(assign, nonatomic) float dividerWidth;
@property(readonly, assign, nonatomic) UIView* contentView;
+(CGSize)preferredSizeForCellData:(id)cellData maximumWidth:(float)width;
+(void)initialize;
-(void).cxx_destruct;
-(id)linkDataForPreviewAtLocation:(CGPoint)location returningLinkDisplayRect:(CGRect*)rect;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(id)textBlockAtTouchLocation:(CGPoint)touchLocation;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(void)handleLongPress;
-(void)handleSingleTap;
-(void)unhighlightAllTextBlocks;
-(void)highlightTextBlock:(id)block;
-(void)setStarIconHidden:(BOOL)hidden animated:(BOOL)animated;
-(void)configureWithCellData:(id)cellData animated:(BOOL)animated;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
@end

