/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAMediaDataPresentationController.h"

@class NSMutableArray;

@interface WAMediaDataGridPresentationController : WAMediaDataPresentationController
{
    NSMutableArray *_imageViews;
}

- (void).cxx_destruct;
- (struct CGRect)frameForIndex:(unsigned int)fp8 count:(unsigned int)fp12 inRect:(struct CGRect)fp16;
- (unsigned int)indexAtPointInView:(struct CGPoint)fp8;
- (void)transitionFromIndex:(unsigned int)fp8 toCurrentIndexWithAnimation:(BOOL)fp12 completion:(id)fp(null);
- (void)viewDidLayoutSubviews;
- (void)didUpdateImageAtIndex:(unsigned int)fp8 completed:(BOOL)fp12;
- (void)cellDataMessagesDidChange;
- (id)currentImageView;
- (id)initWithChatCellData:(id)fp8;

@end

