/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class UILabel;

__attribute__((visibility("hidden")))
@interface WAMediaPickerLibraryTableViewCell : UITableViewCell {
	BOOL _bottomBorderHidden;
	UILabel* _assetCountLabel;
}
@property(readonly, assign, nonatomic) UILabel* assetCountLabel;
@property(assign, nonatomic, getter=isBottomBorderHidden) BOOL bottomBorderHidden;
+(int)preferredSeparatorStyle;
+(float)preferredHeight;
+(id)cellWithReuseIdentifier:(id)reuseIdentifier;
-(void).cxx_destruct;
-(void)updateWithAssetCount:(unsigned)assetCount;
-(id)assetCountLabelTextForCount:(unsigned)count;
-(void)configureWithAssetCollection:(id)assetCollection;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

