/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAURLDownloadTaskData.h"

@class NSString, NSURL;

@interface WAMMSDownloadTaskData : WAURLDownloadTaskData
{
    NSString *_originalHost;
    NSURL *_transformedURL;
    BOOL _autodownload;
    NSURL *_fallbackRemoteURL;
}

- (BOOL)isAutodownload;
- (id)fallbackRemoteURL;
- (void).cxx_destruct;
- (void)calculateHashOfFileAtPath:(id)fp8 completion:(id)fp(null);
- (void)transformDownloadedFileAtURLIfNeeded:(id)fp8 completion:(id)fp(null);
- (void)validateDownloadedFileAtURL:(id)fp8 forTask:(id)fp12 completion:(id)fp(null);
- (id)modifyRequestConfigForRetry:(id)fp8 bytesReceived:(long long)fp12 error:(id)fp20;
- (void)dealloc;
- (id)initWithMessage:(id)fp8 autodownload:(BOOL)fp12;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;

@end

