/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WABackupOperation.h"

@class NSString;

@interface WAMoveOperation : WABackupOperation
{
    BOOL _succeeded;
    NSString *_source;
    NSString *_destination;
}

- (id)destination;
- (id)source;
- (void).cxx_destruct;
- (void)run;
- (BOOL)succeeded;
- (id)initWithSource:(id)fp8 andDestination:(id)fp12;
- (id)initWithDependenciesRequired:(BOOL)fp8;

@end

