/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAMultiSendThumbnailBrowserItemView.h"

@class UIImageView, WAMediaPickerVideoAssetOverlayView, WAMultiSendMediaItem;

@interface WAMultiSendThumbnailBrowserImageView : WAMultiSendThumbnailBrowserItemView
{
    WAMediaPickerVideoAssetOverlayView *_videoOverlayView;
    WAMultiSendMediaItem *_item;
    UIImageView *_thumbnailView;
}

+ (id)viewWithMediaItem:(id)fp8;
- (id)thumbnailView;
- (void).cxx_destruct;
- (id)accessibilityHint;
- (id)accessibilityValue;
- (id)accessibilityLabel;
- (void)configureWithMediaItem:(id)fp8;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)fp8;

@end

