/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAMultiSendMediaItem.h"

@class NSObject<OS_dispatch_queue>, NSString, UIImage;

@interface WAMultiSendEditableImage : WAMultiSendMediaItem
{
    NSObject<OS_dispatch_queue> *_fileCacheQueue;
    NSString *_cachedOriginalImageForPreviewPath;
    NSString *_cachedRenderedImagePath;
    UIImage *_renderedContent;
    UIImage *_originalImageForPreviewToCacheToDisk;
}

- (void).cxx_destruct;
- (id)accessibilityLabel;
- (void)saveRenderedImageToDiskAsync;
- (void)renderWithCompletionHandler:(id)fp(null);
- (void)didChangeTransform;
- (id)renderedImage;
- (id)renderedContent;
- (void)cacheOriginalImageForPreviewToDisk:(id)fp8;
- (id)generateOriginalImageForPreview;
- (void)reallyExportWithProgressHandler:(id)fp(null) completion:(void)fp8;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)initWithImageURL:(id)fp8 renderedImage:(id)fp12 assetIdentifier:(id)fp16;

@end

