/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol WAMultiShotCameraControllerDelegate <NSObject>
-(void)multiShotCameraControllerDidCancel:(id)multiShotCameraController;
-(void)multiShotCameraController:(id)controller didCaptureItems:(id)items;
@optional
-(void)multiShotCameraController:(id)controller didSelectVideoAtURL:(id)url referenceURL:(id)url3 caption:(id)caption;
@end

