/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

#import "WAMultiSendThumbnailBrowserItemViewDelegate-Protocol.h"

@class NSMutableArray, UIButton, UIImageView, UIView, WAMultiSendThumbnailBrowserAddItemButton;

@interface WAMultiSendThumbnailBrowserView : _ABAddressBookCopyArrayOfAllGroups <WAMultiSendThumbnailBrowserItemViewDelegate>
{
    UIImageView *_topBorderImageView;
    UIImageView *_backgroundImageView;
    NSMutableArray *_itemViews;
    UIButton *_viewBlocker;
    BOOL _draggingInProgress;
    BOOL _ignoreDragging;
    int _maxItemsPerRow;
    BOOL _editingModeBeforeRotationAnimation;
    int _rowCount;
    float _itemWidth;
    UIView *_blurView;
    BOOL _editing;
    id <WAMultiSendThumbnailBrowserViewDelegate> _delegate;
    UIView *_headerView;
    int _currentIndex;
    int _maximumNumberOfItems;
    WAMultiSendThumbnailBrowserAddItemButton *_addItemButton;
}

+ (float)preferredThumbnailImageWidth;
- (id)addItemButton;
- (void)setMaximumNumberOfItems:(int)fp8;
- (int)maximumNumberOfItems;
- (BOOL)isEditing;
- (int)currentIndex;
- (id)headerView;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)superViewDidEndRotationAnimation;
- (void)superViewWillBeginRotationAnimation;
- (void)multiSendThumbnailBrowserItemViewWasTapped:(id)fp8;
- (void)changeIndexOfItemView:(id)fp8 to:(int)fp12;
- (void)multiSendThumbnailBrowserItemViewCenterDidChange:(id)fp8;
- (void)multiSendThumbnailBrowserItemViewDidEndDragging:(id)fp8;
- (void)multiSendThumbnailBrowserItemViewDidBeginDragging:(id)fp8;
- (void)multiSendThumbnailBrowserItemViewWantsToEnterEditMode:(id)fp8;
- (void)sortItemViewsByIndex;
- (void)windowBlockerTouched:(id)fp8;
- (void)layoutViewBlocker;
- (void)removeViewBlocker;
- (void)addViewBlocker;
- (void)didMoveToWindow;
- (void)setEditing:(BOOL)fp8;
- (void)setRotationAngle:(float)fp8 ofThumbnailAtIndex:(int)fp12;
- (void)reloadThumbnailAtIndex:(int)fp8;
- (void)removeItemAtIndex:(int)fp8;
- (void)reload;
- (void)setCurrentIndex:(int)fp8 animated:(BOOL)fp12;
- (void)setCurrentIndex:(int)fp8;
- (void)send:(id)fp8;
- (void)addItem:(id)fp8;
- (void)setHeaderView:(id)fp8;
- (int)bestIndexForItemViewWithCenter:(struct CGPoint)fp8;
- (int)mapIndexToLogicalIndex:(int)fp8 ignoringOutsideItems:(BOOL)fp12;
- (struct CGPoint)centerForItemViewAtIndex:(int)fp8 ignoringOutsideItems:(BOOL)fp12;
- (void)relayoutThumbnailsWithAnimation:(BOOL)fp8;
- (float)singleRowHeight;
- (void)layoutSubviews;
- (void)applicationDidEnterBackground:(id)fp8;
- (void)setAddItemButtonType:(unsigned int)fp8;
- (unsigned int)addItemButtonType;
- (void)setAddItemButtonHidden:(BOOL)fp8;
- (BOOL)isAddItemButtonHidden;
- (void)dealloc;
- (void)commonInit;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)fp8;

@end

