/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import "WAMultiSendThumbnailBrowserItemView.h"

@class UIButton;

__attribute__((visibility("hidden")))
@interface WAMultiSendThumbnailBrowserAddItemButton : WAMultiSendThumbnailBrowserItemView {
	UIButton* _button;
	unsigned _buttonType;
}
@property(assign, nonatomic) unsigned buttonType;
@property(assign, nonatomic, getter=isHighlighted) BOOL highlighted;
-(void).cxx_destruct;
-(void)updateButtonHighlight:(id)highlight;
-(BOOL)gestureRecognizer:(id)recognizer shouldReceiveTouch:(id)touch;
-(void)addTarget:(id)target action:(SEL)action forControlEvents:(unsigned)controlEvents;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
@end

