/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol WAMultiSendMediaPickerControllerDelegate <NSObject>
- (void)multiSendMediaPickerController:(id)fp8 didSelectVideoAtURL:(id)fp12 referenceURL:(id)fp16 caption:(id)fp20;
- (void)multiSendMediaPickerControllerDidRequestRetakePhoto:(id)fp8;
- (void)multiSendMediaPickerControllerDidCancel:(id)fp8;
- (void)multiSendMediaPickerController:(id)fp8 didSaveVideoToURL:(id)fp12 caption:(id)fp16;
- (void)multiSendMediaPickerController:(id)fp8 didSelectItems:(id)fp12;
@end

