/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class UIButton;

@interface WAMultiSendTitleView : _ABAddressBookCopyArrayOfAllGroups
{
    UIButton *_deleteButton;
    UIButton *_rotateButton;
    UIButton *_cropButton;
    BOOL _cropping;
    BOOL _editingButtonsHidden;
    id <WAMultiSendTitleViewDelegate> _delegate;
}

+ (struct CGSize)preferredSize;
- (BOOL)isEditingButtonsHidden;
- (BOOL)isCropping;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)setEditingButtonsHidden:(BOOL)fp8;
- (void)setCropping:(BOOL)fp8;
- (void)cropButtonTapped:(id)fp8;
- (void)rotateButtonTapped:(id)fp8;
- (void)deleteButtonTapped:(id)fp8;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)fp8;

@end

