/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WATableViewController.h"

@class NSString, WAMergedContact;

@interface WANotificationSettingsViewController : WATableViewController
{
    NSString *_jid;
    WAMergedContact *_mergedContact;
}

+ (id)controller;
- (id)mergedContact;
- (void)setJid:(id)fp8;
- (id)jid;
- (void).cxx_destruct;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 willSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)showSoundPickerControllerWithTag:(int)fp8;
- (void)setCallSound:(id)fp8;
- (void)setNotificationSound:(id)fp8;
- (id)allJIDsForCurrentContact;
- (void)setMergedContact:(id)fp8;
- (void)wa_fontSizeDidChange;
- (void)viewDidLoad;
- (void)dealloc;

@end

