/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class NSMutableArray, NSString, UITapGestureRecognizer, UIView, UIVisualEffectView;

@interface WANotificationWindow : _ABAddressBookCopyArrayOfAllGroups
{
    UIView *_backgroundView;
    UIVisualEffectView *_backgroundBlurView;
    BOOL _useStaticBlurBackground;
    BOOL _useLiveBlurBackground;
    UITapGestureRecognizer *_tapGestureRecognizer;
    BOOL _forcedToHide;
    BOOL _active;
    id <WANotificationWindowDelegate> _notificationDelegate;
    NSString *_contactJID;
    NSString *_stanzaID;
    NSMutableArray *_messageQueue;
}

+ (id)sharedWindow;
- (void)setMessageQueue:(id)fp8;
- (id)messageQueue;
- (void)setActive:(BOOL)fp8;
- (BOOL)isActive;
- (void)setForcedToHide:(BOOL)fp8;
- (BOOL)forcedToHide;
- (void)setStanzaID:(id)fp8;
- (id)stanzaID;
- (void)setContactJID:(id)fp8;
- (id)contactJID;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (BOOL)_canAffectStatusBarAppearance;
- (void)applicationWillResignActive:(id)fp8;
- (void)contentViewAnyTouch:(id)fp8;
- (void)contentViewTouchUp:(id)fp8;
- (void)handleTapGesture:(id)fp8;
- (void)closeAction:(id)fp8;
- (void)resizeToCurrentStatusBarBounds;
- (void)rotateToStatusBarOrientation;
- (void)didChangeStatusBarFrame:(id)fp8;
- (void)show;
- (void)hideTemporarily;
- (void)hideAnimated:(BOOL)fp8;
- (void)hideIfEmpty;
- (void)removeContentViewsBelowView:(id)fp8;
- (void)removeContentView:(id)fp8 withAnimationDuration:(double)fp12;
- (void)removeContentView:(id)fp8;
- (void)showNextMessage;
- (void)postWAMessage:(id)fp8 duration:(double)fp12 animated:(BOOL)fp20;
- (void)postWAMessage:(id)fp8 duration:(double)fp12;
- (void)configureLegacyContentView:(id)fp8 withChatName:(id)fp12 senderName:(id)fp16 messageText:(id)fp20 profilePicture:(id)fp24;
- (void)configureContentView:(id)fp8 withChatName:(id)fp12 senderName:(id)fp16 messageText:(id)fp20 profilePicture:(id)fp24;
- (id)addCloseButtonToContentView:(id)fp8;
- (id)addContentViewForWAMessage:(id)fp8 profilePicture:(id)fp12;
- (id)blurredBackgroundImage;
- (id)rootViewController;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

