/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import <UIKit/UIButton.h>

@class UILabel, NSString, UIImageView, UIImage;
@protocol WAOutlineRoundButtonDelegate;

__attribute__((visibility("hidden")))
@interface WAOutlineRoundButton : UIButton {
	UILabel* _bottomLabel;
	UIImageView* _outlineMask;
	UIImageView* _solidMask;
	UIImageView* _outlineImageView;
	UIImageView* _solidImageView;
	UIImage* _normalImage;
	UIImage* _selectedImage;
	UIImageView* _blurredImageView;
	BOOL _selectable;
	id<WAOutlineRoundButtonDelegate> _delegate;
}
@property(assign, nonatomic) __weak id<WAOutlineRoundButtonDelegate> delegate;
@property(copy, nonatomic) NSString* bottomLabelText;
@property(assign, nonatomic, getter=isSelectable) BOOL selectable;
+(id)button;
-(void).cxx_destruct;
-(id)accessibilityValue;
-(void)sendAction:(SEL)action to:(id)to forEvent:(id)event;
-(void)setSelected:(BOOL)selected;
-(void)setHighlighted:(BOOL)highlighted;
-(void)setPressed:(BOOL)pressed;
-(void)setIconImage:(id)image;
-(void)updateBlurredImage;
-(void)setCenter:(CGPoint)center;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
@end

