/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class UIView;

@interface WAOverlayImageView : _ABAddressBookCopyArrayOfAllGroups
{
    UIView *_overlayView;
}

- (void).cxx_destruct;
- (void)setOverlayColor:(id)fp8;
- (id)overlayColor;
- (void)setOriginalImage:(id)fp8;
- (id)originalImage;
- (void)setImage:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

