/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import <UIKit/UIScrollView.h>


__attribute__((visibility("hidden")))
@interface WAPagingScrollView : UIScrollView {
}
-(BOOL)gestureRecognizer:(id)recognizer shouldReceiveTouch:(id)touch;
-(BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
@end

