/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIScrollViewDelegate-Protocol.h"

@protocol WAPageableItemBrowserViewDelegate <UIScrollViewDelegate>
- (id)pageableItemBrowserViewContainingViewController:(id)fp8;
- (void)pageableItemBrowserView:(id)fp8 didUpdateThumbnailOfItemAtIndex:(int)fp12;
- (BOOL)pageableItemBrowserViewKeyboardIsShown:(id)fp8;
- (void)pageableItemBrowserViewDidScroll:(id)fp8;
- (void)pageableItemBrowserViewDidEndFocusedTask:(id)fp8;
- (void)pageableItemBrowserViewWillBeginFocusedTask:(id)fp8;
- (void)pageableItemBrowserView:(id)fp8 didFinishRotatingItemAtIndex:(int)fp12;
- (void)pageableItemBrowserView:(id)fp8 willAnimateRotationOfItemAtIndex:(int)fp12 angle:(float)fp16;
- (void)pageableItemBrowserView:(id)fp8 didEndEditingAnimationForItemAtIndex:(int)fp12;
- (void)pageableItemBrowserView:(id)fp8 willBeginEditingAnimationForItemAtIndex:(int)fp12;
- (void)pageableItemBrowserView:(id)fp8 wantsToDeleteItemAtIndex:(int)fp12;
- (void)pageableItemBrowserViewCurrentIndexDidChange:(id)fp8;
- (int)pageableItemCount:(id)fp8;
- (id)pageableItemBrowserView:(id)fp8 itemAtIndex:(int)fp12;
@end

