/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAPageableItemView.h"

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "WAEditableImageEditingViewDelegate-Protocol.h"
#import "WAMediaPlayerDelegate-Protocol.h"
#import "WAVideoScrubberDelegate-Protocol.h"

@class UITapGestureRecognizer, UIView, WAEditableImageEditingView, WAMediaPlayer, WAMultiSendEditableVideo, WAVideoScrubber;

@interface WAPageableVideoItemView : WAPageableItemView <WAMediaPlayerDelegate, WAVideoScrubberDelegate, UIGestureRecognizerDelegate, WAEditableImageEditingViewDelegate>
{
    WAMultiSendEditableVideo *_videoItem;
    WAMediaPlayer *_mediaPlayer;
    WAVideoScrubber *_videoScrubber;
    UIView *_videoScrubberContainerView;
    CDAnonymousStruct1 _sourceTimeToSeekOnPlayerLoad;
    BOOL _suppressMediaPlayerLayout;
    BOOL _needsRegenerateThumbnails;
    UITapGestureRecognizer *_tapGesture;
    BOOL _needsUpdateThumbnailOnTimeChange;
    WAEditableImageEditingView *_editingView;
    UIView *_previewView;
    BOOL _isRenderedContentAvailable;
    BOOL _suppressEditingViewItemChanges;
    BOOL _suppressVideoScrubberLayout;
}

- (void).cxx_destruct;
- (struct CGSize)videoScrubberThumbnailAspectRatio:(id)fp8;
- (void)videoScrubber:(id)fp8 videoFramesAtTimes:(id)fp12 size:(struct CGSize)fp16 tolerance:(CDAnonymousStruct1)fp24 block:(id)fp(null);
- (void)videoScrubberDidEndScrubbing:(id)fp8;
- (void)videoScrubberDidChangeCurrentTime:(id)fp8;
- (void)videoScrubberDidBeginScrubbing:(id)fp8 pausePlayback:(BOOL)fp12;
- (void)videoScrubberDidChangeSlowMotionTimeRange:(id)fp8;
- (void)videoScrubberDidChangeTrimmedTimeRange:(id)fp8;
- (void)mediaPlayerDidEndScrubbing:(id)fp8;
- (void)mediaPlayerDidBeginScrubbing:(id)fp8;
- (void)mediaPlayerDidFinishLoading:(id)fp8;
- (void)mediaPlayerDidPlayToEndTime:(id)fp8;
- (void)mediaPlayerDidChangeCurrentTime:(id)fp8;
- (void)mediaPlayerStatusDidChange:(id)fp8;
- (void)mediaPlayerDidRequestPlaybackStart:(id)fp8;
- (id)editableImageEditingViewContainingViewController:(id)fp8;
- (void)editableImageEditingViewDidEndDeferringRendering:(id)fp8;
- (void)editableImageEditingViewDidBeginDeferringRendering:(id)fp8;
- (void)setCropping:(BOOL)fp8;
- (void)setRotationAngle:(float)fp8 animated:(BOOL)fp12;
- (void)rotateCounterClockwise;
- (void)stopPresentation;
- (void)didScroll;
- (void)setScrolling:(BOOL)fp8;
- (void)setKeyboardHidden:(BOOL)fp8;
- (void)updateMediaPlayerPlaybackTimeRange;
- (void)updateThumb;
- (void)viewTapped:(id)fp8;
- (id)contentView;
- (id)posterImage;
- (void)applyPlayerItem:(id)fp8;
- (void)prepareToCancelCropping;
- (void)configureWithItem:(id)fp8;
- (void)destroyPlayerElements;
- (void)createPlayerElements;
- (void)prepareForReuse;
- (void)didSetContentInset;
- (void)setNeedsLayout;
- (void)layoutSubviews;
- (struct CGRect)fittedRectForAspectRatio:(struct CGSize)fp8;
- (BOOL)gestureRecognizer:(id)fp8 shouldReceiveTouch:(id)fp12;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

