/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

#import "WAPercentDrivenInteractiveTransitioning-Protocol.h"

@interface WAPercentDrivenInteractiveTransition : _ABAddressBookCopyArrayOfAllGroups <WAPercentDrivenInteractiveTransitioning>
{
    id _updateHandler;
}

- (void)setUpdateHandler:(id)fp(null);
- (id)updateHandler;
- (void).cxx_destruct;

@end

