/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAMediaCollectionViewCell.h"

#import "WAMediaPickerAssetPresenting-Protocol.h"

@class WAMediaPickerAsset;

@interface WAPhotoLibraryCollectionViewCell : WAMediaCollectionViewCell <WAMediaPickerAssetPresenting>
{
    WAMediaPickerAsset *_mediaPickerAsset;
    int _pendingRequestID;
    BOOL _showsCheckmarkWhenSelected;
    int _index;
    struct CGSize _maximumThumbnailSizeInPixels;
}

- (void)setMaximumThumbnailSizeInPixels:(struct CGSize)fp8;
- (struct CGSize)maximumThumbnailSizeInPixels;
- (void)setIndex:(int)fp8;
- (int)index;
- (void)setShowsCheckmarkWhenSelected:(BOOL)fp8;
- (BOOL)showsCheckmarkWhenSelected;
- (void).cxx_destruct;
- (void)cancelThumbnailLoading;
- (void)prepareForReuse;
- (void)configureWithMediaPickerAsset:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

