/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import "WAMediaPickerAssetPresenting.h"
#import "WAMediaCollectionViewCell.h"

@class WAMediaPickerAsset, NSString;

__attribute__((visibility("hidden")))
@interface WAPhotoLibraryCollectionViewCell : WAMediaCollectionViewCell <WAMediaPickerAssetPresenting> {
	WAMediaPickerAsset* _mediaPickerAsset;
	int _pendingRequestID;
	BOOL _showsCheckmarkWhenSelected;
	int _index;
	CGSize _maximumThumbnailSizeInPixels;
}
@property(assign, nonatomic) BOOL showsCheckmarkWhenSelected;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) CGSize maximumThumbnailSizeInPixels;
@property(assign, nonatomic) int index;
-(void).cxx_destruct;
-(void)configureWithMediaPickerAsset:(id)mediaPickerAsset;
-(id)initWithFrame:(CGRect)frame;
@end

