/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAViewController.h"

#import "UIScrollViewDelegate-Protocol.h"

@class UIActivityIndicatorView, UIButton, UIImage, UIImageView, UILabel, UIScrollView, UIView, WAPhotoMoveAndScaleCropView;

@interface WAPhotoMoveAndScaleViewController : WAViewController <UIScrollViewDelegate>
{
    WAPhotoMoveAndScaleCropView *_cropView;
    UIActivityIndicatorView *_spinner;
    BOOL _statusBarWasHidden;
    UIView *_imageContainerView;
    UIImageView *_imageView;
    UIImage *_blurredImage;
    UIImageView *_blurredImageView;
    float _blurredImageScaleFactor;
    BOOL _adjustsStatusBarAutomatically;
    unsigned int _mode;
    UIImage *_originalImage;
    float _minimumWidth;
    float _maximumWidth;
    id <WAPhotoMoveAndScaleViewControllerDelegate> _delegate;
    id _completionHandler;
    UIScrollView *_scrollView;
    UILabel *_titleLabel;
    UIButton *_cancelButton;
    UIButton *_doneButton;
    UIView *_bottomView;
    UIImageView *_bottomViewBackgroundView;
    UIImageView *_bottomViewShadowView;
    UIView *_footerContentView;
    UIImageView *_staticImageView;
}

- (void)setStaticImageView:(id)fp8;
- (id)staticImageView;
- (void)setFooterContentView:(id)fp8;
- (id)footerContentView;
- (void)setBottomViewShadowView:(id)fp8;
- (id)bottomViewShadowView;
- (void)setBottomViewBackgroundView:(id)fp8;
- (id)bottomViewBackgroundView;
- (void)setBottomView:(id)fp8;
- (id)bottomView;
- (void)setDoneButton:(id)fp8;
- (id)doneButton;
- (void)setCancelButton:(id)fp8;
- (id)cancelButton;
- (void)setTitleLabel:(id)fp8;
- (id)titleLabel;
- (void)setScrollView:(id)fp8;
- (id)scrollView;
- (void)setAdjustsStatusBarAutomatically:(BOOL)fp8;
- (BOOL)adjustsStatusBarAutomatically;
- (void)setCompletionHandler:(id)fp(null);
- (id)completionHandler;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setMaximumWidth:(float)fp8;
- (float)maximumWidth;
- (void)setMinimumWidth:(float)fp8;
- (float)minimumWidth;
- (id)originalImage;
- (unsigned int)mode;
- (void).cxx_destruct;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (id)rotatingHeaderView;
- (id)rotatingFooterView;
- (void)scrollViewDidZoom:(id)fp8;
- (void)recenterContainerView;
- (id)viewForZoomingInScrollView:(id)fp8;
- (void)configureScrollViewForZooming;
- (id)imageForCurrentZoomRect;
- (void)cancel:(id)fp8;
- (void)done:(id)fp8;
- (void)layoutFooter;
- (void)relayout;
- (void)updateInterfaceForMode;
- (void)setMode:(unsigned int)fp8;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (void)setOriginalImage:(id)fp8;
- (void)makeBlurredImage;
- (void)resetImageViewLayout;
- (int)preferredStatusBarStyle;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

