/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString, NSDictionary;

__attribute__((visibility("hidden")))
@interface WAPhoneNumberMap : NSObject {
	NSString* _path;
	NSDictionary* _prefixMap;
	unsigned _maxPrefixLength;
	unsigned _minPrefixLength;
	NSString* _countryCode;
	NSString* _locale;
}
@property(readonly, copy, nonatomic) NSString* locale;
@property(readonly, copy, nonatomic) NSString* countryCode;
-(void).cxx_destruct;
-(void)dealloc;
-(void)didReceiveMemoryWarning:(id)warning;
-(void)loadIfNeeded;
-(id)locationForPhoneNumber:(id)phoneNumber;
-(id)initWithPath:(id)path;
@end

