/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface WAPlaceIconCache : NSObject {
	NSMutableDictionary* _iconsInProgress;
}
+(id)sharedCache;
-(void).cxx_destruct;
-(id)placeIconImageForWAPlace:(id)waplace completion:(id)completion;
-(id)fsqCategoryIconFromImage:(id)image;
-(id)categoryIconFromWhiteImage:(id)whiteImage;
-(void)saveImage:(id)image withFilename:(id)filename;
-(id)imageWithFilename:(id)filename;
-(id)filenameForImageAtURLPath:(id)urlpath;
@end

