/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WAViewController.h"
#import "UIWebViewDelegate.h"

@class UIWebView, NSString, WAPlace;
@protocol ShareLocationControllerDelegate;

__attribute__((visibility("hidden")))
@interface WAPlaceDetailsViewController : WAViewController <UIWebViewDelegate> {
	BOOL _pageLoaded;
	WAPlace* _waPlace;
	id<ShareLocationControllerDelegate> _delegate;
	UIWebView* _webView;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) UIWebView* webView;
@property(assign, nonatomic) __weak id<ShareLocationControllerDelegate> delegate;
@property(retain, nonatomic) WAPlace* waPlace;
-(void).cxx_destruct;
-(void)webView:(id)view didFailLoadWithError:(id)error;
-(void)webViewDidFinishLoad:(id)webView;
-(void)webViewDidStartLoad:(id)webView;
-(BOOL)webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(int)type;
-(void)hideActivityIndicator;
-(void)showActivityIndicator;
-(void)loadPlacePageWithURLString:(id)urlstring;
-(void)sendPlaceAction:(id)action;
-(void)viewWillAppear:(BOOL)view;
-(void)loadView;
-(void)dealloc;
-(id)initWithWAPlace:(id)waplace delegate:(id)delegate;
@end

