/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class NSMutableDictionary;

@interface WAPlaceIconCache : _ABAddressBookCopyArrayOfAllGroups
{
    NSMutableDictionary *_iconsInProgress;
}

+ (id)sharedCache;
- (void).cxx_destruct;
- (id)placeIconImageForWAPlace:(id)fp8 completion:(id)fp(null);
- (id)fsqCategoryIconFromImage:(id)fp8;
- (id)categoryIconFromWhiteImage:(id)fp8;
- (void)saveImage:(id)fp8 withFilename:(id)fp12;
- (id)imageWithFilename:(id)fp8;
- (id)filenameForImageAtURLPath:(id)fp8;

@end

