/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import <UIKit/UIView.h>

@class UIFont, NSTimer, NSString, UILabel, UIColor;
@protocol WAProgressHUDDelegate;

__attribute__((visibility("hidden")))
@interface WAProgressHUD : UIView {
	BOOL useAnimation;
	SEL methodForExecution;
	id targetForExecution;
	id objectForExecution;
	UILabel* label;
	UILabel* detailsLabel;
	BOOL isFinished;
	CGAffineTransform rotationTransform;
	BOOL square;
	BOOL dimBackground;
	BOOL taskInProgress;
	BOOL removeFromSuperViewOnHide;
	unsigned animationType;
	id<WAProgressHUDDelegate> delegate;
	float opacity;
	UIColor* color;
	UIFont* labelFont;
	UIFont* detailsLabelFont;
	UIView* indicator;
	float xOffset;
	float yOffset;
	float margin;
	float graceTime;
	float minShowTime;
	NSTimer* graceTimer;
	NSTimer* minShowTimer;
	UIView* customView;
	unsigned mode;
	NSString* labelText;
	NSString* detailsLabelText;
	float progress;
	id completionBlock;
	CGSize minSize;
	CGSize size;
	double _showStartedTimestamp;
}
@property(assign) CGSize size;
@property(assign) double showStartedTimestamp;
@property(retain) NSTimer* minShowTimer;
@property(retain) NSTimer* graceTimer;
@property(retain) UIView* indicator;
@property(assign, getter=isSquare) BOOL square;
@property(assign) CGSize minSize;
@property(assign) float progress;
@property(retain) UIFont* detailsLabelFont;
@property(retain) UIFont* labelFont;
@property(assign) BOOL removeFromSuperViewOnHide;
@property(assign) BOOL taskInProgress;
@property(assign) float minShowTime;
@property(assign) float graceTime;
@property(assign) BOOL dimBackground;
@property(assign) float margin;
@property(assign) float yOffset;
@property(assign) float xOffset;
@property(retain) UIColor* color;
@property(assign) float opacity;
@property(copy) NSString* detailsLabelText;
@property(copy) NSString* labelText;
@property(assign) __weak id<WAProgressHUDDelegate> delegate;
@property(retain) UIView* customView;
@property(assign) unsigned animationType;
@property(assign) unsigned mode;
@property(copy) id completionBlock;
+(id)allHUDsForView:(id)view;
+(id)HUDForView:(id)view;
+(unsigned)hideAllHUDsForView:(id)view animated:(BOOL)animated;
+(BOOL)hideHUDForView:(id)view animated:(BOOL)animated;
+(id)showHUDAddedTo:(id)to animated:(BOOL)animated;
-(void).cxx_destruct;
-(void)setTransformForCurrentOrientation:(BOOL)currentOrientation;
-(void)deviceOrientationDidChange:(id)deviceOrientation;
-(void)unregisterFromNotifications;
-(void)registerForNotifications;
-(void)updateUIForKeypath:(id)keypath;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(id)observableKeypaths;
-(void)unregisterFromKVO;
-(void)registerForKVO;
-(void)drawRect:(CGRect)rect;
-(void)layoutSubviews;
-(void)updateIndicators;
-(void)setupLabels;
-(void)cleanUp;
-(void)launchExecution;
-(void)showAnimated:(BOOL)animated whileExecutingBlock:(id)block onQueue:(id)queue completionBlock:(id)block4;
-(void)showAnimated:(BOOL)animated whileExecutingBlock:(id)block onQueue:(id)queue;
-(void)showAnimated:(BOOL)animated whileExecutingBlock:(id)block completionBlock:(id)block3;
-(void)showAnimated:(BOOL)animated whileExecutingBlock:(id)block;
-(void)showWhileExecuting:(SEL)executing onTarget:(id)target withObject:(id)object animated:(BOOL)animated;
-(void)done;
-(void)animationFinished:(id)finished finished:(BOOL)finished2 context:(void*)context;
-(void)hideUsingAnimation:(BOOL)animation;
-(void)showUsingAnimation:(BOOL)animation;
-(void)handleMinShowTimer:(id)timer;
-(void)handleGraceTimer:(id)timer;
-(void)hideDelayed:(id)delayed;
-(void)hide:(BOOL)hide afterDelay:(double)delay;
-(void)hide:(BOOL)hide;
-(void)show:(BOOL)show;
-(void)dealloc;
-(id)initWithWindow:(id)window;
-(id)initWithView:(id)view;
-(id)initWithFrame:(CGRect)frame;
@end

