/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


__attribute__((visibility("hidden")))
@interface WAProximityMonitor : NSObject {
	int _refCount;
}
+(id)sharedMonitor;
-(void)endMonitoring;
-(void)beginMonitoring;
@end

