/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import <UIKit/UIImageView.h>

@class NSString, UIColor;

__attribute__((visibility("hidden")))
@interface WAProfilePictureThumbnailView : UIImageView {
	BOOL _round;
	NSString* _jid;
	UIColor* _placeholderColor;
}
@property(assign, nonatomic, getter=isRound) BOOL round;
@property(retain, nonatomic) UIColor* placeholderColor;
@property(copy, nonatomic) NSString* jid;
-(void).cxx_destruct;
-(void)setProfilePictureImage:(id)image allowPlaceholder:(BOOL)placeholder;
-(void)profilePictureManagerDidPictureChange:(id)profilePictureManager;
-(void)reloadImage;
-(void)setImage:(id)image;
-(void)layoutSubviews;
-(void)dealloc;
-(void)commonInit;
-(id)initWithCoder:(id)coder;
-(id)initWithFrame:(CGRect)frame;
@end

