/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WABackupOperation.h"

@class NSString, WACloudInteractionOperation, WARestore;

@interface WAPrepareRestoreOperation : WABackupOperation
{
    WARestore *_restore;
    NSString *_localRestorePath;
    NSString *_permanentMediaPath;
    WACloudInteractionOperation *_download;
}

+ (id)createExtractOperationsForFiles:(id)fp8 fromDownload:(id)fp12 toPath:(id)fp16;
+ (id)createExtractOperationForName:(id)fp8 fromDownload:(id)fp12 toPath:(id)fp16;
- (void)setDownload:(id)fp8;
- (id)download;
- (void).cxx_destruct;
- (id)createUnTAROperations;
- (id)createCopyOperation:(id)fp8;
- (id)createCopyDatabaseOperations;
- (void)loadUserDefaultsFromDictionary:(id)fp8;
- (void)loadUserDefaults;
- (void)loadNetworkUsageStatistics;
- (void)run;
- (id)initWithRestore:(id)fp8;
- (id)initWithDependenciesRequired:(BOOL)fp8;

@end

