/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol WAQRCodeScannerViewControllerDelegate <NSObject>
- (void)qrCodeScannerViewController:(id)fp8 didFinishWithCode:(id)fp12;
- (void)qrCodeScannerViewControllerDidCancel:(id)fp8;
- (BOOL)qrCodeScannerViewController:(id)fp8 shouldAcceptCode:(id)fp12;
@end

