/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WABasicCameraViewController.h"

#import "WAWebClientQRHelpViewDelegate-Protocol.h"

@class NSString, UIActivityIndicatorView, UIButton, UILabel, UIView, WAShapeView, WAWebClientQRHelpView;

@interface WAQRCodeScannerViewController : WABasicCameraViewController <WAWebClientQRHelpViewDelegate>
{
    NSString *_lastQRCode;
    UIView *_shutterView;
    WAShapeView *_maskView;
    UILabel *_titleLabel;
    UIView *_titleBackgroundView;
    WAWebClientQRHelpView *_helpView;
    UIButton *_dismissButton;
    UIActivityIndicatorView *_spinner;
    id <WAQRCodeScannerViewControllerDelegate> _delegate;
}

+ (BOOL)statusBarHidden;
+ (int)cameraMode;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)dismissHelpView:(id)fp8;
- (void)webClientQRHelpViewDidCompleteFirstIteration:(id)fp8;
- (void)cameraController:(id)fp8 didDetectQRCode:(id)fp12;
- (void)handleTapToFocus:(id)fp8;
- (void)cameraControllerSessionDidBeginRunning:(id)fp8;
- (void)didCreateCameraController;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (void)wa_applicationDidEnterBackground;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

