/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class UIButton, UIImageView, UILabel, UIProgressView, UIView;

@interface WARepairDatabaseViewController : _ABAddressBookCopyArrayOfAllGroups
{
    id <WARepairDatabaseViewControllerDelegate> _delegate;
    UILabel *_paragraphLabel;
    UILabel *_warningLabel;
    UIButton *_beginButton;
    UIProgressView *_progressView;
    UILabel *_completionLabel;
    UIImageView *_warningImageView;
    UIView *_topHairlineView;
    UIView *_bottomHairlineView;
    UIView *_buttonBackgroundView;
    UIView *_contentView;
}

+ (void)showInWindow:(id)fp8 withDelegate:(id)fp12;
- (void)setContentView:(id)fp8;
- (id)contentView;
- (void)setButtonBackgroundView:(id)fp8;
- (id)buttonBackgroundView;
- (void)setBottomHairlineView:(id)fp8;
- (id)bottomHairlineView;
- (void)setTopHairlineView:(id)fp8;
- (id)topHairlineView;
- (void)setWarningImageView:(id)fp8;
- (id)warningImageView;
- (void)setCompletionLabel:(id)fp8;
- (id)completionLabel;
- (void)setProgressView:(id)fp8;
- (id)progressView;
- (void)setBeginButton:(id)fp8;
- (id)beginButton;
- (void)setWarningLabel:(id)fp8;
- (id)warningLabel;
- (void)setParagraphLabel:(id)fp8;
- (id)paragraphLabel;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (unsigned int)supportedInterfaceOrientations;
- (void)handleRepairOutcome:(unsigned int)fp8;
- (void)performRecovery:(id)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

