/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAViewController.h"

#import "PeopleMultiPickerNavigationControllerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WAContactsSearchControllerDelegate-Protocol.h"

@class NSArray, NSMutableArray, UIButton, UILabel, UITableView, UITextField, UIView, WAContactsSearchController;

@interface WARecipientsViewController : WAViewController <PeopleMultiPickerNavigationControllerDelegate, UINavigationControllerDelegate, UITableViewDataSource, UITableViewDelegate, UIGestureRecognizerDelegate, WAContactsSearchControllerDelegate>
{
    WAContactsSearchController *_searchController;
    NSArray *_searchResults;
    NSMutableArray *_selectedContacts;
    NSMutableArray *_selectedJIDs;
    UIButton *_addContactVoiceOverButton;
    float _keyboardHeight;
    BOOL _keyboardActive;
    unsigned int _maxContacts;
    unsigned int _minContacts;
    unsigned int _mode;
    id <WARecipientsViewControllerDelegate> _delegate;
    UIButton *_buttonAddContacts;
    UIView *_viewContactName;
    UITextField *_textFieldContactName;
    UIView *_bottomBorder;
    UIView *_viewContacts;
    UITableView *_tableViewContacts;
    UILabel *_labelHelperText;
    UIView *_viewSearchResults;
    UITableView *_tableViewSearchResults;
}

- (void)setTableViewSearchResults:(id)fp8;
- (id)tableViewSearchResults;
- (void)setViewSearchResults:(id)fp8;
- (id)viewSearchResults;
- (void)setLabelHelperText:(id)fp8;
- (id)labelHelperText;
- (void)setTableViewContacts:(id)fp8;
- (id)tableViewContacts;
- (void)setViewContacts:(id)fp8;
- (id)viewContacts;
- (void)setBottomBorder:(id)fp8;
- (id)bottomBorder;
- (void)setTextFieldContactName:(id)fp8;
- (id)textFieldContactName;
- (void)setViewContactName:(id)fp8;
- (id)viewContactName;
- (void)setButtonAddContacts:(id)fp8;
- (id)buttonAddContacts;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)selectedContacts;
- (unsigned int)mode;
- (void).cxx_destruct;
- (void)contactsSearchControllerDelegateDidInvalidateSearchResults:(id)fp8;
- (void)peopleMultiPickerNavigationControllerDidCancel:(id)fp8;
- (void)peopleMultiPickerNavigationController:(id)fp8 didSelectContacts:(id)fp12;
- (void)keyboardWillHide:(id)fp8;
- (void)keyboardWillShow:(id)fp8;
- (void)textFieldDidBeginEditing:(id)fp8;
- (BOOL)textFieldShouldReturn:(id)fp8;
- (void)tableView:(id)fp8 accessoryButtonTappedForRowWithIndexPath:(id)fp12;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 willSelectRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 willDisplayCell:(id)fp12 forRowAtIndexPath:(id)fp16;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 titleForFooterInSection:(int)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)wa_fontSizeDidChange;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)updateVoiceOverElements;
- (void)accessibilityVoiceOverStatusChanged:(id)fp8;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (BOOL)gestureRecognizer:(id)fp8 shouldReceiveTouch:(id)fp12;
- (void)recipientsTableTapped:(id)fp8;
- (void)deleteRowAction:(id)fp8 withEvent:(id)fp12;
- (void)contactNameEditedAction:(id)fp8;
- (void)addContactsAction:(id)fp8;
- (void)cancelAction:(id)fp8;
- (void)createAction:(id)fp8;
- (void)searchContactsWithMask:(id)fp8;
- (void)setupTableViews;
- (void)layoutViewsWithAnimationDuration:(double)fp8;
- (void)updateButtonState;
- (void)setInitiallySelectedGroupMembers:(id)fp8;
- (void)dealloc;
- (id)initWithDelegate:(id)fp8 mode:(unsigned int)fp12;

@end

