/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAViewController.h"

#import "WAImageToImageTransitioning-Protocol.h"
#import "WANavigationControllerPopToAnimating-Protocol.h"

@class NSArray, UISegmentedControl, UIViewController<WAMediaGallery>, WAWebLinksBrowserViewController;

@interface WASavedContentBrowserViewController : WAViewController <WAImageToImageTransitioning, WANavigationControllerPopToAnimating>
{
    WAWebLinksBrowserViewController *_webLinksViewController;
    NSArray *_childViewControllers;
    UISegmentedControl *_segmentedControl;
    UIViewController<WAMediaGallery> *_mediaGalleryViewController;
    int _selectedIndex;
}

- (int)selectedIndex;
- (id)mediaGalleryViewController;
- (void).cxx_destruct;
- (BOOL)shouldBeginCustomPopAnimationForAnimationIdentifier:(id)fp8;
- (id)popAnimationControllerFromViewController:(id)fp8;
- (id)popAnimationInteractionControllerFromViewController:(id)fp8;
- (void)finishTransitionWithView:(id)fp8 context:(id)fp12;
- (id)viewForTransitionAnimationWithContext:(id)fp8;
- (void)prepareForTransitionWithContext:(id)fp8;
- (BOOL)shouldUseImageToImageTransitionForOperation:(int)fp8 fromViewController:(id)fp12 toViewController:(id)fp16 context:(id)fp20;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (BOOL)shouldAutomaticallyForwardRotationMethods;
- (id)currentViewController;
- (void)setSelectedIndex:(int)fp8;
- (void)segmentedControlDidChange:(id)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (id)initWithMediaManager:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

