/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"

@class UIView;

@protocol WASavedContentBrowserChildNoItemsViewDataSource <NSObject>
@property(readonly, assign, nonatomic) UIView* noItemsView;
-(id)noItemsViewImage;
-(id)noItemsViewSubheading;
-(id)noItemsViewHeading;
@end

