/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WAChatCellData.h"


__attribute__((visibility("hidden")))
@interface WASampleChatCellData : WAChatCellData {
	BOOL _incoming;
}
+(id)cellDataWithText:(id)text isIncoming:(BOOL)incoming;
-(id)nameColor;
-(id)shortName;
-(id)pushName;
-(id)fromName;
-(id)messageID;
-(BOOL)needToShowAlert;
-(BOOL)isSenderUnknown;
-(BOOL)isGroupMessage;
-(BOOL)isSending;
-(BOOL)isFromMe;
-(id)messageTimestampString;
-(BOOL)skipCellLayout;
-(unsigned)footerStatus;
-(unsigned)mediaOrigin;
-(unsigned)messageType;
-(id)message;
-(id)initWithText:(id)text isIncoming:(BOOL)incoming;
@end

