/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class UILabel, UIView, NSSet, WALabel;

__attribute__((visibility("hidden")))
@interface WASearchResultTableViewCell : UITableViewCell {
	UIView* _containerView;
	UILabel* _titleLabel;
	WALabel* _snippetLabel;
	UILabel* _dateLabel;
	NSSet* _searchTokens;
}
-(void).cxx_destruct;
-(void)configureWithSearchResultMessage:(id)searchResultMessage searchTokens:(id)tokens;
-(BOOL)isWord:(id)word foundInSearchTokens:(id)searchTokens;
-(void)configureFonts;
-(void)setUpPlaceholderForSizing;
-(void)setHighlighted:(BOOL)highlighted animated:(BOOL)animated;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(void)layoutSubviews;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
-(id)initWithReuseIdentifier:(id)reuseIdentifier;
@end

