/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class FMDatabaseQueue, NSCharacterSet;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface WASearchEngine : NSObject {
	FMDatabaseQueue* _dbQueue;
	NSObject<OS_dispatch_queue>* _privateQueue;
	NSCharacterSet* _whitespaceCharacterSet;
	NSCharacterSet* _punctuationCharacterSet;
	long long _lastRowID;
}
-(void).cxx_destruct;
-(id)docIDsMatchingSearchTerm:(id)term chatSessionJIDs:(id)jids minimumScore:(float)score type:(int)type offset:(unsigned)offset limit:(unsigned)limit;
-(void)setDocumentType:(int)type ofDocIDs:(id)docIDs;
-(void)updateSearchScoreForMessage:(id)message;
-(void)removeDocIDs:(id)ids;
-(void)removeMessage:(id)message;
-(void)internalAddMessage:(id)message;
-(void)addMessage:(id)message;
-(BOOL)isMessageValid:(id)valid;
-(int)indexMessagesOfCount:(unsigned)count inContext:(id)context;
-(void)internalCloseDatabase;
-(void)closeDatabase;
-(BOOL)openDatabaseAtPath:(id)path;
-(void)openDatabaseIfNeeded;
-(void)markSearchDatabaseAsCorrupted;
-(void)deleteDatabase;
-(unsigned)numberOfIndexedMessages;
-(unsigned long long)sizeOfDatabase;
-(BOOL)isIndexReady;
-(void)closeDatabaseAfterDelayIfIdle;
-(void)applicationDidEnterBackground:(id)application;
-(void)applicationWillTerminate:(id)application;
-(void)dealloc;
-(id)init;
@end

