/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class WAHTTPFetcher;

@interface WAServerStatus : _ABAddressBookCopyArrayOfAllGroups
{
    WAHTTPFetcher *_fetcher;
    BOOL _email;
    BOOL _last;
    BOOL _sync;
    BOOL _chat;
    BOOL _group;
    BOOL _multimedia;
    BOOL _online;
    BOOL _profile;
    BOOL _push;
    BOOL _registration;
    BOOL _status;
    BOOL _broadcast;
    BOOL _version;
    BOOL _requestError;
    BOOL _requestInProgress;
    int _numberOfServicesDown;
}

- (int)numberOfServicesDown;
- (BOOL)requestInProgress;
- (BOOL)requestError;
- (void)setVersion:(BOOL)fp8;
- (BOOL)version;
- (void)setBroadcast:(BOOL)fp8;
- (BOOL)broadcast;
- (void)setStatus:(BOOL)fp8;
- (BOOL)status;
- (void)setRegistration:(BOOL)fp8;
- (BOOL)registration;
- (void)setPush:(BOOL)fp8;
- (BOOL)push;
- (void)setProfile:(BOOL)fp8;
- (BOOL)profile;
- (void)setOnline:(BOOL)fp8;
- (BOOL)online;
- (void)setMultimedia:(BOOL)fp8;
- (BOOL)multimedia;
- (void)setGroup:(BOOL)fp8;
- (BOOL)group;
- (void)setChat:(BOOL)fp8;
- (BOOL)chat;
- (void)setSync:(BOOL)fp8;
- (BOOL)sync;
- (void)setLast:(BOOL)fp8;
- (BOOL)last;
- (void)setEmail:(BOOL)fp8;
- (BOOL)email;
- (void).cxx_destruct;
- (id)servicesStatusString;
- (id)registrationStatusString;
- (void)cancelRequest;
- (void)parseStatusResponse:(id)fp8 withCompletion:(id)fp(null);
- (void)requestStatusWithCompletion:(id)fp(null);
- (id)init;

@end

