/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, UITableView, WAMergedContact, WAShareContactTableHeaderView, WAVCardNameSharingUnit, WAVCardProfilePhotoSharingUnit;

@interface WAShareContactViewController : WAViewController <UITableViewDataSource, UITableViewDelegate>
{
    NSArray *_sharingGroups;
    NSArray *_allSharingUnits;
    WAVCardNameSharingUnit *_nameSharingUnit;
    WAVCardProfilePhotoSharingUnit *_profilePhotoSharingUnit;
    WAShareContactTableHeaderView *_tableHeaderView;
    id <WAShareContactViewControllerDelegate> _delegate;
    UITableView *_tableView;
    WAMergedContact *_mergedContact;
}

+ (id)controllerWithMergedContact:(id)fp8;
- (id)mergedContact;
- (void)setTableView:(id)fp8;
- (id)tableView;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (void)sendContact:(id)fp8;
- (void)cancelAction:(id)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (void)rebuildSharingGroups;
- (void)setMergedContact:(id)fp8;
- (void)dealloc;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

