/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@interface WASQLiteDebugger : _ABAddressBookCopyArrayOfAllGroups
{
}

+ (id)SQLResultStringFromInteger:(int)fp8;
+ (void)checkIntegrityOfDatabaseAtPath:(id)fp8 completion:(id)fp(null);
+ (id)processingQueue;
+ (void)runSQLiteMetaCommand:(id)fp8 output:(struct __sFILE *)fp12;
+ (void)closeSQLiteShell;
+ (void)openSQLiteShellForDatabaseAtPath:(id)fp8 readOnly:(BOOL)fp12;
+ (void)initialize;

@end

