/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class NSString, NSTimer;

@interface WASQLiteDatabaseRepairer : _ABAddressBookCopyArrayOfAllGroups
{
    BOOL _databaseRepairInProgress;
    id _progressHandler;
    NSString *_sourceFilePath;
    NSString *_outputFilePath;
    NSString *_dumpFilePath;
    NSTimer *_progressTrackingTimer;
    unsigned int _backgroundTaskID;
    double _repairStartTime;
    BOOL _disconnectBeforeRepairing;
}

+ (void)mergePendingJournalIfPossibleForDatabaseAtPath:(id)fp8;
+ (unsigned long long)estimatedDiskSpaceRequiredToRepairDatabaseAtPath:(id)fp8;
- (void)setDisconnectBeforeRepairing:(BOOL)fp8;
- (BOOL)disconnectBeforeRepairing;
- (void).cxx_destruct;
- (void)restoreFromDump;
- (BOOL)isDumpFileValid;
- (void)dumpDatabase;
- (void)finishWithStatus:(unsigned int)fp8 completion:(id)fp(null);
- (void)performAfterDisconnectingWithCompletionHandler:(id)fp(null);
- (void)repairDatabaseAtPath:(id)fp8 progressHandler:(id)fp(null) completionHandler:(void)fp12;
- (void)fileSizeProgressTimerHandler:(id)fp8;
- (void)fakeProgressTimerHandler:(id)fp8;
- (void)stopTrackingFileSize;
- (void)startTrackingSizeOfFileAtPath:(id)fp8 estimatedSize:(unsigned long long)fp12 offset:(float)fp20 range:(float)fp24;
- (void)stopFakeProgressTracking;
- (void)startFakeProgressTrackingWithDuration:(double)fp8 offset:(float)fp16 range:(float)fp20;

@end

