/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UISearchControllerDelegate.h"
#import "UISearchResultsUpdating.h"
#import "WhatsApp-Structs.h"
#import "WAChatBaseViewController.h"

@class UIView, UISearchController, UIBarButtonItem, NSArray, UIToolbar, NSString, NSSet, WAChatMessagesController, UILabel;

__attribute__((visibility("hidden")))
@interface WAStarredMessagesViewController : WAChatBaseViewController <UISearchControllerDelegate, UISearchResultsUpdating> {
	NSArray* _jids;
	UIView* _noStarredMessagesView;
	UILabel* _helperTextTitle;
	UILabel* _helperText;
	UIBarButtonItem* _barButtonEdit;
	UIBarButtonItem* _barButtonDone;
	UIToolbar* _editModeToolbar;
	UIBarButtonItem* _barButtonForward;
	UIBarButtonItem* _barButtonShare;
	UIBarButtonItem* _barButtonUnstar;
	UIBarButtonItem* _barButtonDelete;
	BOOL _setContentOffsetOnLayoutSubviews;
	BOOL _loadingEarlierMessages;
	NSArray* _preloadedMessages;
	CGSize _contentSizeBeforeLoadEarlierMessages;
	unsigned _loadedMessagesCount;
	WAChatMessagesController* _allMessagesController;
	NSSet* _currentSearchTokens;
	BOOL _searchInProgress;
	NSString* _currentSearchTerm;
	WAChatMessagesController* _searchResultsController;
	UISearchController* _searchController;
	BOOL _dismissingSearchController;
	BOOL _presentingSearchController;
	float _keyboardHeight;
	BOOL _combinedViewForAllChats;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL combinedViewForAllChats;
-(void).cxx_destruct;
-(void)chatStorageDidLoadDatabase:(id)chatStorage;
-(void)chatStorageWillUnloadDatabase:(id)chatStorage;
-(void)messageUpdated:(id)updated;
-(void)chatStorageDidDeleteMessages:(id)chatStorage;
-(void)loadEarlierMessagesIfNeeded;
-(void)preloadEarlierMessagesIfNeeded;
-(void)reloadMessageControllerWithMessageCount:(unsigned)messageCount;
-(void)addMessages:(id)messages toMessagesController:(id)messagesController;
-(id)loadMessagesFromOffset:(unsigned)offset count:(unsigned)count;
-(void)insertStarredMessageIfNecessary:(id)necessary;
-(void)openChatAroundMessage:(id)message;
-(void)messagesTableDidScroll;
-(id)tableView:(id)view willSelectRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(void)configureSelectionStyleForMessageCell:(id)messageCell inTableView:(id)tableView;
-(void)invertSelectionForCell:(id)cell;
-(void)leaveEditMode;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(void)setEditing:(BOOL)editing;
-(void)doneEditing:(id)editing;
-(void)startEditing:(id)editing;
-(void)updateEditModeButtons;
-(void)deleteSelectedMessages:(id)messages;
-(void)unstarSelectedMessages:(id)messages;
-(void)shareSelectedMessages:(id)messages;
-(void)forwardSelectedMessages:(id)messages;
-(void)keyboardWillHide:(id)keyboard;
-(void)keyboardWillShow:(id)keyboard;
-(void)didDismissSearchController:(id)controller;
-(void)willDismissSearchController:(id)controller;
-(void)didPresentSearchController:(id)controller;
-(void)willPresentSearchController:(id)controller;
-(void)updateSearchResultsForSearchController:(id)searchController;
-(void)resetSearchResults;
-(void)redoSearch;
-(void)updateSearchTerm:(id)term;
-(void)updateSearchResults:(id)results;
-(void)performSearch;
-(void)showNoMessagesViewIfNecessary;
-(void)reloadHelperTextFonts;
-(void)addNoMessagesView;
-(void)wa_applicationDidEnterBackground;
-(void)wa_fontSizeDidChange;
-(void)viewDidLayoutSubviews;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(id)initWithChatSessions:(id)chatSessions;
@end

