/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import <UIKit/UIView.h>

@class UILabel, WAProfilePictureThumbnailView;

__attribute__((visibility("hidden")))
@interface WAStarredMessageCellHeaderView : UIView {
	WAProfilePictureThumbnailView* _profilePictureThumbnail;
	UILabel* _participantNameLabel;
	UILabel* _separatorLabel;
	UILabel* _groupNameLabel;
	UILabel* _dateLabel;
	BOOL _canShowGroupName;
	UIEdgeInsets _textInsets;
}
@property(assign, nonatomic) BOOL canShowGroupName;
@property(assign, nonatomic) UIEdgeInsets textInsets;
+(float)preferredHeightForCellData:(id)cellData;
+(id)contactNameForCellData:(id)cellData;
-(void).cxx_destruct;
-(void)configureWithCellData:(id)cellData;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
@end

