/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class NSString, UIButton, UILabel, UIView, WACircularActivityView;

@interface WAStaticPinCalloutView : _ABAddressBookCopyArrayOfAllGroups
{
    UIView *_backgroundView;
    WACircularActivityView *_activityIndicator;
    UIButton *_buttonSendLocation;
    UILabel *_labelTitle;
    UILabel *_labelSubtitle;
    id _callback;
    NSString *_address;
}

- (void)setAddress:(id)fp8;
- (id)address;
- (void)setCallback:(id)fp(null);
- (id)callback;
- (void).cxx_destruct;
- (id)accessibilityValue;
- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (BOOL)isAccessibilityElement;
- (void)configureWithPlacemark:(id)fp8 showActivityIndicator:(BOOL)fp12 animated:(BOOL)fp16;
- (void)tintColorDidChange;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)layoutSubviews;
- (void)reloadFonts;
- (void)sendLocationButtonAction:(id)fp8;
- (void)updateHighlight:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

