/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <CoreData/NSManagedObject.h>

@class WAPhone, NSString, NSNumber, NSDate;

__attribute__((visibility("hidden")))
@interface WAStatus : NSManagedObject {
}
@property(retain, nonatomic) NSNumber* encryptionV2Capable;
@property(retain, nonatomic) NSNumber* encryptionCapable;
@property(retain, nonatomic) NSNumber* callability;
@property(retain, nonatomic) WAPhone* phone;
@property(retain, nonatomic) NSDate* pictureDate;
@property(retain, nonatomic) NSString* picturePath;
@property(retain, nonatomic) NSString* pictureID;
@property(retain, nonatomic) NSString* whatsAppID;
@property(retain, nonatomic) NSString* text;
@property(retain, nonatomic) NSDate* date;
-(void)willSave;
@end

