/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class UILabel;

@interface WAStarredMessageCellHeaderView : _ABAddressBookCopyArrayOfAllGroups
{
    UILabel *_participantNameLabel;
    UILabel *_separatorLabel;
    UILabel *_groupNameLabel;
    UILabel *_dateLabel;
    BOOL _canShowGroupName;
    struct UIEdgeInsets _textInsets;
}

+ (float)preferredHeightForCellData:(id)fp8;
+ (id)contactNameForCellData:(id)fp8;
- (void)setCanShowGroupName:(BOOL)fp8;
- (BOOL)canShowGroupName;
- (void)setTextInsets:(struct UIEdgeInsets)fp8;
- (struct UIEdgeInsets)textInsets;
- (void).cxx_destruct;
- (void)configureWithCellData:(id)fp8;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)fp8;

@end

