/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WADefaultPreviewActionItemsProviding.h"
#import "WAViewControllerExtensions.h"
#import <UIKit/UITableViewController.h>
#import "WAViewControllerPrivateExtensions.h"

@class _WAViewControllerHelper, NSString, NSArray;

__attribute__((visibility("hidden")))
@interface WATableViewController : UITableViewController <WAViewControllerPrivateExtensions, WAViewControllerExtensions, WADefaultPreviewActionItemsProviding> {
	_WAViewControllerHelper* _wa_helper;
	BOOL _needsContentInsetUpdate;
}
@property(retain, nonatomic) NSArray* defaultPreviewActionItems;
@property(readonly, assign, nonatomic) _WAViewControllerHelper* wa_helper;
@property(readonly, assign, nonatomic) unsigned visibleConnectionStatus;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(BOOL)wa_prefersMinimalBackButton;
-(BOOL)wa_shouldAnimateTableViewRowChanges;
-(BOOL)wa_is3DTouchAvailable;
-(BOOL)wa_isBeingPreviewed;
-(void)visibleConnectionStatusDidChange;
-(void)performAfterTransitionEnds:(id)ends;
-(void)wa_applicationDidBecomeActive;
-(void)wa_applicationWillResignActive;
-(void)wa_applicationDidEnterBackground;
-(void)wa_applicationWillEnterForeground;
-(void)wa_tintColorDidChange;
-(void)wa_fontSizeDidChange;
-(void)_applicationDidDismissCallScreen:(id)_application;
-(void)dismissAllDropDownAlertViewsWithAnimation:(BOOL)animation;
-(void)dismissDropDownAlertView:(id)view animated:(BOOL)animated;
-(void)showDropDownAlertView:(id)view animated:(BOOL)animated;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)didMoveToParentViewController:(id)parentViewController;
-(void)willMoveToParentViewController:(id)parentViewController;
-(void)viewDidLayoutSubviews;
-(void)viewWillLayoutSubviews;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(id)uniqueIdentifier;
-(void)dealloc;
-(id)initWithStyle:(int)style;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

