/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSFileHandle, NSString;

__attribute__((visibility("hidden")))
@interface WATarFile : NSObject {
	unsigned _mode;
	id _fileCompletionHandler;
	NSFileHandle* _handle;
	NSString* _prefix;
}
@property(retain, nonatomic) NSString* prefix;
@property(readonly, assign, nonatomic) NSFileHandle* handle;
@property(copy, nonatomic) id fileCompletionHandler;
@property(readonly, assign, nonatomic) unsigned mode;
+(BOOL)doesHeaderFitAtOffset:(unsigned long long)offset forFileSize:(unsigned long long)fileSize;
+(BOOL)isOffset:(unsigned long long)offset validForSize:(unsigned long long)size;
+(BOOL)fileForHeader:(id)header fitsInTar:(unsigned long long)tar withOffset:(unsigned long long)offset;
+(BOOL)file:(id)file matchesHeader:(id)header;
+(BOOL)createDirectory:(id)directory;
-(void).cxx_destruct;
-(unsigned)extractToDirectory:(id)directory startingAtOffset:(unsigned long long)offset withCancellationCheck:(id)cancellationCheck;
-(unsigned)extractToDirectory:(id)directory withCancellationCheck:(id)cancellationCheck;
-(unsigned)extractFileWithHeader:(id)header toDirectory:(id)directory withCancellationCheck:(id)cancellationCheck;
-(unsigned)extractFileWithHeader:(id)header toPath:(id)path inDirectory:(id)directory withCancellationCheck:(id)cancellationCheck;
-(void)addEOF;
-(id)addFilesAtPaths:(id)paths withCancellationCheck:(id)cancellationCheck;
-(unsigned)addFileAtPath:(id)path withCancellationCheck:(id)cancellationCheck;
-(unsigned)internalAddFileAtPath:(id)path withCancellationCheck:(id)cancellationCheck;
-(unsigned)addFileWithHeader:(id)header fromHandle:(id)handle withCancellationCheck:(id)cancellationCheck;
-(id)headerForPath:(id)path;
-(id)nameForPath:(id)path;
-(void)finish;
-(void)close;
-(id)initWithHandle:(id)handle commonPrefix:(id)prefix mode:(unsigned)mode;
-(id)initWithPath:(id)path commonPrefix:(id)prefix mode:(unsigned)mode;
-(id)initWithPath:(id)path mode:(unsigned)mode;
-(id)init;
@end

