/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import <UIKit/NSTextAttachment.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface WATextAttachment : NSTextAttachment {
	NSString* _name;
	float _pointSize;
	CGRect _boundingRect;
}
@property(assign, nonatomic) float pointSize;
@property(assign, nonatomic) CGRect boundingRect;
@property(copy, nonatomic) NSString* name;
-(void).cxx_destruct;
-(CGRect)attachmentBoundsForTextContainer:(id)textContainer proposedLineFragment:(CGRect)fragment glyphPosition:(CGPoint)position characterIndex:(unsigned)index;
@end

