/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AVSpeechSynthesizerDelegate.h"
#import </libobjc.A.h>
#import "WhatsApp-Structs.h"

@class AVSpeechSynthesizer, NSString;

__attribute__((visibility("hidden")))
@interface WATextToSpeechEngine : NSObject <AVSpeechSynthesizerDelegate> {
	AVSpeechSynthesizer* _synthesizer;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, assign, nonatomic, getter=isSpeechSelectionEnabled) BOOL speechSelectionEnabled;
+(id)sharedEngine;
-(void).cxx_destruct;
-(void)speechSynthesizer:(id)synthesizer didFinishSpeechUtterance:(id)utterance;
-(void)speechSynthesizer:(id)synthesizer didCancelSpeechUtterance:(id)utterance;
-(void)pause;
-(void)speakUtterance:(id)utterance;
-(void)stopSpeakingImmediately;
-(id)init;
@end

