/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import </libobjc.A.h>

@class NSMutableDictionary, UIFont, UIColor, UIImage;

__attribute__((visibility("hidden")))
@interface WATheme : NSObject {
	BOOL _needsReloadWallpaper;
	UIImage* _wallpaperImage;
	UIImage* _blurredWallpaperImage;
	NSMutableDictionary* _contactNameColors;
	int _wallpaperLoadingLock;
	int _groupedTableViewCellSeparatorStyle;
	float _genericTableRowHeight;
	UIFont* _genericTableCellFont;
	float _chatsTableRowHeight;
	UIColor* _tableViewTextFieldTextColor;
	int _tableViewCellDefaultTextAlignment;
	int _tableViewCellActionTextAlignment;
	UIColor* _tableViewCellTextColor;
	UIColor* _tableViewCellTextColorSelected;
	UIColor* _tableViewCellDestructiveTextColor;
	UIColor* _tableViewCellHighlightedBackgroundColor;
	UIColor* _tableViewCellSeparatorColor;
	UIFont* _tableViewFooterFont;
	UIColor* _tableViewFooterTextColor;
	UIColor* _tableViewFooterTextShadowColor;
	int _tableViewFooterTextAlignment;
	UIColor* _tintColor;
	UIColor* _accentColor;
	UIColor* _disabledTintColor;
	UIColor* _helperTextColor;
	UIColor* _helperTextBackgroundColor;
	float _contactsTableRowHeight;
	float _waContactTableRowHeight;
	float _favoritesTableRowHeight;
	float _forwardPickerTableRowHeight;
	UIFont* _contactNameFont;
	UIFont* _waContactNameFont;
	UIColor* _contactNameColor;
	UIColor* _contactNameColorHighlighted;
	UIFont* _contactStatusFont;
	UIFont* _contactStatusFontItalic;
	UIColor* _contactStatusColor;
	UIColor* _contactStatusColorHighlighted;
	UIFont* _contactDetailsFont;
	UIColor* _contactDetailsColor;
	UIColor* _contactDetailsColorHighlighted;
	UIFont* _chatNameFont;
	UIFont* _chatMessageFont;
	UIFont* _chatTimestampFont;
	UIFont* _bubbleContactNameFont;
	UIFont* _bubblePushNameFont;
	UIFont* _bubbleEventFont;
	UIFont* _bubbleDateFont;
	UIFont* _bubbleMessageFont;
	UIFont* _bubbleTimestampFont;
	UIFont* _bubbleVCardFont;
	UIColor* _messageTextColor;
	UIFont* _tooltipFont;
	UIColor* _chatTimestampColor;
	UIColor* _chatTimestampColorHighlighted;
	CGSize _tableViewFooterTextShadowOffset;
}
@property(readonly, assign, nonatomic) UIColor* chatTimestampColorHighlighted;
@property(readonly, assign, nonatomic) UIColor* chatTimestampColor;
@property(readonly, assign, nonatomic) UIFont* tooltipFont;
@property(readonly, assign, nonatomic) UIImage* blurredWallpaperImage;
@property(readonly, assign, nonatomic) UIImage* wallpaperImage;
@property(readonly, assign, nonatomic) UIColor* messageHighlightedUrlColor;
@property(readonly, assign, nonatomic) UIColor* messageUrlColor;
@property(readonly, assign, nonatomic) UIColor* messageTextColor;
@property(readonly, assign, nonatomic) UIFont* bubbleVCardFont;
@property(readonly, assign, nonatomic) UIFont* bubbleTimestampFont;
@property(readonly, assign, nonatomic) UIFont* bubbleMessageFont;
@property(readonly, assign, nonatomic) UIFont* bubbleDateFont;
@property(readonly, assign, nonatomic) UIFont* bubbleEventFont;
@property(readonly, assign, nonatomic) UIFont* bubblePushNameFont;
@property(readonly, assign, nonatomic) UIFont* bubbleContactNameFont;
@property(readonly, assign, nonatomic) UIFont* chatTimestampFont;
@property(readonly, assign, nonatomic) UIFont* chatMessageFont;
@property(readonly, assign, nonatomic) UIFont* chatNameFont;
@property(readonly, assign, nonatomic) UIColor* contactDetailsColorHighlighted;
@property(readonly, assign, nonatomic) UIColor* contactDetailsColor;
@property(readonly, assign, nonatomic) UIFont* contactDetailsFont;
@property(readonly, assign, nonatomic) UIColor* contactStatusColorHighlighted;
@property(readonly, assign, nonatomic) UIColor* contactStatusColor;
@property(readonly, assign, nonatomic) UIFont* contactStatusFontItalic;
@property(readonly, assign, nonatomic) UIFont* contactStatusFont;
@property(readonly, assign, nonatomic) UIColor* contactNameColorHighlighted;
@property(readonly, assign, nonatomic) UIColor* contactNameColor;
@property(readonly, assign, nonatomic) UIFont* waContactNameFont;
@property(readonly, assign, nonatomic) UIFont* contactNameFont;
@property(readonly, assign, nonatomic) float forwardPickerTableRowHeight;
@property(readonly, assign, nonatomic) float favoritesTableRowHeight;
@property(readonly, assign, nonatomic) float waContactTableRowHeight;
@property(readonly, assign, nonatomic) float contactsTableRowHeight;
@property(readonly, assign, nonatomic) UIColor* helperTextBackgroundColor;
@property(readonly, assign, nonatomic) UIColor* helperTextColor;
@property(readonly, assign, nonatomic) UIColor* disabledTintColor;
@property(readonly, assign, nonatomic) UIColor* accentColor;
@property(readonly, assign, nonatomic) UIColor* tintColor;
@property(readonly, assign, nonatomic) int tableViewFooterTextAlignment;
@property(readonly, assign, nonatomic) CGSize tableViewFooterTextShadowOffset;
@property(readonly, assign, nonatomic) UIColor* tableViewFooterTextShadowColor;
@property(readonly, assign, nonatomic) UIColor* tableViewFooterTextColor;
@property(readonly, assign, nonatomic) UIFont* tableViewFooterFont;
@property(readonly, assign, nonatomic) UIColor* tableViewCellSeparatorColor;
@property(readonly, assign, nonatomic) UIColor* tableViewCellHighlightedBackgroundColor;
@property(readonly, assign, nonatomic) UIColor* tableViewCellDestructiveTextColor;
@property(readonly, assign, nonatomic) UIColor* tableViewCellActionTextColor;
@property(readonly, assign, nonatomic) UIColor* tableViewCellTextColorSelected;
@property(readonly, assign, nonatomic) UIColor* tableViewCellTextColor;
@property(readonly, assign, nonatomic) int tableViewCellActionTextAlignment;
@property(readonly, assign, nonatomic) int tableViewCellDefaultTextAlignment;
@property(readonly, assign, nonatomic) UIColor* tableViewTextFieldTextColor;
@property(readonly, assign, nonatomic) float chatsTableRowHeight;
@property(readonly, assign, nonatomic) UIFont* genericTableCellFont;
@property(readonly, assign, nonatomic) float genericTableRowHeight;
@property(readonly, assign, nonatomic) int groupedTableViewCellSeparatorStyle;
+(id)colorPalette;
+(id)defaultTheme;
-(void).cxx_destruct;
-(id)highlightedTintColorForColor:(id)color;
-(void)reloadTintColorInWindow:(id)window;
-(void)resetContactNameColors;
-(id)contactNameColorForJID:(id)jid;
-(id)colorListFilePath;
-(void)setInWindow:(id)window;
-(void)loadWallpaper;
-(void)preloadWallpaper;
-(void)reloadWallpaperIfNeeded;
-(void)setNeedsReloadWallpaper;
-(void)wallpaperDidChange:(id)wallpaper;
-(id)helperTextLabelWithFrame:(CGRect)frame;
-(void)reloadFonts;
-(void)contentSizeCategoryDidChange:(id)contentSizeCategory;
-(void)reloadDynamicTypeFontSize;
-(void)setFontSize:(float)size;
-(int)fontIndexForSize:(int)size;
-(int)fontSizeForIndex:(int)index;
-(id)fontNameForIndex:(int)index;
-(int)numberOfFonts;
-(int)defaultFontSize;
-(int)fontSize;
-(id)fontName;
-(void)dealloc;
-(id)init;
@end

