/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@protocol OS_dispatch_source, OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface WATimer : NSObject {
	id _block;
	NSObject<OS_dispatch_source>* _timer;
	NSObject<OS_dispatch_queue>* _queue;
	double _delay;
	BOOL _didInvalidateTimer;
}
+(id)performBlock:(id)block onQueue:(id)queue afterDelay:(double)delay;
-(void).cxx_destruct;
-(void)internalInvalidate;
-(void)invalidate;
-(void)start;
-(void)performBlock:(id)block;
-(id)initWithBlock:(id)block onQueue:(id)queue afterDelay:(double)delay;
@end

