/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WAViewController.h"
#import "WALinkLabelDelegate.h"
#import "WATOSReadMoreViewControllerDelegate.h"

@class WAGradientView, NSLayoutConstraint, WALinkLabel, UIView, UIButton, NSString, UILabel;
@protocol WATOSMainViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface WATOSMainViewController : WAViewController <WALinkLabelDelegate, WATOSReadMoreViewControllerDelegate> {
	BOOL _accountInfoSharingOptOut;
	unsigned _stage;
	id<WATOSMainViewControllerDelegate> _delegate;
	NSLayoutConstraint* _dismissButtonTop;
	NSLayoutConstraint* _mainContentContainerTop;
	UIButton* _buttonDismiss;
	UIButton* _buttonAgree;
	WALinkLabel* _helperTextLabel;
	UIView* _mainContentContainer;
	UIView* _bottomPanel;
	UIButton* _buttonReadMore;
	NSLayoutConstraint* _buttonReadMoreLeft;
	UILabel* _readMoreHintLabel;
	WAGradientView* _bottomPanelShadow;
	NSLayoutConstraint* _readMoreLabelLeft;
	NSLayoutConstraint* _readMoreLabelRight;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) __weak NSLayoutConstraint* readMoreLabelRight;
@property(assign, nonatomic) __weak NSLayoutConstraint* readMoreLabelLeft;
@property(assign, nonatomic) __weak WAGradientView* bottomPanelShadow;
@property(assign, nonatomic) __weak UILabel* readMoreHintLabel;
@property(assign, nonatomic) __weak NSLayoutConstraint* buttonReadMoreLeft;
@property(assign, nonatomic) __weak UIButton* buttonReadMore;
@property(assign, nonatomic) __weak UIView* bottomPanel;
@property(assign, nonatomic) __weak UIView* mainContentContainer;
@property(assign, nonatomic) __weak WALinkLabel* helperTextLabel;
@property(assign, nonatomic) __weak UIButton* buttonAgree;
@property(assign, nonatomic) __weak UIButton* buttonDismiss;
@property(assign, nonatomic) __weak NSLayoutConstraint* mainContentContainerTop;
@property(assign, nonatomic) __weak NSLayoutConstraint* dismissButtonTop;
@property(assign, nonatomic) __weak id<WATOSMainViewControllerDelegate> delegate;
@property(assign, nonatomic) BOOL accountInfoSharingOptOut;
@property(assign, nonatomic) unsigned stage;
+(id)controller;
-(void).cxx_destruct;
-(void)handleOpenURL:(id)url fromLinkLabel:(id)linkLabel;
-(void)reloadHelperText;
-(void)reloadButtonTitleColors;
-(void)reloadFonts;
-(void)reloadDismissButtonVisibility;
-(void)tosReadMoreControllerDidDismiss:(id)tosReadMoreController;
-(void)tosReadMoreControllerDidAccept:(id)tosReadMoreController;
-(void)handleBottomPanelTap:(id)tap;
-(void)presentReadMoreScreen;
-(void)readMoreButtonTapped:(id)tapped;
-(void)dismissButtonTapped:(id)tapped;
-(void)agreeButtonTapped:(id)tapped;
-(unsigned)supportedInterfaceOrientations;
-(BOOL)shouldAutorotate;
-(void)viewDidLayoutSubviews;
-(void)wa_tintColorDidChange;
-(void)wa_fontSizeDidChange;
-(void)viewDidLoad;
@end

