/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WAWaitOperation.h"


__attribute__((visibility("hidden")))
@interface WATriggeredOperation : WAWaitOperation {
	id _action;
}
@property(copy) id action;
-(void).cxx_destruct;
-(void)run;
-(id)initWithAction:(id)action waitCount:(int)count;
-(id)initWithAction:(id)action;
-(id)initWithCount:(int)count dependenciesRequired:(BOOL)required;
@end

