/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WAUpgradeCallback.h"
#import </libobjc.A.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface WAUpgradeManager : NSObject <WAUpgradeCallback> {
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(void)notifyListenersOfUpgradeFrom:(id)from to:(id)to;
+(void)wa_didUpgradeFrom:(id)from to:(id)to;
+(void)checkForUpgrade;
+(id)previousAppVersion;
+(id)classesToNotifyDuringUpgrade;
@end

