/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WAURLSessionDownloadTaskHandlerOS6Delegate.h"
#import "NSURLSessionDownloadDelegate.h"
#import </libobjc.A.h>

@class NSMutableDictionary, NSString, NSArray;

__attribute__((visibility("hidden")))
@interface WAURLSessionManager : NSObject <WAURLSessionDownloadTaskHandlerOS6Delegate, NSURLSessionDownloadDelegate> {
	NSMutableDictionary* _sessions;
	NSMutableDictionary* _resumableDownloads;
	int _suspensionCounter;
	unsigned _state;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) unsigned state;
@property(readonly, assign, nonatomic) BOOL hasPendingInProcessRequests;
@property(readonly, assign, nonatomic) NSArray* allTaskIdentifiers;
+(id)credentialForServerTrustChallenge:(id)serverTrustChallenge;
+(BOOL)usesURLSession;
-(void).cxx_destruct;
-(void)downloadTaskOS6:(id)a6 didCompleteWithError:(id)error;
-(void)downloadTaskOS6:(id)a6 didFinishDownloadingToURL:(id)url;
-(void)downloadTaskOS6:(id)a6 didWriteData:(long long)data totalBytesWritten:(long long)written totalBytesExpectedToWrite:(long long)write;
-(void)URLSession:(id)session task:(id)task didCompleteWithError:(id)error;
-(void)URLSession:(id)session downloadTask:(id)task didResumeAtOffset:(long long)offset expectedTotalBytes:(long long)bytes;
-(void)URLSession:(id)session downloadTask:(id)task didWriteData:(long long)data totalBytesWritten:(long long)written totalBytesExpectedToWrite:(long long)write;
-(void)URLSession:(id)session downloadTask:(id)task didFinishDownloadingToURL:(id)url;
-(void)URLSession:(id)session didReceiveChallenge:(id)challenge completionHandler:(id)handler;
-(void)URLSessionDidFinishEventsForBackgroundURLSession:(id)urlsession;
-(void)downloadTask:(id)task didCompleteWithError:(id)error;
-(void)downloadTask:(id)task didFinishDownloadingToURL:(id)url;
-(void)downloadTask:(id)task didWriteData:(long long)data totalBytesWritten:(long long)written totalBytesExpectedToWrite:(long long)write;
-(id)downloadTaskDataWithMessage:(id)message autodownload:(BOOL)autodownload;
-(void)endSuspendingTasks;
-(void)beginSuspendingTasks;
-(void)cancelAll;
-(void)resumeAll;
-(void)suspendAll;
-(void)cancelTask:(id)task suppressingNotifications:(BOOL)notifications;
-(BOOL)cancelTaskWithIdentifier:(id)identifier;
-(float)progressOfTaskWithIdentifier:(id)identifier;
-(BOOL)shouldShowNetworkActivityForTaskWithIdentifier:(id)identifier;
-(int)stateOfTaskWithIdentifier:(id)identifier;
-(void)enqueueTaskWithTaskData:(id)taskData;
-(id)dequeueResumableDownloadTaskDataWithIdentifier:(id)identifier;
-(void)removeTask:(id)task;
-(id)existingTaskWithIdentifier:(id)identifier;
-(void)handleEventsForBackgroundURLSession:(id)backgroundURLSession completionHandler:(id)handler;
-(id)addSessionWithIdentifierIfNeeded:(id)identifierIfNeeded;
-(id)mainAppBackgroundSession;
-(id)foregroundSession;
-(id)mainAppBackgroundSessionIdentifier;
-(id)foregroundSessionIdentifier;
-(void)installCategoryMethodsIfNeeded;
-(id)init;
@end

