/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSSecureCoding.h"
#import "NSCopying.h"
#import "WhatsApp-Structs.h"
#import </libobjc.A.h>


__attribute__((visibility("hidden")))
@interface WAURLTaskStats : NSObject <NSSecureCoding, NSCopying> {
	int _mediaType;
	int _result;
	int _mediaSize;
	double _startTime;
	double _durationBeforeSuspend;
}
@property(assign, nonatomic) int mediaSize;
@property(assign, nonatomic) int result;
@property(assign, nonatomic) double durationBeforeSuspend;
@property(assign, nonatomic) double startTime;
@property(assign, nonatomic) int mediaType;
+(BOOL)supportsSecureCoding;
-(void)reset;
-(id)copyWithZone:(NSZone*)zone;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
@end

