/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol WAURLSessionDownloadTaskHandlerOS6Delegate <NSObject>
-(void)downloadTaskOS6:(id)a6 didCompleteWithError:(id)error;
-(void)downloadTaskOS6:(id)a6 didFinishDownloadingToURL:(id)url;
-(void)downloadTaskOS6:(id)a6 didWriteData:(long long)data totalBytesWritten:(long long)written totalBytesExpectedToWrite:(long long)write;
@end

