/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WAVCardSharingUnit.h"

@class UIImage;

__attribute__((visibility("hidden")))
@interface WAVCardProfilePhotoSharingUnit : WAVCardSharingUnit {
	UIImage* _image;
	int _maxWidthInPixels;
}
@property(assign, nonatomic) int maxWidthInPixels;
@property(readonly, assign, nonatomic) UIImage* image;
-(void).cxx_destruct;
-(id)stringForVCard;
-(id)initWithMergedContact:(id)mergedContact index:(unsigned)index;
@end

