/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface WAVCard : NSObject {
	NSString* _contactName;
	NSString* _vCardString;
}
@property(copy, nonatomic) NSString* vCardString;
@property(copy, nonatomic) NSString* contactName;
+(id)mergedContactFromVCardString:(id)vcardString;
+(id)labelFromFieldDescriptions:(id)fieldDescriptions;
+(BOOL)isFieldNameForIMServiceValid:(id)imserviceValid;
+(BOOL)canShareInstantMessagingService:(id)service;
-(void).cxx_destruct;
@end

