/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WAVCardSharingUnit.h"


__attribute__((visibility("hidden")))
@interface WAVCardWorkInfoSharingUnit : WAVCardSharingUnit {
}
+(id)stringForVCardForContact:(id)contact;
-(id)stringForVCard;
-(id)initWithMergedContact:(id)mergedContact index:(unsigned)index;
@end

