/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAViewController.h"

@class NSArray, UILabel, UIView, WACloudBackupManager;

@interface WAVerificationCloudReminderViewController : WAViewController
{
    id <WAVerificationCloudReminderViewControllerDelegate> _delegate;
    WACloudBackupManager *_manager;
    NSArray *_listNumberLabels;
    UIView *_contentView;
    UILabel *_labelTitle;
    NSArray *_textLabels;
    NSArray *_icons;
    UILabel *_labelText1;
    UILabel *_labelText2;
    UILabel *_labelText3;
    UILabel *_labelText4;
    UIView *_viewWhatsApp;
    UILabel *_labelWhatsApp;
}

+ (id)createFromStoryboard;
- (void)setLabelWhatsApp:(id)fp8;
- (id)labelWhatsApp;
- (void)setViewWhatsApp:(id)fp8;
- (id)viewWhatsApp;
- (void)setLabelText4:(id)fp8;
- (id)labelText4;
- (void)setLabelText3:(id)fp8;
- (id)labelText3;
- (void)setLabelText2:(id)fp8;
- (id)labelText2;
- (void)setLabelText1:(id)fp8;
- (id)labelText1;
- (void)setIcons:(id)fp8;
- (id)icons;
- (void)setTextLabels:(id)fp8;
- (id)textLabels;
- (void)setLabelTitle:(id)fp8;
- (id)labelTitle;
- (void)setContentView:(id)fp8;
- (id)contentView;
- (void)setListNumberLabels:(id)fp8;
- (id)listNumberLabels;
- (void)setManager:(id)fp8;
- (id)manager;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)nextAction:(id)fp8;
- (void)addNextButton;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithCoder:(id)fp8 andManager:(id)fp12;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;
- (id)initWithCoder:(id)fp8;
- (id)init;

@end

