/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class UILabel, UIProgressView;

@interface WAVideoPreviewStatusView : _ABAddressBookCopyArrayOfAllGroups
{
    UILabel *_progressLabel;
    UIProgressView *_progressView;
}

- (void).cxx_destruct;
- (void)setProgress:(float)fp8;
- (float)progress;
- (void)setTextColor:(id)fp8;
- (id)textColor;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)fp8;

@end

