/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WACaptionBarDelegate.h"
#import "WhatsApp-Structs.h"
#import "UIGestureRecognizerDelegate.h"
#import "WAViewController.h"

@class NSString, WADoneWithSpinnerBarButtonItem, NSURL, NSObject, WAVideoTranscoder, WAVideoPreviewStatusView, UIBarButtonItem, WACaptionBar, NSTimer;
@protocol WAVideoPreviewViewControllerDelegate, OS_dispatch_group;

__attribute__((visibility("hidden")))
@interface WAVideoPreviewViewController : WAViewController <WACaptionBarDelegate, UIGestureRecognizerDelegate> {
	WAVideoTranscoder* _transcoder;
	NSTimer* _progressTimer;
	NSObject<OS_dispatch_group>* _transcodeDispatchGroup;
	int _transcodeJobID;
	UIBarButtonItem* _cancelButton;
	BOOL _requiresTranscoding;
	BOOL _sendButtonTapped;
	BOOL _showsBackButton;
	NSString* _caption;
	NSURL* _videoURL;
	NSURL* _outputFileURL;
	NSURL* _referenceURL;
	NSURL* _assetLibraryURL;
	id _assetIdentifier;
	id<WAVideoPreviewViewControllerDelegate> _delegate;
	WAVideoPreviewStatusView* _progressView;
	WADoneWithSpinnerBarButtonItem* _sendButton;
	WACaptionBar* _captionBar;
	unsigned long long _videoFileSize;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL showsBackButton;
@property(assign, nonatomic, getter=isProgressViewHidden) BOOL progressViewHidden;
@property(readonly, assign, nonatomic) WACaptionBar* captionBar;
@property(readonly, assign, nonatomic) BOOL sendButtonTapped;
@property(readonly, assign, nonatomic) WADoneWithSpinnerBarButtonItem* sendButton;
@property(retain, nonatomic) WAVideoPreviewStatusView* progressView;
@property(assign, nonatomic) __weak id<WAVideoPreviewViewControllerDelegate> delegate;
@property(copy, nonatomic) id assetIdentifier;
@property(copy, nonatomic) NSURL* assetLibraryURL;
@property(copy, nonatomic) NSURL* referenceURL;
@property(copy, nonatomic) NSURL* outputFileURL;
@property(assign, nonatomic) BOOL requiresTranscoding;
@property(assign, nonatomic) unsigned long long videoFileSize;
@property(copy, nonatomic) NSURL* videoURL;
@property(copy, nonatomic) NSString* caption;
+(int)captionBarStyle;
+(BOOL)movieFileAtURL:(id)url hasSameDurationAsMovieFileAtURL:(id)url2;
+(void)controllerWithURL:(id)url identifier:(id)identifier completion:(id)completion;
+(id)controllerWithURL:(id)url;
+(id)controller;
-(void).cxx_destruct;
-(void)captionBarDidChangeText:(id)captionBar;
-(void)captionBarDidFinishEditing:(id)captionBar;
-(void)captionBarDidHideKeyboard:(id)captionBar;
-(void)captionBarWillHideKeyboard:(id)captionBar;
-(void)captionBarWillShowKeyboard:(id)captionBar;
-(BOOL)gestureRecognizer:(id)recognizer shouldReceiveTouch:(id)touch;
-(BOOL)gestureRecognizer:(id)recognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)gestureRecognizer;
-(void)viewTapped:(id)tapped;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)didProcessVideo;
-(void)willProcessVideo;
-(void)processTranscodedVideoOfDuration:(double)duration atURL:(id)url referenceURL:(id)url3;
-(id)videoCompositionForTranscode;
-(id)assetToTranscode;
-(void)reallyProcessVideo;
-(void)setNeedsVideoProcessing;
-(void)cancelVideoProcessing;
-(XXStruct_yD8eWC)timeRangeToExport;
-(BOOL)internalRequiresTranscoding;
-(void)waitForVideoProcessingToFinish;
-(void)sendVideo:(id)video;
-(void)updateSendButton;
-(void)updateProgress:(id)progress;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)cancel:(id)cancel;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

