/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WABackupOperation.h"

@class NSObject;
@protocol OS_dispatch_semaphore;

__attribute__((visibility("hidden")))
@interface WAWaitOperation : WABackupOperation {
	int _completionIndex;
	int _count;
	int _waitIndex;
	NSObject<OS_dispatch_semaphore>* _semaphore;
}
@property(retain, nonatomic) NSObject<OS_dispatch_semaphore>* semaphore;
@property(assign, nonatomic) int waitIndex;
@property(readonly, assign) int count;
-(void).cxx_destruct;
-(void)finishIndex:(int)index;
-(void)waitForIndexToFinish:(int)finish;
-(void)finish;
-(void)cancel;
-(void)run;
-(id)initWithCount:(int)count;
-(id)initWithCount:(int)count dependenciesRequired:(BOOL)required;
-(id)init;
-(id)initWithDependenciesRequired:(BOOL)dependenciesRequired;
@end

