/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAViewController.h"

#import "UIScrollViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSMutableArray, UIButton, UIImage, UIImageView, UIMotionEffectGroup, UIScrollView, UITableView, UIView;

@interface WAWallpaperPreviewController : WAViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
{
    UIView *_bottomView;
    UIScrollView *_pagingScrollView;
    NSMutableArray *_scrollViewPages;
    UIScrollView *_scrollView;
    UIImageView *_imageView;
    UITableView *_tableViewMessages;
    UIButton *_buttonParallaxOnOff;
    UIMotionEffectGroup *_parallaxEffect;
    BOOL _parallaxEnabled;
    NSArray *_messagesLeft;
    NSArray *_messagesMiddle;
    NSArray *_messagesRight;
    NSArray *_messagesSinglePhoto;
    BOOL _libraryMode;
    id <WAWallpaperPreviewControllerDelegate> _delegate;
    int _libraryImageIndex;
    UIImage *_image;
}

+ (id)controllerWithLibraryImageIndex:(unsigned int)fp8;
+ (id)controllerWithImage:(id)fp8;
- (void)setImage:(id)fp8;
- (id)image;
- (void)setLibraryImageIndex:(int)fp8;
- (int)libraryImageIndex;
- (void)setLibraryMode:(BOOL)fp8;
- (BOOL)libraryMode;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (id)tableView:(id)fp8 viewForHeaderInSection:(int)fp12;
- (float)tableView:(id)fp8 heightForHeaderInSection:(int)fp12;
- (int)tableView:(id)fp8 editingStyleForRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForRowWithCellData:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (id)sampleChatMessagesForTableView:(id)fp8;
- (void)scrollViewDidScroll:(id)fp8;
- (void)scrollViewDidEndZooming:(id)fp8 withView:(id)fp12 atScale:(float)fp16;
- (void)scrollViewDidEndDecelerating:(id)fp8;
- (void)scrollViewDidEndDragging:(id)fp8 willDecelerate:(BOOL)fp12;
- (void)scrollViewWillBeginZooming:(id)fp8 withView:(id)fp12;
- (void)scrollViewWillBeginDragging:(id)fp8;
- (id)viewForZoomingInScrollView:(id)fp8;
- (void)updateScrollViewAfterEnablingMotion:(BOOL)fp8;
- (void)checkIfMotionShouldBeDisabledUnintentionally;
- (void)updateBlurEffectsForParallaxButton:(id)fp8;
- (void)updateParallaxOnOffButtonState;
- (void)setParallaxEffectEnabled:(BOOL)fp8;
- (void)parallaxOnOffAction:(id)fp8;
- (void)cancelAction:(id)fp8;
- (void)doneAction:(id)fp8;
- (void)bottomButtonAnyTouch:(id)fp8;
- (id)imageForCurrentZoomRect;
- (void)reloadSingleImage;
- (void)tilePages;
- (void)setCurrentPageIndex:(unsigned int)fp8;
- (void)scrollToPageAtIndex:(int)fp8 animated:(BOOL)fp12;
- (void)unloadScrollViewPageAtIndex:(int)fp8;
- (void)loadScrollViewPageAtIndex:(int)fp8 asynchronously:(BOOL)fp12;
- (id)parallaxOnOffButton;
- (id)sampleConversationTable;
- (void)presentFromViewController:(id)fp8 animated:(BOOL)fp12;
- (unsigned int)supportedInterfaceOrientations;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(BOOL)fp8;
- (void)loadView;
- (id)init;

@end

