/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WhatsApp-Structs.h"
#import "WAVisibilityTrackingViewController.h"

@class UITableView, NSString, UIColor, WAWarningView;

__attribute__((visibility("hidden")))
@interface WAWarningViewController : WAVisibilityTrackingViewController {
	UITableView* _tableView;
	UIColor* _warningTextColor;
	UIColor* _warningBackgroundColor;
	WAWarningView* _warningView;
}
@property(readonly, assign, nonatomic) float topLayoutGuideLengthIfAvailable;
@property(retain, nonatomic) WAWarningView* warningView;
@property(retain, nonatomic) UIColor* warningBackgroundColor;
@property(retain, nonatomic) UIColor* warningTextColor;
@property(readonly, assign, nonatomic) NSString* warningText;
@property(retain, nonatomic) UITableView* tableView;
-(void).cxx_destruct;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)refreshWarningViewLayout;
-(void)viewDidLayoutSubviews;
-(BOOL)prepareTableViewForFrame:(CGRect)frame;
-(CGRect)frameForWarningView:(id)warningView visible:(BOOL)visible;
-(void)animate:(BOOL)animate actions:(id)actions completion:(id)completion;
-(void)hideWarningView;
-(void)showWarningViewAnimated:(BOOL)animated;
-(void)removeWarningView;
-(void)addWarningView;
-(void)setWarningText:(id)text withAction:(id)action;
-(void)dealloc;
@end

