/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAMessageCell.h"

@class UIImageView, UILabel, UILongPressGestureRecognizer, UITapGestureRecognizer, UIView, WAMessageTextView;

@interface WAWebURLMessageCell : WAMessageCell
{
    UIImageView *_roundedCornersImageView;
    WAMessageTextView *_messageTextView;
    UIView *_infoView;
    UIImageView *_imageView;
    UILabel *_contentLabel;
    UILabel *_webURLLabel;
    UITapGestureRecognizer *_contentSingleTapGestureRecognizer;
    UITapGestureRecognizer *_contentDoubleTapGestureRecognizer;
    UILongPressGestureRecognizer *_contentLongPressGestureRecognizer;
}

+ (struct CGSize)contentSizeForCellData:(id)fp8 maxWidth:(float)fp12;
+ (struct UIEdgeInsets)textInsetsForCellData:(id)fp8;
+ (struct UIEdgeInsets)contentInsetsForCellData:(id)fp8 cellWidth:(float)fp12;
+ (id)cellReuseIdentifier;
+ (void)initialize;
- (void).cxx_destruct;
- (void)configureForAccessibility;
- (id)accessibilityHintText;
- (void)prepareFor3DTouchPreviewWithContext:(id)fp8;
- (id)dataForPreviewingContext:(id)fp8 atLocation:(struct CGPoint)fp12;
- (id)registerSubviewsForPreviewingUsingViewController:(id)fp8 previewingDelegate:(id)fp12;
- (void)setBubbleHighlighted:(BOOL)fp8 animated:(BOOL)fp12;
- (void)setDimmed:(BOOL)fp8 animated:(BOOL)fp12;
- (void)setDimmed:(BOOL)fp8;
- (void)performCopy;
- (BOOL)canPerformCopy;
- (void)handleContentLongPressGesture:(id)fp8;
- (void)handleContentDoubleTapGesture:(id)fp8;
- (void)handleContentTapGesture:(id)fp8;
- (void)handleTapOnBubbleWithLocation:(struct CGPoint)fp8;
- (void)updateStarIndicatorAnimated:(BOOL)fp8;
- (void)configureCellWithAnimation:(BOOL)fp8;
- (void)layoutSubviews;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;

@end

