/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class NSURL, NSURLSessionDataTask;

@interface WAWebPageReader : _ABAddressBookCopyArrayOfAllGroups
{
    id _handler;
    double _startTime;
    NSURLSessionDataTask *_currentDataTask;
    BOOL _invalidated;
    int _handlerInvocationCount;
    int _imageFetchRetryCount;
    NSURL *_webURL;
    double _htmlFetchTimeout;
    double _imageFetchTimeout;
    struct CGSize _preferredImageSize;
}

+ (void)initialize;
- (void)setPreferredImageSize:(struct CGSize)fp8;
- (struct CGSize)preferredImageSize;
- (id)webURL;
- (void)setImageFetchTimeout:(double)fp8;
- (double)imageFetchTimeout;
- (void)setHtmlFetchTimeout:(double)fp8;
- (double)htmlFetchTimeout;
- (void).cxx_destruct;
- (void)cleanUp;
- (void)failWithError:(id)fp8;
- (void)cancel;
- (void)fetchImageInMetadata:(id)fp8;
- (void)completeReadingWithMetadata:(id)fp8;
- (void)parseHTML:(id)fp8 fromURL:(id)fp12 rawData:(id)fp16 assumedEncoding:(unsigned int)fp20 reinterpretDataIfNeeded:(BOOL)fp24;
- (unsigned int)stringEncodingFromCharset:(id)fp8;
- (void)loadMetadataWithResultHandler:(id)fp(null);
- (id)URLRequestWithURL:(id)fp8 timeout:(double)fp12;
- (id)initWithURL:(id)fp8;
- (id)init;

@end

