/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import </libobjc.A.h>

@class NSDate, NSString;

__attribute__((visibility("hidden")))
@interface WAWebClientSessionData : NSObject <NSCoding> {
	NSString* _webRef;
	BOOL _active;
	NSString* _browserID;
	NSString* _clientToken;
	NSString* _operatingSystem;
	NSString* _browser;
	NSDate* _deviceLoginTime;
	NSString* _location;
	NSDate* _lastActiveTime;
	NSDate* _expirationTime;
}
@property(copy, nonatomic) NSDate* expirationTime;
@property(assign, nonatomic, getter=isActive) BOOL active;
@property(copy, nonatomic) NSDate* lastActiveTime;
@property(copy, nonatomic) NSString* location;
@property(copy, nonatomic) NSDate* deviceLoginTime;
@property(copy, nonatomic) NSString* browser;
@property(copy, nonatomic) NSString* operatingSystem;
@property(copy, nonatomic) NSString* webRef;
@property(copy, nonatomic) NSString* clientToken;
@property(copy, nonatomic) NSString* browserID;
-(void).cxx_destruct;
-(BOOL)isEqualToSessionData:(id)sessionData;
-(void)clear;
-(id)description;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
@end

