/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString, NSURL, WAWebPageMetadata, WAWebPageReader;
@protocol WAWebPageFromTextLoaderDelegate;

__attribute__((visibility("hidden")))
@interface WAWebPageFromTextLoader : NSObject {
	NSString* _textForWebURLDetection;
	BOOL _isDetectingWebURL;
	WAWebPageReader* _pendingReader;
	NSString* _matchedText;
	NSURL* _webURL;
	BOOL _isCancelled;
	id<WAWebPageFromTextLoaderDelegate> _delegate;
	WAWebPageMetadata* _metadata;
	NSString* _text;
}
@property(copy, nonatomic) NSString* text;
@property(readonly, copy, nonatomic) NSString* matchedText;
@property(readonly, assign, nonatomic) WAWebPageMetadata* metadata;
@property(assign, nonatomic) __weak id<WAWebPageFromTextLoaderDelegate> delegate;
+(void)initialize;
-(void).cxx_destruct;
-(void)reallyLoadWebURL:(id)url resultHandler:(id)handler;
-(void)loadWebURL:(id)url matchedText:(id)text;
-(void)detectWebURL;
-(void)cancel;
@end

