/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol WebImagePickerDelegate <NSObject>
- (void)webImagePickerDidCancel:(id)fp8;
- (void)webImagePicker:(id)fp8 didSelectImage:(id)fp12;
@end

