/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ImageSearchControllerDelegate.h"
#import "WAPhotoMoveAndScaleViewControllerDelegate.h"
#import <UIKit/UINavigationController.h>

@class NSString, WAHTTPFetcher, WAPhotoMoveAndScaleViewController, ImageSearchController;
@protocol WebImagePickerDelegate;

__attribute__((visibility("hidden")))
@interface WebImagePicker : UINavigationController <ImageSearchControllerDelegate, WAPhotoMoveAndScaleViewControllerDelegate> {
	ImageSearchController* _imageSearchController;
	id<WebImagePickerDelegate> _pickerDelegate;
	WAHTTPFetcher* _httpFetcher;
	WAPhotoMoveAndScaleViewController* _moveAndScaleViewController;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSString* preloadedSearchText;
-(void).cxx_destruct;
-(void)downloadImageAtURL:(id)url;
-(void)photoMoveAndScaleViewController:(id)controller didFinishWithImage:(id)image;
-(id)popViewControllerAnimated:(BOOL)animated;
-(void)imageSearchControllerDidCancel:(id)imageSearchController;
-(void)imageSearchController:(id)controller didSelectImageWithURL:(id)url;
-(id)initWithPickerDelegate:(id)pickerDelegate;
@end

