/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

#import "PKPushRegistryDelegate-Protocol.h"
#import "RestoreBackupViewControllerDelegate-Protocol.h"
#import "UIApplicationDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "UITabBarControllerDelegate-Protocol.h"
#import "VerificationControllerDelegate-Protocol.h"
#import "WAChatDatabaseMigrationViewControllerDelegate-Protocol.h"
#import "WADeleteAccountControllerDelegate-Protocol.h"
#import "WANotificationWindowDelegate-Protocol.h"
#import "WARepairDatabaseViewControllerDelegate-Protocol.h"
#import "WAVoiceCallViewControllerDelegate-Protocol.h"

@class NSMutableArray, NSObject<OS_dispatch_group>, NSString, PKPushRegistry, UINavigationController, UIWindow, VerificationController, WAAutomationWindow, WACallWindow, WATabBarController, WATimelockViewController, WAVoiceCallViewController;

@interface WhatsAppAppDelegate : _ABAddressBookCopyArrayOfAllGroups <UITabBarControllerDelegate, WAChatDatabaseMigrationViewControllerDelegate, WANotificationWindowDelegate, WARepairDatabaseViewControllerDelegate, RestoreBackupViewControllerDelegate, WAVoiceCallViewControllerDelegate, WADeleteAccountControllerDelegate, PKPushRegistryDelegate, VerificationControllerDelegate, UINavigationControllerDelegate, UIApplicationDelegate>
{
    UINavigationController *_iPadNoticeController;
    UINavigationController *_noNetworkViewController;
    WATimelockViewController *_timelockViewController;
    BOOL _databaseMigrationInProgress;
    BOOL _databaseRepairInProgress;
    BOOL _suppressRootViewSetUpOnEnteringForeground;
    BOOL _applicationIsBecomingActive;
    BOOL _upgrade;
    BOOL _applicationUILoaded;
    BOOL _changNumberPending;
    BOOL _buildExpired;
    BOOL _contactsAccessRequestInProgress;
    NSString *_jidToCallOnConnect;
    NSString *_pendingApplicationShortcutAction;
    NSObject<OS_dispatch_group> *_rotationDispatchGroup;
    WAVoiceCallViewController *_activeVoiceCallViewController;
    BOOL _showMicPermissionErrorOnDismissCallScreen;
    BOOL _showNoCallingErrorOnDismissCallScreen;
    int _noCallingErrorCode;
    NSMutableArray *_presentedInAppNotificationAlerts;
    NSMutableArray *_deferredInAppNotificationAlerts;
    PKPushRegistry *_voipRegistry;
    BOOL _needsAPNSToken;
    BOOL _needsVOIPToken;
    int _lastSeenVOIPPushIndex;
    int _lastSeenAPNSPushIndex;
    unsigned int _resumeCounter;
    id _backgroundFetchCompletionHandler;
    BOOL _hasAppFinishedLaunching;
    WAAutomationWindow *_automationWindow;
    NSObject<OS_dispatch_group> *_dataProtectionDispatchGroup;
    BOOL _missedCallAtLaunch;
    BOOL _presentCallScreenAgainAfterDismiss;
    int _savedCallState;
    BOOL _recentlyDidCompleteDeleteAccount;
    BOOL _shareTooltipShown;
    BOOL _groupInfoTooltipShown;
    BOOL _settingsTooltipShown;
    BOOL _groupChatTooltipShown;
    BOOL _disablePushProcessing;
    BOOL _keyboardFailedToShow;
    BOOL _chatDatabaseAccessible;
    UIWindow *_window;
    WATabBarController *_tabBarController;
    VerificationController *_verificationController;
    NSString *_chatJID;
    WACallWindow *_callWindow;
    unsigned int _appWakeReason;
}

- (BOOL)isChatDatabaseAccessible;
- (void)setAppWakeReason:(unsigned int)fp8;
- (unsigned int)appWakeReason;
- (id)callWindow;
- (void)setChatJID:(id)fp8;
- (id)chatJID;
- (void)setKeyboardFailedToShow:(BOOL)fp8;
- (BOOL)keyboardFailedToShow;
- (void)setDisablePushProcessing:(BOOL)fp8;
- (BOOL)disablePushProcessing;
- (void)setGroupChatTooltipShown:(BOOL)fp8;
- (BOOL)groupChatTooltipShown;
- (void)setSettingsTooltipShown:(BOOL)fp8;
- (BOOL)settingsTooltipShown;
- (void)setGroupInfoTooltipShown:(BOOL)fp8;
- (BOOL)groupInfoTooltipShown;
- (void)setShareTooltipShown:(BOOL)fp8;
- (BOOL)shareTooltipShown;
- (BOOL)recentlyDidCompleteDeleteAccount;
- (id)verificationController;
- (id)tabBarController;
- (void)setWindow:(id)fp8;
- (id)window;
- (void).cxx_destruct;
- (void)application:(id)fp8 handleWatchKitExtensionRequest:(id)fp12 reply:(id)fp(null);
- (void)snapshotForAutomation;
- (void)openConnectionIfNeeded;
- (void)applicationReallyDidResume;
- (void)applicationDidResume;
- (void)applicationWillSuspendWithCompletionHandler:(id)fp(null);
- (void)askToUnblockJIDBeforeCalling:(id)fp8;
- (void)performVOIPActivitiesOnConnectionStateChange;
- (void)makeOutgoingCallToJIDIfPossible:(id)fp8;
- (void)switchToRecentsTab;
- (void)scheduleOutgoingCallToJIDOnConnect:(id)fp8;
- (void)makeVoiceCallViewControllerActive;
- (id)voiceCallViewControllerNeedsUpdatedSnapshot:(id)fp8;
- (void)voiceCallViewControllerWillResignActive:(id)fp8;
- (void)voiceCallViewController:(id)fp8 didRequestToShowChatWithJID:(id)fp12 presentKeyboard:(BOOL)fp16;
- (void)voiceCallViewControllerDidFinish:(id)fp8;
- (void)voiceCallViewControllerWillFinish:(id)fp8;
- (void)handleCallBusy;
- (void)handleCallTimeout;
- (void)handleCallFailureWithErrorCode:(int)fp8;
- (void)showNoCallingError;
- (void)cancelOutgoingCall;
- (void)handleCallTerminationByPeer;
- (void)dismissCallScreen;
- (void)forcePortraitOrientation;
- (void)reallyPresentCallScreenWithInitialCallState:(int)fp8;
- (void)presentCallScreenWithInitialCallState:(int)fp8;
- (BOOL)isCallWindowVisible;
- (void)application:(id)fp8 didChangeStatusBarOrientation:(int)fp12;
- (void)application:(id)fp8 willChangeStatusBarOrientation:(int)fp12 duration:(double)fp16;
- (void)chatDatabaseMigrationViewController:(id)fp8 didCompleteSuccessfully:(BOOL)fp12;
- (void)restoreBackupViewControllerDidFinish:(id)fp8;
- (void)restoreFromBackupAfterFailedDatabaseRepairWithNavigationController:(id)fp8;
- (void)showUnableToRecoverChatHistoryErrorAndTerminate;
- (void)proceedAfterRestoringOrRepairingDatabase;
- (void)repairDatabaseViewControllerDidFail:(id)fp8;
- (void)showUnexpectedDatabaseStateAndTerminate;
- (void)repairDatabaseViewControllerDidSucceed:(id)fp8;
- (void)performChatDatabaseRepair;
- (void)performPostRestoreChangesIfNecessary;
- (BOOL)isChatDatabaseReady;
- (void)registerForMigrationAndRepairNotifications;
- (void)switchToVerificationController:(id)fp8;
- (void)detectMobileNetworkChange;
- (void)startChangeNumberIfPossible;
- (void)startChangeNumberSequence;
- (void)deleteAccountControllerDidCancel:(id)fp8;
- (void)deleteAccountControllerDidFinish:(id)fp8;
- (void)reallyDeleteAccount;
- (void)startDeleteAccountSequence;
- (void)verificationControllerDidCancel:(id)fp8;
- (void)verificationControllerDidSucceed:(id)fp8;
- (void)chatStorageDidReceiveMessage:(id)fp8;
- (void)chatManagerDidChangeTimelockState:(id)fp8;
- (void)chatStorageDidDeleteDatabase:(id)fp8;
- (void)chatStorageDidLoadDatabase:(id)fp8;
- (void)tabBarController:(id)fp8 didSelectViewController:(id)fp12;
- (BOOL)tabBarController:(id)fp8 shouldSelectViewController:(id)fp12;
- (void)submitPushTokensIfReady;
- (void)pushRegistry:(id)fp8 didInvalidatePushTokenForType:(id)fp12;
- (void)pushRegistry:(id)fp8 didReceiveIncomingPushWithPayload:(id)fp12 forType:(id)fp16;
- (void)pushRegistry:(id)fp8 didUpdatePushCredentials:(id)fp12 forType:(id)fp16;
- (void)application:(id)fp8 didFailToRegisterForRemoteNotificationsWithError:(id)fp12;
- (void)application:(id)fp8 didRegisterForRemoteNotificationsWithDeviceToken:(id)fp12;
- (void)registerForPushTokens;
- (void)registerForVOIPPushIfNeeded;
- (void)application:(id)fp8 performActionForShortcutItem:(id)fp12 completionHandler:(id)fp(null);
- (void)processNewChatApplicationShortcut;
- (void)processSearchApplicationShortcut;
- (void)prepareUIForShortcutActionWithCompletion:(id)fp(null);
- (void)processApplicationShortcutAction:(id)fp8;
- (void)configureShortcutItemsForApplication:(id)fp8;
- (void)application:(id)fp8 performFetchWithCompletionHandler:(id)fp(null);
- (void)application:(id)fp8 handleEventsForBackgroundURLSession:(id)fp12 completionHandler:(id)fp(null);
- (void)application:(id)fp8 handleActionWithIdentifier:(id)fp12 forRemoteNotification:(id)fp16 completionHandler:(id)fp(null);
- (void)application:(id)fp8 handleActionWithIdentifier:(id)fp12 withResponseInfo:(id)fp16 completionHandler:(id)fp(null) jid:(void)fp20;
- (void)application:(id)fp8 handleActionWithIdentifier:(id)fp12 forRemoteNotification:(id)fp16 withResponseInfo:(id)fp20 completionHandler:(id)fp(null);
- (void)application:(id)fp8 handleActionWithIdentifier:(id)fp12 forLocalNotification:(id)fp16 withResponseInfo:(id)fp20 completionHandler:(id)fp(null);
- (void)application:(id)fp8 handleActionWithIdentifier:(id)fp12 forLocalNotification:(id)fp16 completionHandler:(id)fp(null);
- (void)applicationUserDidTakeScreenshot:(id)fp8;
- (unsigned int)application:(id)fp8 supportedInterfaceOrientationsForWindow:(id)fp12;
- (void)application:(id)fp8 reallyDidReceiveRemoteNotification:(id)fp12 fetchCompletionHandler:(id)fp(null);
- (void)application:(id)fp8 didReceiveRemoteNotification:(id)fp12 fetchCompletionHandler:(id)fp(null);
- (void)application:(id)fp8 reallyDidReceiveRemoteNotification:(id)fp12;
- (void)application:(id)fp8 didReceiveRemoteNotification:(id)fp12;
- (void)application:(id)fp8 reallyDidReceiveLocalNotification:(id)fp12;
- (void)application:(id)fp8 didReceiveLocalNotification:(id)fp12;
- (void)application:(id)fp8 didRegisterUserNotificationSettings:(id)fp12;
- (void)applicationDidReceiveMemoryWarning:(id)fp8;
- (void)applicationDidEnterBackground:(id)fp8;
- (void)applicationReallyWillEnterForeground:(id)fp8;
- (void)applicationWillEnterForeground:(id)fp8;
- (void)applicationWillResignActive:(id)fp8;
- (void)applicationReallyDidBecomeActive:(id)fp8;
- (void)applicationDidBecomeActive:(id)fp8;
- (void)applicationWillTerminate:(id)fp8;
- (BOOL)application:(id)fp8 openURL:(id)fp12 sourceApplication:(id)fp16 annotation:(id)fp20;
- (BOOL)application:(id)fp8 reallyDidFinishLaunchingWithOptions:(id)fp12 andPreviousLaunchResult:(int)fp16;
- (BOOL)application:(id)fp8 didFinishLaunchingWithOptions:(id)fp12;
- (void)reportPreviousCrashesWithPreviousLaunchResult:(int)fp8;
- (void)checkForDiedWhileDisconnecting;
- (void)checkForFailedToLaunchWithPreviousResult:(int)fp8;
- (void)stopWatchingForFailedToLaunch;
- (void)setFailedToLaunchReason:(int)fp8;
- (void)checkForGeneralCrashes;
- (void)initializePreferences;
- (void)connectionStateDidChange:(id)fp8;
- (void)updateApplicationBadgeCountAllowDecrements:(BOOL)fp8;
- (BOOL)isApplicationBadgeEnabled;
- (void)launchChatFromInAppAlert:(id)fp8 forJID:(id)fp12;
- (void)showDeferredNotifications;
- (void)showInAppNotificationAlertForMessage:(id)fp8;
- (void)notificationWindowTapped:(id)fp8;
- (void)showInAppNotificationBannerForMessage:(id)fp8;
- (void)showInAppNotificationForMessage:(id)fp8;
- (void)requestAccessToContactsIfNecessary;
- (void)checkAddressBookPermissionsWithCompletionHandler:(id)fp(null);
- (void)doHelperTasksAfterApplicationLaunch:(BOOL)fp8;
- (void)showSettingsTooltipIfNeeded;
- (void)loadApplicationUI;
- (void)setupRootViewController;
- (void)setupRootViewControllerIfPossible;
- (void)configureTabBarController;
- (void)callabilityDidChange:(id)fp8;
- (unsigned int)indexOfRecentsTab;
- (id)callHistoryTabBarItem;
- (void)resetViewControllers;
- (void)presentStorageAlert;
- (void)openChatAnimated:(BOOL)fp8 presentKeyboard:(BOOL)fp12;
- (void)jumpToAllChatsAnimated:(BOOL)fp8;
- (id)chatListViewController;
- (void)showMicrophoneAccessReminderScreen;
- (void)presentHelperScreenIfNecessary;
- (void)performLegacyPushSettingsCheck;
- (void)presentAppReviewPromptIfNecessaryWithCompletion:(id)fp(null);
- (void)reauthenticate;
- (void)performBlockAfterFirstUnlock:(id)fp(null);
- (void)protectedDataDidBecomeAvailable:(id)fp8;
- (void)setChatDatabaseAccessible:(BOOL)fp8;
- (id)init;
- (id)jidFromLocalNotification:(id)fp8;
- (id)jidFromUserInfo:(id)fp8;
- (void)checkForUpdatedBetaBuildIfNeeded;
- (id)strippedRemoteNotification:(id)fp8;
- (void)processLocalNotificationAtLaunch:(id)fp8;
- (void)processPushInfo:(id)fp8;
- (void)generateMemoryWarning:(id)fp8;
- (void)callBackJID:(id)fp8;
- (void)declineCall;
- (void)notifyReplyFailedForJID:(id)fp8 contactName:(id)fp12;
- (void)replyWithMessage:(id)fp8 toJID:(id)fp12 withCompletionHandler:(id)fp(null) markAsRead:(void)fp16;

@end

