/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_XMPPWebClientRequest.h"

@interface XMPPRequestWebClientSendContactsGroupsLists : _XMPPWebClientRequest
{
}

- (id)initWithPhones:(id)fp8 groups:(id)fp12 lists:(id)fp16 requestID:(id)fp20 isDuplicate:(BOOL)fp24 isPreemptive:(BOOL)fp28 forWebSession:(id)fp32 completion:(id)fp(null);

@end

