/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_XMPPRequestWebClientLogin.h"

@interface XMPPRequestWebClientAcceptPersistentLogin : _XMPPRequestWebClientLogin
{
    BOOL _isResume;
}

- (id)syncElementWithWebReference:(id)fp8;
- (id)initWithWebReference:(id)fp8 clientToken:(id)fp12 isResume:(BOOL)fp16 completion:(id)fp(null);

@end

