/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "XMPPStanza.h"

@interface XMPPNotificationStanza : XMPPStanza
{
}

+ (unsigned int)typeForString:(id)fp8;
+ (id)stringForType:(unsigned int)fp8;
+ (id)stringsForTypes;
- (id)log;
- (id)nickname;
- (id)text;
- (void)setType:(unsigned int)fp8;
- (unsigned int)type;
- (id)initWithType:(unsigned int)fp8;

@end

