/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "XMPPGroupRequest.h"

@class NSArray;

@interface XMPPGroupParticipantsRequest : XMPPGroupRequest
{
    NSArray *_participantJIDs;
}

- (id)participantJIDs;
- (void).cxx_destruct;
- (id)initWithGroupJID:(id)fp8 participantJIDs:(id)fp12;

@end

