/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface XMPPContactCapability : NSObject {
	NSString* _jid;
	int _urlCapable;
	int _encV1Capable;
	int _encV2Capable;
	int _encGroupCapable;
	int _voipCapable;
	int _encContactCapable;
	int _encImageCapable;
	int _encLocationCapable;
	int _encAudioCapable;
	int _encVideoCapable;
	int _encBlistCapable;
	int _documentCapable;
	int _identityVerification;
}
@property(assign, nonatomic) int identityVerification;
@property(assign, nonatomic) int documentCapable;
@property(assign, nonatomic) int encBlistCapable;
@property(assign, nonatomic) int encVideoCapable;
@property(assign, nonatomic) int encAudioCapable;
@property(assign, nonatomic) int encLocationCapable;
@property(assign, nonatomic) int encImageCapable;
@property(assign, nonatomic) int encContactCapable;
@property(assign, nonatomic) int voipCapable;
@property(assign, nonatomic) int encGroupCapable;
@property(assign, nonatomic) int encV2Capable;
@property(assign, nonatomic) int encV1Capable;
@property(assign, nonatomic) int urlCapable;
@property(retain, nonatomic) NSString* jid;
+(int)stringToType:(id)type;
-(void).cxx_destruct;
-(id)description;
@end

