/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XMPPRequest.h"


__attribute__((visibility("hidden")))
@interface XMPPRequestGetProfilePicture : XMPPRequest {
}
@property(copy, nonatomic) id completion;
-(void)didFailWithError:(id)error;
-(void)didSuceedWithResponse:(id)response;
-(id)initWithJID:(id)jid pictureType:(unsigned)type currentIdentifier:(id)identifier completion:(id)completion;
@end

