/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XMPPRequest.h"


__attribute__((visibility("hidden")))
@interface XMPPRequestPushConfig : XMPPRequest {
}
-(id)initWithGlobalConfig:(id)globalConfig customSettings:(id)settings completion:(id)completion;
-(void)_setPlatformExtrasConfigOn:(id)on;
-(void)_setConfigOn:(id)on;
@end

