/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_XMPPWebClientRequest.h"

@interface XMPPRequestWebClientForwardSingleMessage : _XMPPWebClientRequest
{
}

- (id)initWithMessage:(id)fp8 invisible:(BOOL)fp12 update:(BOOL)fp16 forWebSession:(id)fp20 completion:(id)fp(null);

@end

