/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XMPPStanza.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface XMPPPresenceStanza : XMPPStanza {
}
@property(retain, nonatomic) NSString* nickname;
@property(assign, nonatomic) unsigned presence;
+(unsigned)presenceForString:(id)string;
+(id)stringForPresence:(unsigned)presence;
+(id)stringsForPresences;
+(id)stanzaWithPresence:(unsigned)presence nickname:(id)nickname;
-(id)log;
-(id)initWithPresence:(unsigned)presence toJID:(id)jid;
@end

