/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "XMPPRequest.h"

@interface XMPPRequestUploadURL : XMPPRequest
{
}

- (void)didFailWithError:(id)fp8;
- (void)didSuceedWithResponse:(id)fp8;
- (id)initWithFileHash:(id)fp8 origHash:(id)fp12 fileSize:(unsigned long long)fp16 mediaType:(unsigned int)fp24 mediaIndex:(int)fp28 totalMediaCount:(int)fp32 completion:(id)fp(null);

@end

