/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_XMPPWebClientRequest.h"

@interface XMPPRequestWebClientSendReceiptUpdates : _XMPPWebClientRequest
{
}

- (id)initWithReceipts:(id)fp8 requestID:(id)fp12 forWebSession:(id)fp16 completion:(id)fp(null);

@end

