/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class NSData;

@interface XMPPRC4Coder : _ABAddressBookCopyArrayOfAllGroups
{
    NSData *_key;
    struct _CCCryptor *_cryptor;
}

- (void).cxx_destruct;
- (id)process:(id)fp8;
- (void)drop:(int)fp8;
- (void)reset:(id)fp8;
- (void)dealloc;
- (void)clean;

@end

