/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "XMPPGroupParticipantsRequest.h"


__attribute__((visibility("hidden")))
@interface XMPPRequestDemoteParticipants : XMPPGroupParticipantsRequest {
}
@property(copy, nonatomic) id completion;
-(void)didFailWithError:(id)error;
-(void)didSuceedWithResponse:(id)response;
-(id)initWithGroupJID:(id)groupJID participantJIDs:(id)jids completion:(id)completion;
@end

