/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@interface XMPPError : _ABAddressBookCopyArrayOfAllGroups
{
}

+ (id)errorWithCode:(int)fp8;
+ (id)errorAborted;
+ (id)errorCancelled;
+ (id)errorUnknown;
+ (id)errorNotConnected;
+ (id)errorTimeout;

@end

