/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSDate, NSString, NSDictionary;

__attribute__((visibility("hidden")))
@interface XMPPGroupNotification : NSObject {
	BOOL _offlineStorage;
	BOOL _receivedWithActiveWebClientSession;
	NSString* _groupJID;
	NSString* _participantJID;
	NSString* _participantName;
	NSDate* _timestamp;
	NSDictionary* _userInfo;
}
@property(readonly, assign, nonatomic, getter=isReceivedWithActiveWebClientSession) BOOL receivedWithActiveWebClientSession;
@property(retain, nonatomic) NSDictionary* userInfo;
@property(readonly, assign, nonatomic) BOOL offlineStorage;
@property(readonly, assign, nonatomic) NSDate* timestamp;
@property(readonly, copy, nonatomic) NSString* participantName;
@property(copy, nonatomic) NSString* participantJID;
@property(readonly, copy, nonatomic) NSString* groupJID;
-(void).cxx_destruct;
-(id)initWithGroupNotificationStanza:(id)groupNotificationStanza;
@end

