/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "XMPPRequest.h"

@interface XMPPE2ERequestPreKeyDigest : XMPPRequest
{
}

- (void)didFailWithError:(id)fp8;
- (void)didSuceedWithResponse:(id)fp8;
- (id)initWithCompletion:(id)fp(null);

@end

