/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class NSDate, NSLock, NSString;

@interface XMPPClient : _ABAddressBookCopyArrayOfAllGroups
{
    unsigned int _lastSentChatState;
    NSLock *_outgoingChatStateLock;
    unsigned int _lastReceivedChatState;
    NSLock *_incomingChatStateLock;
    unsigned int _presence;
    NSDate *_outgoingChatStateTimestamp;
    NSDate *_incomingChatStateTimestamp;
    NSString *_groupJIDForChatState;
    NSDate *_lastSeenTimestamp;
    NSString *_jid;
}

- (void)setJid:(id)fp8;
- (id)jid;
- (void)setLastSeenTimestamp:(id)fp8;
- (id)lastSeenTimestamp;
- (void)setGroupJIDForChatState:(id)fp8;
- (id)groupJIDForChatState;
- (void)setIncomingChatStateTimestamp:(id)fp8;
- (id)incomingChatStateTimestamp;
- (void)setOutgoingChatStateTimestamp:(id)fp8;
- (id)outgoingChatStateTimestamp;
- (void)setPresence:(unsigned int)fp8;
- (unsigned int)presence;
- (void).cxx_destruct;
- (void)setLastReceivedChatState:(unsigned int)fp8;
- (unsigned int)lastReceivedChatState;
- (void)setLastSentChatState:(unsigned int)fp8;
- (unsigned int)lastSentChatState;
- (void)reset;
- (id)initWithJID:(id)fp8;

@end

