/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "_XMPPWebClientRequest.h"


__attribute__((visibility("hidden")))
@interface XMPPRequestWebClientUpdateMessagesStarredState : _XMPPWebClientRequest {
}
-(id)initWithChatJID:(id)chatJID messages:(id)messages starred:(BOOL)starred forWebSession:(id)webSession completion:(id)completion;
@end

