/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "XMPPStanza.h"

@interface XMPPAckStanza : XMPPStanza
{
}

+ (unsigned int)typeForString:(id)fp8;
+ (id)stringForType:(unsigned int)fp8;
+ (id)stringsForTypes;
- (id)log;
- (int)count;
- (BOOL)negative;
- (void)setCallType:(unsigned int)fp8;
- (unsigned int)callType;
- (void)setNotificationType:(unsigned int)fp8;
- (unsigned int)notificationType;
- (void)setReceiptType:(unsigned int)fp8;
- (unsigned int)receiptType;
- (void)setMessageType:(unsigned int)fp8;
- (unsigned int)messageType;
- (void)setAckClass:(unsigned int)fp8;
- (unsigned int)ackClass;
- (id)initWithClass:(unsigned int)fp8;

@end

