/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllGroups.h"

@class XMPPIQStanza;

@interface XMPPRequest : _ABAddressBookCopyArrayOfAllGroups
{
    int _retriesRemaining;
    unsigned int _taskID;
    int _taskLock;
    XMPPIQStanza *_iq;
    unsigned int _state;
    XMPPIQStanza *_response;
    id _completion;
    double _timeout;
}

- (void)setCompletion:(id)fp8;
- (id)completion;
- (id)response;
- (unsigned int)state;
- (int)retriesRemaining;
- (double)timeout;
- (void)setIq:(id)fp8;
- (id)iq;
- (void).cxx_destruct;
- (void)didFailWithError:(id)fp8;
- (void)didSuceedWithResponse:(id)fp8;
- (void)processResponse:(id)fp8;
- (BOOL)cancelAndPrepareForRetry:(BOOL)fp8;
- (void)failOnNoConnection;
- (void)sendOnStream:(id)fp8;
- (void)endBackgroundTaskIfNeeded;
- (void)setState:(unsigned int)fp8;
- (id)initWithTimeout:(double)fp8;
- (id)init;

@end

