/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_XMPPRequestWebClientLogin.h"

@interface XMPPRequestWebClientInitiateRendezvous : _XMPPRequestWebClientLogin
{
}

- (id)initWithWebReference:(id)fp8 clientToken:(id)fp12 password:(id)fp16 completion:(id)fp(null);

@end

