/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "_XMPPWebClientRequest.h"


__attribute__((visibility("hidden")))
@interface XMPPRequestWebClientSendGroupInfo : _XMPPWebClientRequest {
}
-(id)initWithChatSession:(id)chatSession requestID:(id)anId forWebSession:(id)webSession completion:(id)completion;
@end

